-- ============================================================
-- TU KHO TRONG TRUYEN KINH DIEN — sinh tu tools/books/gen_gloss.py
--
-- Nhung tu KHONG co trong bang words (giao trinh hoc tu vung) nhung
-- gap lien tuc khi doc truyen. Tach bang rieng de khong lam loang
-- cac khoa hoc tu vung.
--
-- Chay books_schema.sql TRUOC file nay. An toan chay lai nhieu lan.
-- ============================================================

insert into public.book_words (word, meaning) values
  ('abbey', 'tu viện'),
  ('absence', 'sự vắng mặt'),
  ('absolute', 'tuyệt đối'),
  ('absolutely', 'tuyệt đối, hoàn toàn'),
  ('according', 'according to: theo như'),
  ('acquaintance', 'người quen; sự quen biết'),
  ('across', 'băng qua, bên kia'),
  ('act', 'đạo luật; hành động; màn kịch'),
  ('actually', 'thực ra, thực sự'),
  ('address', 'địa chỉ; nói với, xưng hô'),
  ('admiration', 'sự ngưỡng mộ'),
  ('advance', 'bước tiến; tiến lên'),
  ('affair', 'chuyện, vụ việc'),
  ('affection', 'tình cảm trìu mến'),
  ('afterwards', 'sau đó'),
  ('against', 'chống lại; dựa vào'),
  ('agreeable', 'dễ chịu, dễ mến'),
  ('along', 'dọc theo'),
  ('although', 'mặc dù'),
  ('altogether', 'hoàn toàn; tổng cộng'),
  ('amiable', 'hoà nhã, dễ mến'),
  ('anybody', 'bất cứ ai'),
  ('anyone', 'bất cứ ai'),
  ('anything', 'bất cứ thứ gì'),
  ('appointed', 'bổ nhiệm'),
  ('archbishop', 'tổng giám mục'),
  ('armies', 'các đạo quân'),
  ('army', 'quân đội'),
  ('arose', 'nảy sinh, xuất hiện'),
  ('assembled', 'tập hợp lại'),
  ('assure', 'cam đoan, bảo đảm'),
  ('assured', 'cam đoan; chắc chắn'),
  ('astonishment', 'sự kinh ngạc'),
  ('attempt', 'cố gắng, nỗ lực'),
  ('attended', 'tham dự; đi kèm'),
  ('authority', 'quyền lực; nhà chức trách'),
  ('band', 'nhóm, toán; ban nhạc'),
  ('baron', 'nam tước'),
  ('barons', 'các nam tước'),
  ('battle', 'trận đánh'),
  ('beat', 'đánh; nhịp đập'),
  ('beauty', 'vẻ đẹp; người đẹp'),
  ('beg', 'khẩn cầu, xin'),
  ('behaviour', 'cách cư xử, hành vi'),
  ('belief', 'niềm tin'),
  ('below', 'phía dưới'),
  ('beneath', 'bên dưới'),
  ('beside', 'bên cạnh'),
  ('besides', 'ngoài ra, hơn nữa'),
  ('beyond', 'vượt quá, bên kia'),
  ('bishop', 'giám mục'),
  ('bishops', 'các giám mục'),
  ('bit', 'một chút; đã cắn'),
  ('blow', 'cú đánh; thổi'),
  ('blue', 'màu xanh lam'),
  ('bold', 'táo bạo; in đậm'),
  ('bore', 'chịu đựng; mang (quá khứ của bear)'),
  ('bound', 'bị trói; chắc chắn sẽ'),
  ('bright', 'sáng; thông minh'),
  ('buried', 'chôn cất'),
  ('burnt', 'bị cháy, đã đốt'),
  ('camp', 'trại, doanh trại'),
  ('cannot', 'không thể'),
  ('cardinal', 'hồng y'),
  ('carriage', 'cỗ xe ngựa'),
  ('carried', 'mang, bế; đã chở'),
  ('castle', 'lâu đài'),
  ('caterpillar', 'con sâu bướm'),
  ('central', 'ở trung tâm'),
  ('centre', 'trung tâm'),
  ('certain', 'chắc chắn; một ... nào đó'),
  ('chapter', 'chương (sách)'),
  ('charge', 'lời buộc tội; phí; xông lên'),
  ('charming', 'duyên dáng, quyến rũ'),
  ('chief', 'thủ lĩnh; chính yếu'),
  ('chiefly', 'chủ yếu là'),
  ('circumstances', 'hoàn cảnh, tình cảnh'),
  ('civil', 'dân sự; nội bộ (civil war: nội chiến)'),
  ('civility', 'sự lịch thiệp, phép xã giao'),
  ('civilization', 'nền văn minh'),
  ('civilizations', 'các nền văn minh'),
  ('claim', 'yêu sách; đòi hỏi'),
  ('clergy', 'giới tăng lữ'),
  ('client', 'thân chủ, khách hàng'),
  ('colonel', 'đại tá'),
  ('colour', 'màu sắc'),
  ('command', 'quyền chỉ huy; ra lệnh'),
  ('committed', 'phạm (tội); cam kết'),
  ('companion', 'người bạn đồng hành'),
  ('compliment', 'lời khen'),
  ('concerned', 'lo lắng; có liên quan'),
  ('conduct', 'cách hành xử; dẫn dắt'),
  ('confess', 'thú nhận'),
  ('confusion', 'sự hỗn loạn, bối rối'),
  ('conquered', 'đã chinh phục, bị chinh phục'),
  ('conquest', 'cuộc chinh phục'),
  ('consent', 'sự đồng ý'),
  ('consequence', 'hậu quả; tầm quan trọng'),
  ('considerable', 'đáng kể'),
  ('conversation', 'cuộc trò chuyện'),
  ('convinced', 'tin chắc, bị thuyết phục'),
  ('council', 'hội đồng'),
  ('countenance', 'vẻ mặt, sắc mặt'),
  ('creature', 'sinh vật, con vật'),
  ('cried', 'kêu lên, thốt lên; đã khóc'),
  ('crime', 'tội ác'),
  ('cross', 'cây thánh giá; băng qua'),
  ('crossed', 'đã băng qua'),
  ('crowd', 'đám đông'),
  ('crown', 'vương miện; ngôi vua'),
  ('crowned', 'được lên ngôi, đội vương miện'),
  ('cruel', 'tàn nhẫn'),
  ('curiosity', 'sự tò mò'),
  ('custom', 'phong tục, tập quán'),
  ('dance', 'khiêu vũ, buổi khiêu vũ'),
  ('dancing', 'khiêu vũ'),
  ('dare', 'dám'),
  ('darkness', 'bóng tối'),
  ('dead', 'đã chết'),
  ('deal', 'lượng lớn (a great deal); giao dịch'),
  ('dear', 'thân mến; ôi trời (thán từ)'),
  ('declared', 'tuyên bố'),
  ('delight', 'niềm vui thích'),
  ('desire', 'khao khát, mong muốn'),
  ('determined', 'quyết tâm; đã xác định'),
  ('development', 'sự phát triển'),
  ('difficulty', 'sự khó khăn'),
  ('directly', 'trực tiếp; ngay lập tức'),
  ('dislike', 'sự không ưa'),
  ('disposition', 'tính khí, bản tính'),
  ('dominions', 'lãnh thổ cai trị'),
  ('down', 'xuống; đi xuống'),
  ('dreadful', 'khủng khiếp'),
  ('dropped', 'đánh rơi, thả xuống'),
  ('duke', 'công tước'),
  ('dying', 'đang hấp hối'),
  ('dynasty', 'triều đại, vương triều'),
  ('eagerly', 'hăm hở, háo hức'),
  ('earl', 'bá tước (tước Anh)'),
  ('easily', 'dễ dàng'),
  ('edge', 'mép, rìa; lưỡi dao'),
  ('education', 'giáo dục'),
  ('eight', 'tám'),
  ('eighteenth', 'thứ mười tám'),
  ('either', 'một trong hai; cũng (câu phủ định)'),
  ('eldest', 'lớn tuổi nhất (trong nhà)'),
  ('else', 'khác, nữa'),
  ('emperor', 'hoàng đế'),
  ('empire', 'đế quốc, đế chế'),
  ('empires', 'các đế quốc'),
  ('enemies', 'quân địch, kẻ thù'),
  ('enemy', 'kẻ thù'),
  ('enormous', 'khổng lồ'),
  ('entirely', 'hoàn toàn'),
  ('equal', 'ngang bằng'),
  ('established', 'thiết lập, thành lập'),
  ('estate', 'điền trang, cơ ngơi'),
  ('everybody', 'mọi người'),
  ('everything', 'mọi thứ'),
  ('evidently', 'rõ ràng là'),
  ('evil', 'cái ác; xấu xa'),
  ('exceedingly', 'vô cùng, hết sức'),
  ('excellent', 'xuất sắc, tuyệt vời'),
  ('except', 'ngoại trừ'),
  ('excuse', 'lời bào chữa; thứ lỗi'),
  ('executed', 'bị hành quyết; đã thi hành'),
  ('execution', 'cuộc hành quyết; sự thi hành'),
  ('existence', 'sự tồn tại'),
  ('expression', 'vẻ mặt; cách diễn đạt'),
  ('extraordinary', 'phi thường, khác thường'),
  ('extremely', 'vô cùng'),
  ('faith', 'đức tin; lòng tin'),
  ('faithful', 'trung thành'),
  ('fancy', 'tưởng tượng; thích; cầu kỳ'),
  ('fast', 'nhanh; chặt; nhịn ăn'),
  ('favour', 'sự ưu ái; việc giúp đỡ'),
  ('favourite', 'người được sủng ái; ưa thích nhất'),
  ('fear', 'nỗi sợ; sợ'),
  ('fellow', 'gã, chàng; bạn đồng hành'),
  ('few', 'ít, một vài'),
  ('fifteen', 'mười lăm'),
  ('fifth', 'thứ năm'),
  ('fifty', 'năm mươi'),
  ('figure', 'dáng người; con số; hình'),
  ('firm', 'vững chắc; công ty'),
  ('fled', 'bỏ chạy, chạy trốn'),
  ('fleet', 'hạm đội'),
  ('followers', 'những người đi theo'),
  ('fond', 'be fond of: thích, quý mến'),
  ('force', 'vũ lực, sức mạnh; ép buộc'),
  ('forced', 'bị ép buộc; gượng gạo'),
  ('forces', 'lực lượng, quân lực'),
  ('form', 'hình thức; mẫu đơn; tạo thành'),
  ('formed', 'hình thành, tạo nên'),
  ('former', 'trước kia; cái thứ nhất trong hai'),
  ('forth', 'ra phía trước (and so forth: vân vân)'),
  ('fortune', 'gia sản; vận may'),
  ('founded', 'sáng lập'),
  ('four', 'bốn'),
  ('fourth', 'thứ tư'),
  ('frequently', 'thường xuyên'),
  ('frightened', 'hoảng sợ'),
  ('gained', 'đạt được, giành được'),
  ('general', 'chung, phổ biến; vị tướng'),
  ('generally', 'nói chung, thường thì'),
  ('gentleman', 'quý ông, người đàn ông lịch thiệp'),
  ('gentlemen', 'các quý ông'),
  ('glad', 'vui mừng'),
  ('glance', 'cái liếc nhìn'),
  ('glanced', 'liếc nhìn'),
  ('glancing', 'đang liếc nhìn'),
  ('god', 'vị thần; Chúa'),
  ('gods', 'các vị thần'),
  ('golden', 'bằng vàng, vàng óng'),
  ('gradually', 'dần dần'),
  ('grave', 'nấm mồ; nghiêm trọng'),
  ('green', 'màu xanh lá'),
  ('grey', 'màu xám'),
  ('ground', 'mặt đất; khuôn viên'),
  ('guard', 'lính gác; canh gác'),
  ('hall', 'sảnh, đại sảnh'),
  ('happiness', 'hạnh phúc'),
  ('hastily', 'vội vàng'),
  ('heaven', 'thiên đường'),
  ('hitherto', 'cho đến nay, từ trước tới giờ'),
  ('holy', 'thiêng liêng, thánh'),
  ('honour', 'danh dự; vinh hạnh'),
  ('human', 'thuộc con người'),
  ('hunting', 'săn bắn'),
  ('hurried', 'vội vã'),
  ('ignorant', 'dốt nát, không biết'),
  ('ill', 'ốm, bệnh; xấu'),
  ('immediate', 'ngay lập tức; gần kề'),
  ('importance', 'tầm quan trọng'),
  ('impossible', 'không thể được'),
  ('impression', 'ấn tượng'),
  ('indeed', 'quả thật, thật vậy'),
  ('independent', 'độc lập'),
  ('innocent', 'vô tội; ngây thơ'),
  ('inquired', 'hỏi thăm, dò hỏi'),
  ('inquiries', 'những câu hỏi thăm dò'),
  ('inspector', 'thanh tra'),
  ('instant', 'khoảnh khắc; tức thì'),
  ('instantly', 'ngay lập tức'),
  ('instead', 'thay vì, thay vào đó'),
  ('intellectual', 'trí tuệ; trí thức'),
  ('intention', 'ý định'),
  ('invitation', 'lời mời'),
  ('joy', 'niềm vui sướng'),
  ('judge', 'quan toà; xét xử'),
  ('justice', 'công lý; quan toà'),
  ('kindness', 'lòng tốt'),
  ('kingdom', 'vương quốc'),
  ('knights', 'các hiệp sĩ'),
  ('ladies', 'các quý bà'),
  ('lady', 'quý bà, phu nhân'),
  ('laid', 'đặt, để (quá khứ của lay)'),
  ('land', 'vùng đất; đất liền; hạ cánh'),
  ('lands', 'các vùng đất'),
  ('latter', 'cái thứ hai trong hai'),
  ('lawn', 'bãi cỏ'),
  ('learnt', 'đã học, đã biết được'),
  ('length', 'chiều dài; at length: cuối cùng'),
  ('less', 'ít hơn'),
  ('lord', 'huân tước, lãnh chúa'),
  ('loss', 'sự mất mát; thua'),
  ('lying', 'đang nằm; nói dối'),
  ('mad', 'điên; tức giận'),
  ('madam', 'thưa bà'),
  ('maid', 'người hầu gái; thiếu nữ'),
  ('main', 'chính, chủ yếu'),
  ('mankind', 'loài người, nhân loại'),
  ('manners', 'cách cư xử, phép lịch sự'),
  ('many', 'nhiều'),
  ('march', 'cuộc hành quân; tháng Ba'),
  ('marched', 'hành quân'),
  ('mark', 'dấu; điểm số; đánh dấu'),
  ('marked', 'rõ rệt; đã đánh dấu'),
  ('marriage', 'hôn nhân, cuộc hôn nhân'),
  ('married', 'đã kết hôn; cưới'),
  ('master', 'ông chủ; bậc thầy'),
  ('material', 'vật chất; vật liệu'),
  ('mere', 'chỉ là, thuần tuý'),
  ('merely', 'chỉ, đơn thuần'),
  ('merry', 'vui vẻ'),
  ('miles', 'dặm (đơn vị đo, ~1,6 km)'),
  ('military', 'thuộc quân sự'),
  ('mine', 'của tôi'),
  ('minor', 'nhỏ, thứ yếu'),
  ('mistaken', 'nhầm lẫn'),
  ('monarch', 'quân vương, vua'),
  ('monks', 'các thầy tu'),
  ('moral', 'thuộc đạo đức'),
  ('murder', 'vụ giết người'),
  ('murdered', 'bị giết hại'),
  ('myself', 'chính tôi'),
  ('national', 'thuộc quốc gia'),
  ('natural', 'tự nhiên'),
  ('necessary', 'cần thiết'),
  ('neck', 'cổ'),
  ('neighbourhood', 'vùng lân cận, khu xóm'),
  ('neither', 'không cái nào trong hai'),
  ('nice', 'tử tế, dễ chịu'),
  ('nine', 'chín'),
  ('noble', 'quý tộc; cao thượng'),
  ('noblemen', 'các nhà quý tộc'),
  ('nobles', 'giới quý tộc'),
  ('nobody', 'không ai'),
  ('none', 'không ai, không cái nào'),
  ('nor', 'cũng không'),
  ('northern', 'thuộc phương Bắc'),
  ('nothing', 'không có gì'),
  ('object', 'vật, đồ vật; mục đích; phản đối'),
  ('obliged', 'buộc phải; hàm ơn'),
  ('observe', 'quan sát; nhận xét'),
  ('observed', 'quan sát thấy; nhận xét'),
  ('obvious', 'hiển nhiên, rõ ràng'),
  ('occasion', 'dịp, cơ hội'),
  ('occurred', 'xảy ra; chợt nảy ra trong đầu'),
  ('officers', 'sĩ quan; viên chức'),
  ('opposed', 'phản đối; đối lập'),
  ('otherwise', 'nếu không thì; cách khác'),
  ('ought', 'nên (ought to)'),
  ('palace', 'cung điện'),
  ('pale', 'nhợt nhạt, tái'),
  ('pardon', 'thứ lỗi, xin lỗi'),
  ('parliament', 'nghị viện, quốc hội'),
  ('particular', 'cụ thể, riêng biệt; kỹ tính'),
  ('particularly', 'đặc biệt là'),
  ('passage', 'lối đi, hành lang; đoạn văn'),
  ('pause', 'khoảng dừng; ngừng lại'),
  ('peace', 'hoà bình'),
  ('peculiar', 'kỳ quặc, riêng biệt'),
  ('perfect', 'hoàn hảo'),
  ('perfectly', 'hoàn toàn, một cách hoàn hảo'),
  ('personal', 'cá nhân, riêng tư'),
  ('persuaded', 'thuyết phục'),
  ('phase', 'giai đoạn'),
  ('photograph', 'bức ảnh'),
  ('piece', 'mảnh, miếng'),
  ('pieces', 'các mảnh'),
  ('plain', 'đồng bằng; giản dị; rõ ràng'),
  ('pleasant', 'dễ chịu, thú vị'),
  ('please', 'làm hài lòng; xin vui lòng'),
  ('pleased', 'hài lòng, vui'),
  ('pleasure', 'niềm vui, sự hài lòng'),
  ('plot', 'âm mưu; cốt truyện; mảnh đất'),
  ('political', 'thuộc chính trị'),
  ('pool', 'vũng nước, ao'),
  ('population', 'dân số'),
  ('possession', 'quyền sở hữu; vật sở hữu'),
  ('possessions', 'tài sản; thuộc địa'),
  ('possibility', 'khả năng'),
  ('possibly', 'có thể'),
  ('pounds', 'bảng Anh (tiền); pao (cân nặng)'),
  ('powerful', 'hùng mạnh'),
  ('presence', 'sự hiện diện'),
  ('pretended', 'giả vờ'),
  ('pride', 'lòng kiêu hãnh, sự tự hào'),
  ('priest', 'linh mục, thầy tế'),
  ('priests', 'các linh mục'),
  ('primitive', 'nguyên thuỷ, sơ khai'),
  ('prince', 'hoàng tử; thân vương'),
  ('princes', 'các hoàng tử'),
  ('princess', 'công chúa'),
  ('principal', 'chính, chủ yếu; hiệu trưởng'),
  ('prison', 'nhà tù'),
  ('prisoner', 'tù nhân, tù binh'),
  ('prisoners', 'các tù binh'),
  ('private', 'riêng tư'),
  ('probable', 'có khả năng xảy ra'),
  ('process', 'quá trình'),
  ('proper', 'đúng đắn, thích hợp'),
  ('property', 'tài sản, của cải'),
  ('proposed', 'đề nghị; cầu hôn'),
  ('proved', 'chứng tỏ, hoá ra là'),
  ('quarter', 'một phần tư; khu phố'),
  ('race', 'chủng tộc; cuộc đua'),
  ('railway', 'đường sắt'),
  ('rate', 'tỉ lệ; mức giá; tốc độ'),
  ('readily', 'sẵn sàng; dễ dàng'),
  ('record', 'ghi chép, hồ sơ; ghi lại'),
  ('red', 'màu đỏ'),
  ('regard', 'sự quan tâm, lòng kính trọng; xem như'),
  ('reign', 'triều đại; trị vì'),
  ('related', 'liên quan; kể lại'),
  ('relations', 'quan hệ'),
  ('religious', 'thuộc tôn giáo'),
  ('remark', 'lời nhận xét'),
  ('remarkable', 'đáng chú ý, phi thường'),
  ('remarked', 'nhận xét, nói'),
  ('removed', 'loại bỏ, dời đi'),
  ('replied', 'đáp lại, trả lời'),
  ('represented', 'đại diện; thể hiện'),
  ('republic', 'nền cộng hoà'),
  ('resolved', 'quyết định dứt khoát; đã giải quyết'),
  ('revolution', 'cuộc cách mạng'),
  ('rid', 'get rid of: thoát khỏi, bỏ đi'),
  ('rise', 'sự trỗi dậy; đứng lên'),
  ('rising', 'đang lên, trỗi dậy'),
  ('rose', 'đứng dậy, dâng lên; hoa hồng'),
  ('round', 'quanh, vòng quanh; tròn'),
  ('royal', 'thuộc hoàng gia'),
  ('sailed', 'đi thuyền, ra khơi'),
  ('saint', 'vị thánh'),
  ('sake', 'for the sake of: vì, cho'),
  ('satisfaction', 'sự hài lòng, thoả mãn'),
  ('savage', 'hung tợn, man rợ'),
  ('scarcely', 'hầu như không'),
  ('scene', 'cảnh, khung cảnh'),
  ('scientific', 'thuộc khoa học'),
  ('secure', 'an toàn; bảo đảm'),
  ('seized', 'chiếm lấy, bắt giữ'),
  ('sense', 'cảm giác; lý trí; ý nghĩa'),
  ('sensible', 'biết điều, khôn ngoan'),
  ('series', 'chuỗi, loạt'),
  ('servant', 'người hầu'),
  ('servants', 'những người hầu'),
  ('settled', 'đã yên vị; đã giải quyết xong'),
  ('seven', 'bảy'),
  ('several', 'vài, một số'),
  ('shall', 'sẽ (lối nói trang trọng/cổ)'),
  ('sharp', 'sắc bén; gay gắt'),
  ('shot', 'bắn; cú bắn'),
  ('shown', 'đã cho thấy'),
  ('shut', 'đóng lại'),
  ('sick', 'ốm, buồn nôn'),
  ('sight', 'cảnh tượng; thị lực'),
  ('silence', 'sự im lặng'),
  ('silent', 'im lặng'),
  ('silver', 'bạc'),
  ('similar', 'tương tự'),
  ('single', 'độc thân; đơn lẻ'),
  ('singular', 'kỳ lạ, khác thường; số ít'),
  ('sir', 'thưa ngài, thưa ông'),
  ('situation', 'tình huống, hoàn cảnh'),
  ('six', 'sáu'),
  ('sixth', 'thứ sáu'),
  ('slave', 'nô lệ'),
  ('slaves', 'những người nô lệ'),
  ('slight', 'nhẹ, không đáng kể'),
  ('solemn', 'trang nghiêm'),
  ('somebody', 'ai đó'),
  ('someone', 'ai đó'),
  ('somewhere', 'đâu đó'),
  ('sorry', 'tiếc, xin lỗi'),
  ('sort', 'loại, kiểu'),
  ('sought', 'tìm kiếm (quá khứ của seek)'),
  ('speech', 'bài diễn văn; lời nói'),
  ('spirit', 'tinh thần; linh hồn'),
  ('spirits', 'tinh thần, tâm trạng'),
  ('spite', 'in spite of: mặc dù; ác ý'),
  ('stage', 'giai đoạn; sân khấu'),
  ('state', 'trạng thái; tuyên bố; bang'),
  ('steadily', 'đều đặn'),
  ('steady', 'vững vàng, đều đặn'),
  ('step', 'bước chân; bậc'),
  ('steps', 'các bước; bậc thềm'),
  ('strength', 'sức mạnh'),
  ('struck', 'đánh trúng; gây ấn tượng mạnh'),
  ('struggle', 'cuộc đấu tranh; vật lộn'),
  ('successful', 'thành công'),
  ('such', 'như vậy, như thế'),
  ('sudden', 'đột ngột'),
  ('superior', 'cao cấp hơn; cấp trên'),
  ('supper', 'bữa tối'),
  ('suppose', 'cho rằng, đoán là'),
  ('supposed', 'được cho là; lẽ ra phải'),
  ('sword', 'thanh kiếm'),
  ('ten', 'mười'),
  ('terms', 'điều khoản; quan hệ (on good terms)'),
  ('therefore', 'vì vậy, do đó'),
  ('third', 'thứ ba'),
  ('thirty', 'ba mươi'),
  ('those', 'những cái đó, những người đó'),
  ('though', 'mặc dù'),
  ('thoughts', 'những suy nghĩ'),
  ('throne', 'ngai vàng'),
  ('through', 'xuyên qua, qua'),
  ('throughout', 'suốt, khắp'),
  ('thrust', 'đâm, xô mạnh'),
  ('thus', 'như vậy, do đó'),
  ('till', 'cho đến khi'),
  ('tone', 'giọng điệu'),
  ('toward', 'về phía'),
  ('towards', 'về phía'),
  ('tower', 'tháp; Tháp London'),
  ('traces', 'dấu vết'),
  ('treason', 'tội phản quốc'),
  ('treaty', 'hiệp ước'),
  ('trial', 'phiên toà; cuộc thử nghiệm'),
  ('tribes', 'các bộ lạc'),
  ('tried', 'đã thử, đã cố'),
  ('troops', 'quân lính'),
  ('twelve', 'mười hai'),
  ('twenty', 'hai mươi'),
  ('twice', 'hai lần'),
  ('unfortunate', 'không may'),
  ('unhappy', 'không vui, bất hạnh'),
  ('united', 'hợp nhất, thống nhất'),
  ('unless', 'trừ khi'),
  ('upon', 'trên; vào lúc (lối viết cổ của on)'),
  ('upstairs', 'trên gác, lên gác'),
  ('usual', 'thường lệ'),
  ('utmost', 'tột bậc, hết mức'),
  ('vain', 'in vain: vô ích; kiêu ngạo'),
  ('various', 'khác nhau, đa dạng'),
  ('vast', 'rộng lớn, mênh mông'),
  ('view', 'quang cảnh; quan điểm'),
  ('violent', 'hung bạo, dữ dội'),
  ('visitor', 'khách đến thăm'),
  ('western', 'thuộc phương Tây'),
  ('whatever', 'bất cứ điều gì'),
  ('whenever', 'bất cứ khi nào'),
  ('wherever', 'bất cứ nơi nào'),
  ('whether', 'liệu có... hay không'),
  ('whole', 'toàn bộ, cả'),
  ('whom', 'người mà (tân ngữ của who)'),
  ('whose', 'của ai, mà ... của người đó'),
  ('within', 'bên trong; trong vòng'),
  ('witness', 'nhân chứng; chứng kiến'),
  ('worth', 'đáng giá'),
  ('wretched', 'khốn khổ, thảm hại'),
  ('yellow', 'màu vàng'),
  ('youth', 'tuổi trẻ; thanh niên')
on conflict (word) do update set meaning = excluded.meaning;
