-- ============================================================
-- TU KHO TRONG TRUYEN KINH DIEN — sinh tu tools/books/gen_gloss.py
--
-- Nhung tu KHONG co trong bang words (giao trinh hoc tu vung) nhung
-- gap lien tuc khi doc truyen. Tach bang rieng de khong lam loang
-- cac khoa hoc tu vung.
--
-- Chay books_schema.sql TRUOC file nay. An toan chay lai nhieu lan.
-- ============================================================

insert into public.book_words (word, meaning) values
  ('absence', 'sự vắng mặt'),
  ('absolutely', 'tuyệt đối, hoàn toàn'),
  ('acquaintance', 'người quen; sự quen biết'),
  ('across', 'băng qua, bên kia'),
  ('address', 'địa chỉ; nói với, xưng hô'),
  ('admiration', 'sự ngưỡng mộ'),
  ('affair', 'chuyện, vụ việc'),
  ('affection', 'tình cảm trìu mến'),
  ('afterwards', 'sau đó'),
  ('against', 'chống lại; dựa vào'),
  ('agreeable', 'dễ chịu, dễ mến'),
  ('along', 'dọc theo'),
  ('amiable', 'hoà nhã, dễ mến'),
  ('anybody', 'bất cứ ai'),
  ('anyone', 'bất cứ ai'),
  ('anything', 'bất cứ thứ gì'),
  ('assure', 'cam đoan, bảo đảm'),
  ('assured', 'cam đoan; chắc chắn'),
  ('astonishment', 'sự kinh ngạc'),
  ('attempt', 'cố gắng, nỗ lực'),
  ('beauty', 'vẻ đẹp; người đẹp'),
  ('beg', 'khẩn cầu, xin'),
  ('behaviour', 'cách cư xử, hành vi'),
  ('beside', 'bên cạnh'),
  ('besides', 'ngoài ra, hơn nữa'),
  ('beyond', 'vượt quá, bên kia'),
  ('bit', 'một chút; đã cắn'),
  ('blue', 'màu xanh lam'),
  ('bright', 'sáng; thông minh'),
  ('cannot', 'không thể'),
  ('carriage', 'cỗ xe ngựa'),
  ('carried', 'mang, bế; đã chở'),
  ('caterpillar', 'con sâu bướm'),
  ('certain', 'chắc chắn; một ... nào đó'),
  ('charming', 'duyên dáng, quyến rũ'),
  ('circumstances', 'hoàn cảnh, tình cảnh'),
  ('civility', 'sự lịch thiệp, phép xã giao'),
  ('client', 'thân chủ, khách hàng'),
  ('colonel', 'đại tá'),
  ('colour', 'màu sắc'),
  ('companion', 'người bạn đồng hành'),
  ('compliment', 'lời khen'),
  ('concerned', 'lo lắng; có liên quan'),
  ('conduct', 'cách hành xử; dẫn dắt'),
  ('confess', 'thú nhận'),
  ('consequence', 'hậu quả; tầm quan trọng'),
  ('considerable', 'đáng kể'),
  ('conversation', 'cuộc trò chuyện'),
  ('convinced', 'tin chắc, bị thuyết phục'),
  ('countenance', 'vẻ mặt, sắc mặt'),
  ('creature', 'sinh vật, con vật'),
  ('cried', 'kêu lên, thốt lên; đã khóc'),
  ('crime', 'tội ác'),
  ('curiosity', 'sự tò mò'),
  ('dance', 'khiêu vũ, buổi khiêu vũ'),
  ('dancing', 'khiêu vũ'),
  ('dare', 'dám'),
  ('dead', 'đã chết'),
  ('deal', 'lượng lớn (a great deal); giao dịch'),
  ('dear', 'thân mến; ôi trời (thán từ)'),
  ('delight', 'niềm vui thích'),
  ('desire', 'khao khát, mong muốn'),
  ('determined', 'quyết tâm; đã xác định'),
  ('disposition', 'tính khí, bản tính'),
  ('down', 'xuống; đi xuống'),
  ('dreadful', 'khủng khiếp'),
  ('dropped', 'đánh rơi, thả xuống'),
  ('eagerly', 'hăm hở, háo hức'),
  ('easily', 'dễ dàng'),
  ('either', 'một trong hai; cũng (câu phủ định)'),
  ('else', 'khác, nữa'),
  ('entirely', 'hoàn toàn'),
  ('equal', 'ngang bằng'),
  ('estate', 'điền trang, cơ ngơi'),
  ('everybody', 'mọi người'),
  ('everything', 'mọi thứ'),
  ('evidently', 'rõ ràng là'),
  ('exceedingly', 'vô cùng, hết sức'),
  ('excellent', 'xuất sắc, tuyệt vời'),
  ('except', 'ngoại trừ'),
  ('excuse', 'lời bào chữa; thứ lỗi'),
  ('expression', 'vẻ mặt; cách diễn đạt'),
  ('extraordinary', 'phi thường, khác thường'),
  ('fancy', 'tưởng tượng; thích; cầu kỳ'),
  ('favour', 'sự ưu ái; việc giúp đỡ'),
  ('fear', 'nỗi sợ; sợ'),
  ('fellow', 'gã, chàng; bạn đồng hành'),
  ('few', 'ít, một vài'),
  ('figure', 'dáng người; con số; hình'),
  ('forced', 'bị ép buộc; gượng gạo'),
  ('formed', 'hình thành, tạo nên'),
  ('former', 'trước kia; cái thứ nhất trong hai'),
  ('fortune', 'gia sản; vận may'),
  ('four', 'bốn'),
  ('frequently', 'thường xuyên'),
  ('frightened', 'hoảng sợ'),
  ('general', 'chung, phổ biến; vị tướng'),
  ('generally', 'nói chung, thường thì'),
  ('gentleman', 'quý ông, người đàn ông lịch thiệp'),
  ('gentlemen', 'các quý ông'),
  ('glad', 'vui mừng'),
  ('glance', 'cái liếc nhìn'),
  ('glanced', 'liếc nhìn'),
  ('glancing', 'đang liếc nhìn'),
  ('grey', 'màu xám'),
  ('ground', 'mặt đất; khuôn viên'),
  ('hall', 'sảnh, đại sảnh'),
  ('happiness', 'hạnh phúc'),
  ('hastily', 'vội vàng'),
  ('honour', 'danh dự; vinh hạnh'),
  ('hurried', 'vội vã'),
  ('ill', 'ốm, bệnh; xấu'),
  ('importance', 'tầm quan trọng'),
  ('impossible', 'không thể được'),
  ('impression', 'ấn tượng'),
  ('indeed', 'quả thật, thật vậy'),
  ('inquired', 'hỏi thăm, dò hỏi'),
  ('inquiries', 'những câu hỏi thăm dò'),
  ('inspector', 'thanh tra'),
  ('instant', 'khoảnh khắc; tức thì'),
  ('instantly', 'ngay lập tức'),
  ('instead', 'thay vì, thay vào đó'),
  ('intention', 'ý định'),
  ('invitation', 'lời mời'),
  ('kindness', 'lòng tốt'),
  ('ladies', 'các quý bà'),
  ('lady', 'quý bà, phu nhân'),
  ('laid', 'đặt, để (quá khứ của lay)'),
  ('latter', 'cái thứ hai trong hai'),
  ('lawn', 'bãi cỏ'),
  ('length', 'chiều dài; at length: cuối cùng'),
  ('less', 'ít hơn'),
  ('lord', 'huân tước, lãnh chúa'),
  ('lying', 'đang nằm; nói dối'),
  ('mad', 'điên; tức giận'),
  ('madam', 'thưa bà'),
  ('manners', 'cách cư xử, phép lịch sự'),
  ('many', 'nhiều'),
  ('marked', 'rõ rệt; đã đánh dấu'),
  ('marriage', 'hôn nhân, cuộc hôn nhân'),
  ('married', 'đã kết hôn; cưới'),
  ('master', 'ông chủ; bậc thầy'),
  ('merely', 'chỉ, đơn thuần'),
  ('miles', 'dặm (đơn vị đo, ~1,6 km)'),
  ('mine', 'của tôi'),
  ('mistaken', 'nhầm lẫn'),
  ('myself', 'chính tôi'),
  ('natural', 'tự nhiên'),
  ('necessary', 'cần thiết'),
  ('neighbourhood', 'vùng lân cận, khu xóm'),
  ('neither', 'không cái nào trong hai'),
  ('nice', 'tử tế, dễ chịu'),
  ('nobody', 'không ai'),
  ('none', 'không ai, không cái nào'),
  ('nor', 'cũng không'),
  ('nothing', 'không có gì'),
  ('object', 'vật, đồ vật; mục đích; phản đối'),
  ('obliged', 'buộc phải; hàm ơn'),
  ('observe', 'quan sát; nhận xét'),
  ('observed', 'quan sát thấy; nhận xét'),
  ('obvious', 'hiển nhiên, rõ ràng'),
  ('occasion', 'dịp, cơ hội'),
  ('occurred', 'xảy ra; chợt nảy ra trong đầu'),
  ('officers', 'sĩ quan; viên chức'),
  ('ought', 'nên (ought to)'),
  ('pale', 'nhợt nhạt, tái'),
  ('pardon', 'thứ lỗi, xin lỗi'),
  ('particular', 'cụ thể, riêng biệt; kỹ tính'),
  ('particularly', 'đặc biệt là'),
  ('passage', 'lối đi, hành lang; đoạn văn'),
  ('pause', 'khoảng dừng; ngừng lại'),
  ('peculiar', 'kỳ quặc, riêng biệt'),
  ('perfect', 'hoàn hảo'),
  ('perfectly', 'hoàn toàn, một cách hoàn hảo'),
  ('photograph', 'bức ảnh'),
  ('pleasant', 'dễ chịu, thú vị'),
  ('please', 'làm hài lòng; xin vui lòng'),
  ('pleased', 'hài lòng, vui'),
  ('pleasure', 'niềm vui, sự hài lòng'),
  ('pool', 'vũng nước, ao'),
  ('pounds', 'bảng Anh (tiền); pao (cân nặng)'),
  ('presence', 'sự hiện diện'),
  ('pride', 'lòng kiêu hãnh, sự tự hào'),
  ('private', 'riêng tư'),
  ('red', 'màu đỏ'),
  ('regard', 'sự quan tâm, lòng kính trọng; xem như'),
  ('remark', 'lời nhận xét'),
  ('remarkable', 'đáng chú ý, phi thường'),
  ('remarked', 'nhận xét, nói'),
  ('replied', 'đáp lại, trả lời'),
  ('resolved', 'quyết định dứt khoát; đã giải quyết'),
  ('rose', 'đứng dậy, dâng lên; hoa hồng'),
  ('round', 'quanh, vòng quanh; tròn'),
  ('sake', 'for the sake of: vì, cho'),
  ('satisfaction', 'sự hài lòng, thoả mãn'),
  ('scarcely', 'hầu như không'),
  ('scene', 'cảnh, khung cảnh'),
  ('sense', 'cảm giác; lý trí; ý nghĩa'),
  ('sensible', 'biết điều, khôn ngoan'),
  ('settled', 'đã yên vị; đã giải quyết xong'),
  ('seven', 'bảy'),
  ('several', 'vài, một số'),
  ('shall', 'sẽ (lối nói trang trọng/cổ)'),
  ('sharp', 'sắc bén; gay gắt'),
  ('shown', 'đã cho thấy'),
  ('sight', 'cảnh tượng; thị lực'),
  ('silence', 'sự im lặng'),
  ('silent', 'im lặng'),
  ('single', 'độc thân; đơn lẻ'),
  ('singular', 'kỳ lạ, khác thường; số ít'),
  ('sir', 'thưa ngài, thưa ông'),
  ('situation', 'tình huống, hoàn cảnh'),
  ('six', 'sáu'),
  ('slight', 'nhẹ, không đáng kể'),
  ('somebody', 'ai đó'),
  ('someone', 'ai đó'),
  ('somewhere', 'đâu đó'),
  ('sorry', 'tiếc, xin lỗi'),
  ('sort', 'loại, kiểu'),
  ('spirits', 'tinh thần, tâm trạng'),
  ('spite', 'in spite of: mặc dù; ác ý'),
  ('state', 'trạng thái; tuyên bố; bang'),
  ('step', 'bước chân; bậc'),
  ('steps', 'các bước; bậc thềm'),
  ('struck', 'đánh trúng; gây ấn tượng mạnh'),
  ('such', 'như vậy, như thế'),
  ('sudden', 'đột ngột'),
  ('suppose', 'cho rằng, đoán là'),
  ('supposed', 'được cho là; lẽ ra phải'),
  ('ten', 'mười'),
  ('therefore', 'vì vậy, do đó'),
  ('those', 'những cái đó, những người đó'),
  ('though', 'mặc dù'),
  ('thoughts', 'những suy nghĩ'),
  ('through', 'xuyên qua, qua'),
  ('thus', 'như vậy, do đó'),
  ('till', 'cho đến khi'),
  ('tone', 'giọng điệu'),
  ('toward', 'về phía'),
  ('towards', 'về phía'),
  ('tried', 'đã thử, đã cố'),
  ('twice', 'hai lần'),
  ('unless', 'trừ khi'),
  ('upon', 'trên; vào lúc (lối viết cổ của on)'),
  ('upstairs', 'trên gác, lên gác'),
  ('usual', 'thường lệ'),
  ('view', 'quang cảnh; quan điểm'),
  ('visitor', 'khách đến thăm'),
  ('whatever', 'bất cứ điều gì'),
  ('whenever', 'bất cứ khi nào'),
  ('whether', 'liệu có... hay không'),
  ('whole', 'toàn bộ, cả'),
  ('whom', 'người mà (tân ngữ của who)'),
  ('whose', 'của ai, mà ... của người đó'),
  ('within', 'bên trong; trong vòng'),
  ('witness', 'nhân chứng; chứng kiến'),
  ('worth', 'đáng giá'),
  ('yellow', 'màu vàng')
on conflict (word) do update set meaning = excluded.meaning;
