-- ============================================================================
-- MODULE DOC theo thang CEFR — 20 bai (B1, B2)
-- Chay thang file nay la du. An toan chay lai nhieu lan.
-- ============================================================================

-- 1. CHO PHEP CAP DO CEFR
--    Bang lessons dang khoa cung level o 3 gia tri cu nen chen 'B1' se loi.
--    Noi long rang buoc, van giu 3 gia tri cu de cac bai da co khong hong.
alter table public.lessons drop constraint if exists lessons_level_check;
alter table public.lessons add constraint lessons_level_check
  check (level in ('beginner','intermediate','advanced','A1','A2','B1','B2','C1','C2'));

-- 2. CHU THICH CUM TU RIENG CUA TUNG BAI (hover ra nghia)
--    Tu don da duoc tra tu dong tu kho tu vung; cot nay chi danh cho
--    cum tu va thuat ngu ma tu dien khong co.
alter table public.lessons add column if not exists glossary jsonb;

-- 3. XOA BAI CU CUNG ID roi chen lai (de chay lai file nay luon cap nhat)
delete from public.lessons where id in ('b3000000-0000-4000-8000-000000000001', 'b3000000-0000-4000-8000-000000000002', 'b3000000-0000-4000-8000-000000000003', 'b3000000-0000-4000-8000-000000000004', 'b3000000-0000-4000-8000-000000000005', 'b3000000-0000-4000-8000-000000000006', 'b3000000-0000-4000-8000-000000000007', 'b3000000-0000-4000-8000-000000000008', 'b3000000-0000-4000-8000-000000000009', 'b3000000-0000-4000-8000-000000000010', 'b4000000-0000-4000-8000-000000000001', 'b4000000-0000-4000-8000-000000000002', 'b4000000-0000-4000-8000-000000000003', 'b4000000-0000-4000-8000-000000000004', 'b4000000-0000-4000-8000-000000000005', 'b4000000-0000-4000-8000-000000000006', 'b4000000-0000-4000-8000-000000000007', 'b4000000-0000-4000-8000-000000000008', 'b4000000-0000-4000-8000-000000000009', 'b4000000-0000-4000-8000-000000000010');

-- 4. BAI DOC
insert into public.lessons (id, skill, title, description, level, content, glossary, order_index) values
('b3000000-0000-4000-8000-000000000001', 'reading', 'Working from Home', 'Lợi ích và mặt trái của việc làm việc tại nhà', 'B1', 'Ten years ago, most people travelled to an office every morning. Today, millions of people work from home instead. The change happened quickly, and many companies now let their staff choose where they work.

There are clear advantages. Workers save time and money because they do not have to commute. A person who spends an hour on the road each day gains about five hours every week. Many people also say they concentrate better at home, away from noisy offices and long meetings.

However, working from home is not perfect. Some people find it hard to separate work from private life. They open their laptop at seven in the morning and close it at nine at night. Others feel lonely because they rarely meet their colleagues face to face.

Experts suggest a few simple rules. Set fixed working hours and stop when they end. Create a small area that is used only for work. Meet your team in person at least once a month. With these habits, most workers can enjoy the freedom of home working without losing the benefits of an office.', '[{"term": "work from home", "vi": "làm việc tại nhà"}, {"term": "commute", "vi": "đi lại giữa nhà và nơi làm"}, {"term": "face to face", "vi": "gặp trực tiếp"}, {"term": "fixed working hours", "vi": "giờ làm cố định"}]', 301),
('b3000000-0000-4000-8000-000000000002', 'reading', 'Learning a Language as an Adult', 'Vì sao người lớn vẫn học ngoại ngữ tốt', 'B1', 'Many adults believe they are too old to learn a new language. They remember how easily children pick up words and think the chance has passed. Research suggests this belief is only half true.

Children do have one clear advantage: pronunciation. Young learners copy sounds naturally and often speak without a strong accent. Adults usually keep some accent, no matter how long they study.

In other areas, however, adults do better. They already understand how grammar works, so they can learn rules quickly instead of guessing. They can also organise their study, use a dictionary, and connect new words to knowledge they already have. A child needs years of listening; an adult can reach a useful level in a few months of steady work.

The real difficulty is time. Adults are busy, and progress feels slow when you only study twenty minutes a day. But twenty minutes every day is far better than three hours once a week. Regular practice keeps new words alive in the memory.

So age is not the main problem. Habit is.', '[{"term": "pick up", "vi": "tiếp thu, học được (một cách tự nhiên)"}, {"term": "no matter how long", "vi": "dù có bao lâu đi nữa"}, {"term": "steady work", "vi": "làm đều đặn"}, {"term": "keeps new words alive", "vi": "giữ cho từ mới không bị quên"}]', 302),
('b3000000-0000-4000-8000-000000000003', 'reading', 'Street Food Culture', 'Văn hoá ẩm thực đường phố và sức hút của nó', 'B1', 'In many Asian cities, the best food is not found in expensive restaurants. It is sold on the pavement, from small carts and plastic tables. Street food is cheap, fast and, for many people, part of daily life.

A typical seller cooks only one or two dishes. Because they make the same thing hundreds of times a day, they become extremely good at it. Customers return for years, and a good stall can support a family for two generations.

Street food is also social. People sit close together on low stools, share tables with strangers, and eat within minutes. Office workers, students and taxi drivers all queue at the same cart.

There are worries, of course. Hygiene is not always perfect, and some governments have tried to move sellers indoors. Yet many customers judge a stall by simple signs: a long queue, fresh ingredients, and a cook who washes their hands.

For visitors, street food offers something a restaurant cannot: the taste of ordinary life in a city.', '[{"term": "street food", "vi": "đồ ăn đường phố"}, {"term": "low stools", "vi": "ghế nhựa thấp"}, {"term": "two generations", "vi": "hai đời, hai thế hệ"}, {"term": "fresh ingredients", "vi": "nguyên liệu tươi"}]', 303),
('b3000000-0000-4000-8000-000000000004', 'reading', 'Why Sleep Matters', 'Giấc ngủ ảnh hưởng thế nào tới trí nhớ và sức khoẻ', 'B1', 'Most adults need between seven and nine hours of sleep, but many get far less. People often treat sleep as time that could be used for something more useful. Scientists disagree.

During sleep, the brain does important work. It sorts through the day''s events and moves useful information into long-term memory. This is why students who sleep after studying remember more than students who stay awake all night. The body also repairs muscle and produces hormones that control appetite.

Losing sleep has quick effects. After one bad night, people react more slowly and make more mistakes. After several bad nights, they become irritable and find it harder to concentrate. Long-term poor sleep is linked to heart problems and weight gain.

The good news is that habits help. Go to bed and get up at similar times, even at weekends. Keep the bedroom dark and slightly cool. Avoid coffee after the early afternoon, and put the phone in another room.

Sleep is not lost time. It is when the body prepares for tomorrow.', '[{"term": "long-term memory", "vi": "trí nhớ dài hạn"}, {"term": "stay awake", "vi": "thức, không ngủ"}, {"term": "weight gain", "vi": "tăng cân"}, {"term": "slightly cool", "vi": "hơi mát"}]', 304),
('b3000000-0000-4000-8000-000000000005', 'reading', 'Phones and Attention', 'Điện thoại ảnh hưởng tới khả năng tập trung', 'B1', 'The average person checks their phone more than a hundred times a day. Most of these checks last only a few seconds, so they feel harmless. Researchers say the cost is higher than it looks.

The problem is not the time itself but what happens afterwards. When you stop a task to look at a message, your attention does not return immediately. It can take several minutes to reach the same level of concentration again. If this happens twenty times in a morning, most of the morning is spent starting again.

Phones are designed to attract us. Notifications, bright colours and endless lists of new content all encourage one more look. This is not an accident; companies earn money from our attention.

Some simple changes help. Turn off notifications for apps that are not urgent. Keep the phone out of sight while working, not just face down. Choose two or three fixed times a day to check messages.

Nobody needs to give up their phone. The aim is to decide when it speaks to you.', '[{"term": "a few seconds", "vi": "vài giây"}, {"term": "endless lists", "vi": "danh sách bất tận"}, {"term": "out of sight", "vi": "khuất tầm mắt"}, {"term": "face down", "vi": "úp mặt xuống"}]', 305),
('b3000000-0000-4000-8000-000000000006', 'reading', 'Getting Around a Big City', 'Các cách di chuyển trong thành phố lớn', 'B1', 'Every large city faces the same question: how should millions of people move around each day? The answers are different, but the problems are similar.

Cars offer comfort and privacy. Unfortunately, they also take up a great deal of space. A single bus carries as many passengers as forty cars, using a fraction of the road. When too many people drive, everyone moves slowly, including the drivers.

Public transport is cheaper and cleaner, but it only works if it is reliable. People will accept a crowded train if it arrives every five minutes. They will not accept an empty bus that comes once an hour and is often late.

Recently, many cities have returned to an older idea: walking and cycling. Wide pavements and protected bike lanes cost far less than new roads. They also make streets safer and shops busier.

There is no perfect system. The best cities simply give people a real choice, so that driving becomes one option among several rather than the only one.', '[{"term": "public transport", "vi": "giao thông công cộng"}, {"term": "bike lanes", "vi": "làn đường xe đạp"}, {"term": "a fraction of", "vi": "một phần nhỏ của"}, {"term": "real choice", "vi": "lựa chọn thật sự"}]', 306),
('b3000000-0000-4000-8000-000000000007', 'reading', 'Small Habits, Big Savings', 'Thói quen nhỏ giúp tiết kiệm tiền', 'B1', 'People often believe that saving money requires a large salary. In fact, what matters more is the pattern of small daily decisions.

Consider a coffee bought on the way to work. One cup costs very little, but five cups a week for a year add up to a serious amount. The same is true of unused subscriptions, delivery fees and things bought simply because they were on sale.

Financial advisers suggest a simple exercise. For one month, write down every payment, however small. Most people are surprised: the largest problem is rarely the rent or the electricity bill. It is the many small payments nobody remembers making.

Another useful habit is to save first. Instead of saving whatever is left at the end of the month, move a fixed sum into a separate account on payday. Because the money disappears immediately, people adjust their spending without noticing.

None of this is complicated. The difficulty is that small habits feel unimportant, and that is exactly why they are powerful.', '[{"term": "add up to", "vi": "cộng dồn thành"}, {"term": "on sale", "vi": "đang giảm giá"}, {"term": "save first", "vi": "tiết kiệm trước, tiêu sau"}, {"term": "payday", "vi": "ngày lĩnh lương"}]', 307),
('b3000000-0000-4000-8000-000000000008', 'reading', 'The Weather Is Changing', 'Biến đổi thời tiết ảnh hưởng tới đời sống hằng ngày', 'B1', 'Farmers are often the first to notice that the weather is changing. They do not read reports; they simply see that the rain no longer arrives when it used to.

In many countries, the wet season now starts later and ends suddenly. Rice planted at the traditional time may sit in dry soil for weeks. When the rain finally comes, it falls too heavily, and young plants are washed away. A crop that once needed careful timing now needs luck.

Cities feel the change differently. Concrete and metal hold heat, so a hot day in the city can be several degrees warmer than in the countryside nearby. Older people and outdoor workers suffer most.

Governments are responding slowly. Some are building better drainage; others are planting trees along main roads, because shade is cheap and effective.

Ordinary people are adapting too. Farmers plant different varieties, shops open earlier to avoid the afternoon heat, and families keep water stored at home. Life continues, but the old rules no longer work.', '[{"term": "wet season", "vi": "mùa mưa"}, {"term": "washed away", "vi": "bị cuốn trôi"}, {"term": "outdoor workers", "vi": "người lao động ngoài trời"}, {"term": "keep water stored", "vi": "trữ nước"}]', 308),
('b3000000-0000-4000-8000-000000000009', 'reading', 'Making Friends After Thirty', 'Vì sao kết bạn khi trưởng thành lại khó hơn', 'B1', 'At school and university, friendship happens almost by accident. You see the same people every day, you share the same timetable, and there is plenty of free time. After thirty, all three of these conditions usually disappear.

Adults meet fewer new people, and the people they do meet are often busy. A friendly conversation at work may never turn into anything more, simply because nobody has an evening free. Many adults report that they have colleagues they like but no close friends nearby.

Sociologists say that friendship needs three things: repeated contact, a shared activity, and time without a clear purpose. A weekly football game provides all three. A single dinner every six months provides none of them.

This explains why hobbies matter more than they seem to. Joining a class, a running group or a choir is not only about the activity. It creates a reason to see the same faces again and again.

Friendship after thirty rarely happens by accident. It has to be arranged.', '[{"term": "by accident", "vi": "một cách tình cờ"}, {"term": "share the same timetable", "vi": "dùng chung thời khoá biểu"}, {"term": "without a clear purpose", "vi": "không có mục đích rõ ràng"}, {"term": "repeated contact", "vi": "gặp lại nhiều lần"}]', 309),
('b3000000-0000-4000-8000-000000000010', 'reading', 'Reading More Books', 'Cách xây dựng thói quen đọc sách', 'B1', 'Many people say they want to read more but finish only two or three books a year. They rarely lack interest. What they lack is a system.

The first mistake is choosing books that sound impressive rather than books that are enjoyable. A difficult classic left unfinished on a shelf teaches nothing. A simple novel that keeps you turning pages builds the habit, and the habit makes harder books possible later.

The second mistake is waiting for long free periods. Very few adults have two quiet hours. However, almost everyone has ten minutes while waiting, travelling or drinking coffee. Ten minutes a day is roughly fifteen books a year.

A third idea is to allow yourself to stop. Many readers force themselves through a book they dislike and then read nothing for months. Leaving a bad book is not failure; it protects the habit.

Reading is less about discipline than about removing small obstacles. Keep a book where you can reach it, and the rest usually follows.', '[{"term": "turning pages", "vi": "lật hết trang này tới trang khác"}, {"term": "free periods", "vi": "khoảng thời gian rảnh"}, {"term": "force themselves through", "vi": "ép mình đọc cho hết"}, {"term": "small obstacles", "vi": "những trở ngại nhỏ"}]', 310),
('b4000000-0000-4000-8000-000000000001', 'reading', 'The Cost of Convenience', 'Cái giá thật của sự tiện lợi tức thì', 'B2', 'A decade ago, ordering dinner meant phoning a restaurant and waiting. Today an app delivers almost anything within half an hour. Convenience of this kind feels like pure progress, but it comes with costs that are easy to overlook.

The most obvious is financial. Delivery fees, service charges and slightly higher menu prices add perhaps thirty per cent to a meal. Customers accept this because each individual charge looks small, yet over a year the difference is substantial.

Less obvious is the effect on the businesses involved. Restaurants often pay a large commission to the platform, which means a busy kitchen can deliver hundreds of meals and still earn very little. Some owners now treat delivery as advertising rather than profit.

There is also a change in habit. When effort disappears, so does deliberation. People who once decided what to cook on Sunday now decide what to order at eight o''clock, when they are tired and hungry. Studies of household spending suggest that decisions made in that state are rarely the cheapest or the healthiest.

None of this means delivery apps are harmful. For a parent with a sick child or a worker finishing at midnight, they solve a genuine problem. The difficulty arises when an occasional solution quietly becomes a daily default, and nobody remembers choosing it.', '[{"term": "service charges", "vi": "phí dịch vụ"}, {"term": "delivery fees", "vi": "phí giao hàng"}, {"term": "commission", "vi": "hoa hồng, phần trăm chiết khấu"}, {"term": "daily default", "vi": "lựa chọn mặc định hằng ngày"}, {"term": "genuine problem", "vi": "vấn đề có thật"}]', 401),
('b4000000-0000-4000-8000-000000000002', 'reading', 'Why Cities Are Getting Older', 'Dân số già hoá và điều đó thay đổi thành phố ra sao', 'B2', 'For most of the twentieth century, planners designed cities for young families. Schools, playgrounds and wide roads were built on the assumption that the population would keep growing and keep getting younger. In much of the world, that assumption no longer holds.

Birth rates have fallen sharply, while life expectancy has risen. The result is a population in which the fastest growing group is people over sixty-five. In some Asian and European cities, one resident in four will soon belong to that group.

The consequences reach far beyond healthcare. A city built for drivers becomes difficult for those who no longer drive. Bus stops without seats, pavements with high kerbs and crossings timed for fast walkers all create small daily obstacles. Individually they seem trivial; together they can keep an older person at home.

Some cities have responded intelligently, and often cheaply. Lowering a kerb, adding a bench every two hundred metres or extending the crossing time by four seconds costs very little compared with a new road. Interestingly, these changes benefit almost everyone: parents with pushchairs, injured workers, and anyone carrying heavy shopping.

This is the useful lesson. Designing for the oldest residents is not charity, and it is not a cost imposed by one group on another. A city that an eighty-year-old can cross comfortably tends to be a better city for all of its inhabitants.', '[{"term": "birth rates", "vi": "tỉ lệ sinh"}, {"term": "life expectancy", "vi": "tuổi thọ trung bình"}, {"term": "high kerbs", "vi": "bó vỉa cao"}, {"term": "pushchairs", "vi": "xe đẩy em bé"}, {"term": "no longer holds", "vi": "không còn đúng nữa"}]', 402),
('b4000000-0000-4000-8000-000000000003', 'reading', 'The Problem with Productivity Advice', 'Vì sao lời khuyên tăng năng suất thường không hiệu quả', 'B2', 'Bookshops contain hundreds of guides promising greater productivity. Most offer sensible techniques: plan tomorrow tonight, work in focused blocks, deal with email twice a day. Readers try them enthusiastically, and within a fortnight almost everyone has returned to their old routine. It is worth asking why.

One reason is that such advice usually treats the reader as an isolated individual. In reality, most work is interdependent. A person who decides to answer email only twice a day may be admirably focused, but if their colleagues expect a reply within the hour, the plan collapses under social pressure rather than personal weakness.

A second reason is that productivity advice tends to assume the problem is speed. Often the real problem is direction. Completing forty small tasks efficiently is of little value if none of them matters. Yet measuring effort is easy while measuring importance is uncomfortable, so we quietly prefer the former.

There is also a curious side effect. The pursuit of efficiency can create more work. A person who becomes visibly capable is given additional responsibilities, and the time saved disappears.

The most useful advice, therefore, is unfashionably dull: decide what you will not do, tell other people about it, and accept that some things will be done badly on purpose. This is harder than buying another notebook, which may explain why it sells fewer books.', '[{"term": "focused blocks", "vi": "khoảng thời gian tập trung liền mạch"}, {"term": "social pressure", "vi": "áp lực từ người xung quanh"}, {"term": "side effect", "vi": "tác dụng phụ"}, {"term": "on purpose", "vi": "một cách có chủ đích"}]', 403),
('b4000000-0000-4000-8000-000000000004', 'reading', 'Second-Hand Fashion', 'Thị trường quần áo cũ và giới hạn của nó', 'B2', 'Not long ago, buying used clothing carried a certain stigma. Today second-hand shops and resale apps are among the fastest growing parts of the fashion industry, and young shoppers in particular treat a vintage jacket as a mark of taste rather than of poverty.

Several forces explain the shift. Clothing has become remarkably cheap, which means the market is flooded with garments that are barely worn. At the same time, awareness of environmental damage has grown: producing a single cotton shirt requires thousands of litres of water. Buying an existing shirt avoids that cost entirely.

The economics are attractive too. A shopper can acquire better-made clothing for less money, and a seller can recover part of what they spent. Platforms take a commission and everyone appears to gain.

Yet the picture is more complicated than it seems. Cheap resale can encourage rather than reduce consumption. If a jacket can always be sold on, buying it feels temporary and therefore harmless, and some shoppers simply buy more. Researchers describe this as a rebound effect: an efficiency improvement that increases total use.

The honest conclusion is modest. Second-hand shopping is clearly better than buying new, but it does not solve the underlying problem, which is the sheer volume of clothing produced each year. Reducing that volume requires slower purchasing habits, not merely a cleverer way of passing garments along.', '[{"term": "second-hand", "vi": "đồ đã qua sử dụng"}, {"term": "resale apps", "vi": "ứng dụng bán lại"}, {"term": "rebound effect", "vi": "hiệu ứng bật lại — cải thiện hiệu quả lại làm tăng tiêu dùng"}, {"term": "barely worn", "vi": "gần như chưa mặc"}, {"term": "passing garments along", "vi": "chuyền tay quần áo"}]', 404),
('b4000000-0000-4000-8000-000000000005', 'reading', 'How Rumours Spread Online', 'Cơ chế khiến tin sai lan nhanh hơn tin đúng', 'B2', 'Researchers who study social networks have reached an uncomfortable conclusion: false stories often travel faster and further than accurate ones. The explanation has less to do with technology than with human attention.

A true account of an event is usually complicated. It contains qualifications, uncertain details and dull sections. A rumour has no such obligations. It can be shaped into the most surprising version of events, and surprise is precisely what makes people share. In one large study, false claims reached audiences roughly six times faster than corrections did.

Speed also matters because of order. Whichever version arrives first becomes the reference point, and later information is judged against it. A correction published a day later does not simply replace the original; it competes with a memory that already feels familiar. Familiarity is easily mistaken for truth.

Attempts to fix the problem have produced mixed results. Removing false posts can create the impression that something is being hidden. Labelling them is more effective, though only if the label appears before the reader has formed an opinion.

What seems to help most is unglamorous: slowing the moment of sharing. Platforms that ask users whether they have read an article before posting it see measurably fewer shares of misleading material. The intervention adds two seconds, and two seconds is apparently enough for judgement to catch up with impulse.', '[{"term": "reference point", "vi": "điểm tham chiếu"}, {"term": "mixed results", "vi": "kết quả không đồng nhất"}, {"term": "formed an opinion", "vi": "đã hình thành quan điểm"}, {"term": "misleading material", "vi": "nội dung gây hiểu lầm"}]', 405),
('b4000000-0000-4000-8000-000000000006', 'reading', 'The Return of the Night Train', 'Tàu đêm trở lại và ý nghĩa của du lịch chậm', 'B2', 'In the 1990s, night trains across Europe were quietly withdrawn. Budget airlines could cross the continent in two hours for the price of a taxi ride, and sleeping carriages seemed like a charming relic. Three decades later, several countries are putting them back.

The immediate reason is environmental. A train journey produces a small fraction of the emissions of the equivalent flight, and governments under pressure to reduce transport emissions find rail an obvious target for investment. Some have gone further and taxed short domestic flights.

But the revival is not only about carbon. Travellers have begun to notice something that the airline model conceals: the true length of a flight. Two hours in the air becomes six or seven once airports, security queues and transfers are counted. A night train, by contrast, uses hours that would have been spent asleep anyway, and delivers passengers to a city centre rather than a distant runway.

Difficulties remain. Sleeping carriages are expensive to build and can carry fewer passengers than a seated coach, so tickets are rarely cheap. Cross-border services require agreement between several rail companies, which is slow work.

Even so, the trend is instructive. It suggests that speed measured door to door, rather than in the air, may change how we judge a journey — and that the fastest option is not always the one that saves the most time.', '[{"term": "night trains", "vi": "tàu đêm"}, {"term": "sleeping carriages", "vi": "toa giường nằm"}, {"term": "charming relic", "vi": "tàn dư đáng yêu của quá khứ"}, {"term": "door to door", "vi": "tính từ cửa nhà tới điểm đến"}, {"term": "cross-border", "vi": "xuyên biên giới"}]', 406),
('b4000000-0000-4000-8000-000000000007', 'reading', 'Who Owns Your Data?', 'Dữ liệu cá nhân và câu hỏi về quyền sở hữu', 'B2', 'When you install a free application, you agree to a document you almost certainly have not read. Somewhere inside it, you grant permission for information about your behaviour to be collected, stored and shared. The arrangement is legal, widely accepted, and strange when examined closely.

Part of the strangeness is that the value of personal data is invisible at the moment of exchange. A single record of one person''s shopping is nearly worthless. Millions of such records, combined, can predict behaviour accurately enough to be sold to advertisers, insurers and political campaigns. The individual gives away something cheap; the collector assembles something valuable.

Defenders of the system argue that users receive a fair return in the form of free services, and that nobody is forced to participate. Critics reply that consent given without understanding is not really consent, particularly when the alternative is exclusion from ordinary social and professional life.

Several governments have introduced rules requiring clearer notices and a genuine option to refuse. The effect so far has been limited. Faced with a choice between reading twenty pages and clicking ''accept'', most people click.

Perhaps the more productive question is not who owns data but what may be done with it. Ownership is difficult to define for something that can be copied endlessly. Restricting particular uses — refusing insurance, setting prices individually — is narrower, but it may be enforceable.', '[{"term": "free application", "vi": "ứng dụng miễn phí"}, {"term": "political campaigns", "vi": "chiến dịch tranh cử"}, {"term": "fair return", "vi": "sự đền đáp công bằng"}, {"term": "ordinary social and professional life", "vi": "đời sống xã hội và nghề nghiệp bình thường"}]', 407),
('b4000000-0000-4000-8000-000000000008', 'reading', 'Learning from Failure', 'Vì sao ta học sai bài học từ thành công', 'B2', 'Business writing is full of advice drawn from successful companies. Study what the winners did, the argument goes, and repeat it. The method sounds reasonable and is quietly misleading.

The difficulty is that we only examine the survivors. For every firm that succeeded by ignoring market research, there may be fifty that did the same and disappeared without writing a book about it. Because the failures are invisible, the behaviour looks like the cause of success when it may simply have been a risk that happened to pay off. Statisticians call this survivorship bias.

A famous wartime example makes the point. Engineers examining returning aircraft found most damage on the wings and proposed adding armour there. A mathematician pointed out the flaw: these were the planes that came back. The undamaged areas on survivors were precisely the areas where damage was fatal. Armour was needed where no returning plane had been hit.

The lesson for ordinary decisions is practical rather than gloomy. Before copying a strategy, ask what happened to those who tried it and failed. Ask whether the outcome could reasonably be explained by luck. Notice when a story is told backwards, starting from the result.

Failure, unfortunately, is rarely documented as carefully as success. That imbalance is not neutral: it shapes what an entire generation of managers believes to be true.', '[{"term": "survivorship bias", "vi": "thiên kiến kẻ sống sót — chỉ nhìn vào những trường hợp thành công"}, {"term": "market research", "vi": "nghiên cứu thị trường"}, {"term": "pay off", "vi": "đem lại kết quả tốt"}, {"term": "told backwards", "vi": "kể ngược từ kết quả trở lại"}]', 408),
('b4000000-0000-4000-8000-000000000009', 'reading', 'The Quiet Decline of Cash', 'Tiền mặt biến mất và ai bị bỏ lại', 'B2', 'In a growing number of cities, a person could spend a week without touching a banknote. Cards, phones and watches handle everything from a bus fare to a bowl of noodles. Retailers welcome the change, since counting cash is slow and carrying it is risky.

The advantages are real. Electronic payment leaves a record, which reduces certain kinds of theft and makes tax collection easier. Small traders who once dealt only in coins can now accept payment from a tourist with no local currency at all.

The losses are less visible, and they fall on particular groups. Elderly people who never learned to use a smartphone, workers paid informally, and anyone whose bank account has been closed all find that ordinary transactions become complicated. Cash requires no permission, no battery and no signal. When a payment system fails during a storm or a power cut, that quality suddenly seems less old-fashioned.

There is also a question of privacy. Every electronic payment reveals where a person was and what they bought. Most people accept this without much thought, but the record does not disappear, and its uses may change.

A sensible compromise is emerging in several countries: businesses may encourage digital payment but must still accept cash. This is not nostalgia. It is a recognition that a system with only one method has no way to fail gracefully.', '[{"term": "bus fare", "vi": "tiền vé xe buýt"}, {"term": "informally", "vi": "không chính thức"}, {"term": "power cut", "vi": "mất điện"}, {"term": "fail gracefully", "vi": "hỏng một cách êm, vẫn còn phương án thay thế"}]', 409),
('b4000000-0000-4000-8000-000000000010', 'reading', 'Why We Misjudge Risk', 'Não người đánh giá rủi ro lệch lạc như thế nào', 'B2', 'People are remarkably bad at estimating danger. Many are nervous about flying yet think nothing of crossing a busy road, although the road is far more likely to harm them. This is not stupidity; it is the predictable result of how attention works.

Risk feels larger when an example comes easily to mind. Air accidents are rare but heavily reported, complete with photographs and names, so they are easy to recall. Road deaths are common but reported briefly and locally, so they leave no vivid impression. Psychologists call this the availability heuristic: we judge frequency by how readily an example appears.

Control matters too. We accept greater danger when we feel we are in charge. A driver believes their own skill protects them, while a passenger on a plane can do nothing. Statistically the driver is in far more danger, but the feeling of control is reassuring rather than accurate.

Finally, we respond to how a risk is described. Told that a treatment saves ninety per cent of patients, most people approve. Told that it loses ten per cent, the same people hesitate, although the two statements are identical.

Knowing about these effects does not remove them. What it does allow is a useful habit: when a risk feels obvious, ask whether the feeling comes from evidence or simply from a memorable story.', '[{"term": "availability heuristic", "vi": "phép suy đoán theo mức dễ nhớ"}, {"term": "in charge", "vi": "làm chủ tình hình"}, {"term": "memorable story", "vi": "câu chuyện dễ nhớ"}, {"term": "think nothing of", "vi": "chẳng bận tâm gì tới"}]', 410);

-- 5. CAU HOI
insert into public.exercises (lesson_id, type, prompt, options, accepted_answers, explanation, order_index) values
('b3000000-0000-4000-8000-000000000001', 'multiple_choice', 'How much time can a person save each week by not commuting, according to the passage?', '["About one hour", "About three hours", "About five hours", "About ten hours"]', array['About five hours'], 'Đoạn 2: người mất một tiếng đi lại mỗi ngày sẽ tiết kiệm được khoảng năm tiếng mỗi tuần.', 1),
('b3000000-0000-4000-8000-000000000001', 'true_false', 'The passage says that all companies now allow their staff to work from home.', null, array['false'], 'Bài viết nói ''many companies'' (nhiều công ty), không phải tất cả.', 2),
('b3000000-0000-4000-8000-000000000001', 'multiple_choice', 'What problem with time do some home workers have?', '["They start work too late", "They work far too many hours", "They forget their meetings", "They travel too much"]', array['They work far too many hours'], 'Đoạn 3: họ mở máy lúc bảy giờ sáng và đóng lúc chín giờ tối.', 3),
('b3000000-0000-4000-8000-000000000001', 'true_false', 'Experts advise meeting your colleagues in person from time to time.', null, array['true'], 'Đoạn 4: ''Meet your team in person at least once a month.''', 4),
('b3000000-0000-4000-8000-000000000001', 'multiple_choice', 'In this passage, the word ''commute'' means', '["to work at home", "to travel between home and work", "to take a long holiday", "to change jobs often"]', array['to travel between home and work'], '''Commute'' nghĩa là đi lại giữa nhà và nơi làm việc.', 5),
('b3000000-0000-4000-8000-000000000002', 'multiple_choice', 'What advantage do children have over adults?', '["A larger vocabulary", "Better pronunciation", "More free time", "A better memory for rules"]', array['Better pronunciation'], 'Đoạn 2: trẻ em bắt chước âm thanh tự nhiên và thường nói không bị nặng giọng.', 1),
('b3000000-0000-4000-8000-000000000002', 'true_false', 'According to the passage, adults understand grammar rules more easily than children.', null, array['true'], 'Đoạn 3: người lớn đã hiểu ngữ pháp hoạt động thế nào nên học quy tắc rất nhanh.', 2),
('b3000000-0000-4000-8000-000000000002', 'multiple_choice', 'Which study habit does the writer recommend?', '["Three hours once a week", "Twenty minutes every day", "One full day each month", "Only studying before a test"]', array['Twenty minutes every day'], 'Đoạn 4: hai mươi phút mỗi ngày tốt hơn nhiều so với ba tiếng một tuần một lần.', 3),
('b3000000-0000-4000-8000-000000000002', 'true_false', 'The writer thinks age is the main reason adults fail to learn a language.', null, array['false'], 'Câu cuối: ''So age is not the main problem. Habit is.''', 4),
('b3000000-0000-4000-8000-000000000002', 'multiple_choice', 'What is the main idea of the passage?', '["Children always learn faster than adults", "Adults can learn well if they practise regularly", "Pronunciation is the most important skill", "Grammar should be learned last"]', array['Adults can learn well if they practise regularly'], 'Toàn bài lập luận rằng người lớn học tốt nếu luyện tập đều đặn.', 5),
('b3000000-0000-4000-8000-000000000003', 'multiple_choice', 'Why do street food sellers usually cook only one or two dishes?', '["They cannot afford more ingredients", "Repeating the same dish makes them very skilled", "The government does not allow more", "Customers only order one dish"]', array['Repeating the same dish makes them very skilled'], 'Đoạn 2: vì làm cùng một món hàng trăm lần mỗi ngày nên họ trở nên cực kỳ giỏi.', 1),
('b3000000-0000-4000-8000-000000000003', 'true_false', 'According to the passage, street food stalls are used only by poor people.', null, array['false'], 'Đoạn 3: nhân viên văn phòng, sinh viên và tài xế taxi đều xếp hàng ở cùng một xe đẩy.', 2),
('b3000000-0000-4000-8000-000000000003', 'multiple_choice', 'What concern about street food is mentioned?', '["The price is rising quickly", "Hygiene is not always good", "The food is too spicy", "There are too few sellers"]', array['Hygiene is not always good'], 'Đoạn 4: vệ sinh không phải lúc nào cũng hoàn hảo.', 3),
('b3000000-0000-4000-8000-000000000003', 'true_false', 'Some customers use the length of the queue to judge a stall.', null, array['true'], 'Đoạn 4: khách đánh giá quán qua hàng dài, nguyên liệu tươi và người nấu rửa tay.', 4),
('b3000000-0000-4000-8000-000000000003', 'multiple_choice', 'What does the writer say street food gives visitors?', '["The cheapest possible meal", "A taste of ordinary life in a city", "A quiet place to rest", "A chance to learn cooking"]', array['A taste of ordinary life in a city'], 'Câu cuối: món ăn đường phố cho du khách hương vị của đời sống thường ngày.', 5),
('b3000000-0000-4000-8000-000000000004', 'multiple_choice', 'How many hours of sleep do most adults need?', '["Four to five hours", "Five to six hours", "Seven to nine hours", "Ten to twelve hours"]', array['Seven to nine hours'], 'Câu đầu tiên: hầu hết người lớn cần từ bảy đến chín tiếng.', 1),
('b3000000-0000-4000-8000-000000000004', 'true_false', 'The passage says students who sleep after studying remember more.', null, array['true'], 'Đoạn 2: sinh viên ngủ sau khi học nhớ nhiều hơn người thức trắng đêm.', 2),
('b3000000-0000-4000-8000-000000000004', 'multiple_choice', 'What happens after only one night of bad sleep?', '["People gain weight", "People react more slowly", "People develop heart problems", "People stop feeling hungry"]', array['People react more slowly'], 'Đoạn 3: sau một đêm ngủ kém, người ta phản ứng chậm hơn và mắc nhiều lỗi hơn.', 3),
('b3000000-0000-4000-8000-000000000004', 'true_false', 'The writer advises keeping the bedroom warm and bright.', null, array['false'], 'Đoạn 4: khuyên giữ phòng ngủ tối và hơi mát.', 4),
('b3000000-0000-4000-8000-000000000004', 'multiple_choice', 'What is the writer''s main message?', '["Sleep is wasted time", "Sleep is necessary for the body and mind", "Only students need enough sleep", "Coffee helps you sleep better"]', array['Sleep is necessary for the body and mind'], 'Câu cuối: ngủ không phải thời gian lãng phí, đó là lúc cơ thể chuẩn bị cho ngày mai.', 5),
('b3000000-0000-4000-8000-000000000005', 'multiple_choice', 'According to the passage, why is checking a phone costly?', '["It uses a lot of battery", "Attention takes minutes to return", "It is expensive to use data", "It damages the eyes"]', array['Attention takes minutes to return'], 'Đoạn 2: sau khi dừng việc để xem tin nhắn, phải mất vài phút mới tập trung lại được.', 1),
('b3000000-0000-4000-8000-000000000005', 'true_false', 'The passage says phone companies design apps to attract our attention on purpose.', null, array['true'], 'Đoạn 3: ''This is not an accident; companies earn money from our attention.''', 2),
('b3000000-0000-4000-8000-000000000005', 'multiple_choice', 'What does the writer suggest doing with the phone while working?', '["Put it face down on the desk", "Keep it out of sight", "Give it to a colleague", "Turn it off completely"]', array['Keep it out of sight'], 'Đoạn 4: để điện thoại khuất tầm mắt, không chỉ úp mặt xuống.', 3),
('b3000000-0000-4000-8000-000000000005', 'true_false', 'The writer thinks people should stop using phones completely.', null, array['false'], 'Câu cuối: không ai cần bỏ điện thoại, mục tiêu là tự quyết định khi nào dùng.', 4),
('b3000000-0000-4000-8000-000000000005', 'multiple_choice', 'In the passage, ''notifications'' are', '["long articles", "alerts that tell you about something new", "phone bills", "photographs"]', array['alerts that tell you about something new'], '''Notification'' là thông báo báo cho bạn biết có gì đó mới.', 5),
('b3000000-0000-4000-8000-000000000006', 'multiple_choice', 'How many cars does one bus replace, according to the passage?', '["About ten", "About twenty", "About forty", "About one hundred"]', array['About forty'], 'Đoạn 2: một chiếc xe buýt chở được số khách bằng bốn mươi ô tô.', 1),
('b3000000-0000-4000-8000-000000000006', 'true_false', 'The passage says public transport works only if it is reliable.', null, array['true'], 'Đoạn 3: giao thông công cộng rẻ và sạch hơn nhưng chỉ hiệu quả nếu đáng tin cậy.', 2),
('b3000000-0000-4000-8000-000000000006', 'multiple_choice', 'Why do some cities support walking and cycling?', '["They are traditional", "They cost far less than new roads", "They are faster than trains", "They need no planning"]', array['They cost far less than new roads'], 'Đoạn 4: vỉa hè rộng và làn xe đạp có rào chắn rẻ hơn nhiều so với làm đường mới.', 3),
('b3000000-0000-4000-8000-000000000006', 'true_false', 'According to the writer, there is one perfect transport system for every city.', null, array['false'], 'Đoạn cuối: ''There is no perfect system.''', 4),
('b3000000-0000-4000-8000-000000000006', 'multiple_choice', 'What does the writer say the best cities do?', '["Ban all private cars", "Give people a real choice", "Build only new roads", "Make transport free"]', array['Give people a real choice'], 'Câu cuối: thành phố tốt nhất cho người dân lựa chọn thật sự.', 5),
('b3000000-0000-4000-8000-000000000007', 'multiple_choice', 'What does the writer say matters more than a large salary?', '["Living in a cheap city", "The pattern of small daily decisions", "Having a second job", "Knowing about investment"]', array['The pattern of small daily decisions'], 'Đoạn 1: điều quan trọng hơn là thói quen chi tiêu nhỏ hằng ngày.', 1),
('b3000000-0000-4000-8000-000000000007', 'true_false', 'According to the passage, most people''s biggest money problem is rent.', null, array['false'], 'Đoạn 3: vấn đề lớn nhất hiếm khi là tiền thuê nhà hay tiền điện.', 2),
('b3000000-0000-4000-8000-000000000007', 'multiple_choice', 'What exercise do financial advisers suggest?', '["Stop buying coffee for a year", "Write down every payment for a month", "Open three bank accounts", "Ask for a higher salary"]', array['Write down every payment for a month'], 'Đoạn 3: ghi lại mọi khoản chi trong một tháng, dù nhỏ đến đâu.', 3),
('b3000000-0000-4000-8000-000000000007', 'true_false', 'The writer advises moving money into savings at the start of the month, on payday.', null, array['true'], 'Đoạn 4: chuyển một khoản cố định sang tài khoản riêng ngay ngày nhận lương.', 4),
('b3000000-0000-4000-8000-000000000007', 'multiple_choice', 'Why are small habits powerful, according to the writer?', '["Because they cost a lot", "Because they feel unimportant", "Because banks reward them", "Because they are difficult"]', array['Because they feel unimportant'], 'Câu cuối: thói quen nhỏ có vẻ không quan trọng, và chính vì thế chúng mạnh.', 5),
('b3000000-0000-4000-8000-000000000008', 'multiple_choice', 'Why are farmers often the first to notice the change?', '["They read scientific reports", "They see that rain no longer comes as before", "They travel a lot", "They speak to the government"]', array['They see that rain no longer comes as before'], 'Đoạn 1: họ không đọc báo cáo, họ chỉ thấy mưa không còn đến đúng như trước.', 1),
('b3000000-0000-4000-8000-000000000008', 'true_false', 'The passage says cities can be hotter than the countryside nearby.', null, array['true'], 'Đoạn 3: bê tông và kim loại giữ nhiệt nên thành phố nóng hơn vùng quê vài độ.', 2),
('b3000000-0000-4000-8000-000000000008', 'multiple_choice', 'Why are some governments planting trees along roads?', '["Trees are beautiful", "Shade is cheap and effective", "Trees stop the rain", "People asked for fruit"]', array['Shade is cheap and effective'], 'Đoạn 4: trồng cây vì bóng mát vừa rẻ vừa hiệu quả.', 3),
('b3000000-0000-4000-8000-000000000008', 'true_false', 'According to the passage, ordinary people are doing nothing to adapt.', null, array['false'], 'Đoạn cuối: nông dân đổi giống, cửa hàng mở sớm hơn, các gia đình trữ nước.', 4),
('b3000000-0000-4000-8000-000000000008', 'multiple_choice', 'What does the writer mean by ''the old rules no longer work''?', '["Laws have been changed", "Traditional timing and habits are no longer reliable", "Schools teach differently", "Farming has stopped completely"]', array['Traditional timing and habits are no longer reliable'], 'Ý là cách làm và thời điểm truyền thống giờ không còn đúng nữa.', 5),
('b3000000-0000-4000-8000-000000000009', 'multiple_choice', 'Which three conditions make friendship easy at school, according to the passage?', '["Money, space and freedom", "Seeing the same people, a shared timetable and free time", "Sport, music and study", "Family, teachers and exams"]', array['Seeing the same people, a shared timetable and free time'], 'Đoạn 1: gặp cùng những người mỗi ngày, chung thời khoá biểu, và nhiều thời gian rảnh.', 1),
('b3000000-0000-4000-8000-000000000009', 'true_false', 'The passage says many adults have colleagues they like but no close friends nearby.', null, array['true'], 'Đoạn 2 nêu đúng điều này.', 2),
('b3000000-0000-4000-8000-000000000009', 'multiple_choice', 'What do sociologists say friendship needs?', '["Money and free time", "Repeated contact, a shared activity and unplanned time", "A large family", "Living in the same street"]', array['Repeated contact, a shared activity and unplanned time'], 'Đoạn 3 liệt kê đúng ba yếu tố này.', 3),
('b3000000-0000-4000-8000-000000000009', 'true_false', 'According to the writer, a dinner every six months is enough to build a friendship.', null, array['false'], 'Đoạn 3: bữa tối sáu tháng một lần không đáp ứng yếu tố nào cả.', 4),
('b3000000-0000-4000-8000-000000000009', 'multiple_choice', 'Why does the writer say hobbies matter?', '["They are relaxing", "They create a reason to see the same people repeatedly", "They are cheap", "They improve health"]', array['They create a reason to see the same people repeatedly'], 'Đoạn 4: tham gia lớp học hay nhóm chạy tạo lý do gặp lại cùng những người đó.', 5),
('b3000000-0000-4000-8000-000000000010', 'multiple_choice', 'What does the writer say most people lack?', '["Interest in reading", "A system", "Money for books", "Good eyesight"]', array['A system'], 'Đoạn 1: họ hiếm khi thiếu hứng thú, thứ họ thiếu là một cách làm.', 1),
('b3000000-0000-4000-8000-000000000010', 'true_false', 'The writer recommends starting with difficult classic books.', null, array['false'], 'Đoạn 2: nên chọn sách dễ đọc và hấp dẫn trước, sách khó để sau.', 2),
('b3000000-0000-4000-8000-000000000010', 'multiple_choice', 'How many books a year can ten minutes of daily reading produce?', '["About three", "About eight", "About fifteen", "About thirty"]', array['About fifteen'], 'Đoạn 3: mười phút mỗi ngày tương đương khoảng mười lăm cuốn một năm.', 3),
('b3000000-0000-4000-8000-000000000010', 'true_false', 'According to the passage, giving up a book you dislike protects the reading habit.', null, array['true'], 'Đoạn 4: bỏ dở một cuốn sách dở không phải thất bại, nó bảo vệ thói quen đọc.', 4),
('b3000000-0000-4000-8000-000000000010', 'multiple_choice', 'What is the writer''s main advice?', '["Read only classics", "Remove small obstacles to reading", "Read for two hours a day", "Buy more books"]', array['Remove small obstacles to reading'], 'Câu cuối: đọc sách ít phụ thuộc kỷ luật mà chủ yếu là dẹp bỏ những trở ngại nhỏ.', 5),
('b4000000-0000-4000-8000-000000000001', 'multiple_choice', 'According to the passage, why do customers accept delivery charges?', '["The charges are refunded later", "Each individual charge seems small", "Restaurants explain them clearly", "The food is cheaper than in restaurants"]', array['Each individual charge seems small'], 'Đoạn 2: khách chấp nhận vì từng khoản phí trông nhỏ, nhưng cộng cả năm thì đáng kể.', 1),
('b4000000-0000-4000-8000-000000000001', 'multiple_choice', 'Why do some restaurant owners treat delivery as advertising?', '["It reaches customers abroad", "They earn very little profit from it", "The platform pays them to advertise", "It replaces their signboards"]', array['They earn very little profit from it'], 'Đoạn 3: hoa hồng cho nền tảng lớn nên bán hàng trăm suất vẫn lãi rất ít.', 2),
('b4000000-0000-4000-8000-000000000001', 'true_false', 'The writer claims that decisions made when tired and hungry tend to be less healthy.', null, array['true'], 'Đoạn 4: nghiên cứu chi tiêu cho thấy quyết định lúc mệt và đói ít khi rẻ hoặc lành mạnh.', 3),
('b4000000-0000-4000-8000-000000000001', 'true_false', 'The writer concludes that delivery apps are harmful and should be avoided.', null, array['false'], 'Đoạn cuối nói rõ ''None of this means delivery apps are harmful''.', 4),
('b4000000-0000-4000-8000-000000000001', 'multiple_choice', 'What is the writer''s main concern in the final paragraph?', '["That apps are too expensive for parents", "That an occasional choice becomes an unnoticed habit", "That restaurants will close down", "That delivery drivers are underpaid"]', array['That an occasional choice becomes an unnoticed habit'], 'Đoạn cuối: vấn đề là giải pháp thi thoảng lặng lẽ trở thành lựa chọn mặc định hằng ngày.', 5),
('b4000000-0000-4000-8000-000000000002', 'multiple_choice', 'What assumption did twentieth-century planners make?', '["That cars would disappear", "That the population would keep growing younger", "That birth rates would fall", "That cities would stop expanding"]', array['That the population would keep growing younger'], 'Đoạn 1: họ giả định dân số sẽ tiếp tục tăng và trẻ hơn.', 1),
('b4000000-0000-4000-8000-000000000002', 'true_false', 'The passage says the fastest growing age group is people over sixty-five.', null, array['true'], 'Đoạn 2 nêu đúng điều này.', 2),
('b4000000-0000-4000-8000-000000000002', 'multiple_choice', 'Why does the writer describe the obstacles as ''trivial'' individually?', '["They are easy to remove", "Each one alone seems unimportant, but together they matter", "Older people do not notice them", "They only affect drivers"]', array['Each one alone seems unimportant, but together they matter'], 'Đoạn 3: từng cái riêng lẻ trông không đáng kể, nhưng cộng lại có thể giữ người già ở nhà.', 3),
('b4000000-0000-4000-8000-000000000002', 'multiple_choice', 'According to the passage, who else benefits from these changes?', '["Only elderly residents", "Parents with pushchairs and people carrying shopping", "City planners", "Bus companies"]', array['Parents with pushchairs and people carrying shopping'], 'Đoạn 4: những thay đổi đó có lợi cho gần như tất cả mọi người.', 4),
('b4000000-0000-4000-8000-000000000002', 'true_false', 'The writer presents designing for older residents as an act of charity.', null, array['false'], 'Đoạn cuối: ''Designing for the oldest residents is not charity''.', 5),
('b4000000-0000-4000-8000-000000000003', 'multiple_choice', 'Why does the writer say email plans often collapse?', '["The advice is technically wrong", "Colleagues expect faster replies", "Email systems are unreliable", "People forget the technique"]', array['Colleagues expect faster replies'], 'Đoạn 2: kế hoạch sụp đổ vì áp lực từ đồng nghiệp, không phải vì thiếu ý chí.', 1),
('b4000000-0000-4000-8000-000000000003', 'multiple_choice', 'What does the writer say is often the real problem?', '["Speed of working", "Direction, not speed", "Lack of technology", "Too little sleep"]', array['Direction, not speed'], 'Đoạn 3: vấn đề thật thường là hướng đi, không phải tốc độ.', 2),
('b4000000-0000-4000-8000-000000000003', 'true_false', 'According to the passage, we prefer measuring effort because it is easier than measuring importance.', null, array['true'], 'Đoạn 3: đo nỗ lực thì dễ, đo tầm quan trọng thì khó chịu, nên ta ngầm chọn cái dễ.', 3),
('b4000000-0000-4000-8000-000000000003', 'multiple_choice', 'What ''curious side effect'' does the writer mention?', '["Efficient people are given more work", "Efficient people become unpopular", "People sleep less", "Books become more expensive"]', array['Efficient people are given more work'], 'Đoạn 4: người tỏ ra làm được việc sẽ bị giao thêm trách nhiệm, thời gian tiết kiệm bị mất.', 4),
('b4000000-0000-4000-8000-000000000003', 'multiple_choice', 'What tone does the writer take towards productivity books?', '["Enthusiastic", "Gently sceptical", "Angry", "Completely neutral"]', array['Gently sceptical'], 'Giọng điệu hoài nghi nhẹ nhàng, thấy rõ ở câu cuối về việc ''bán được ít sách hơn''.', 5),
('b4000000-0000-4000-8000-000000000004', 'multiple_choice', 'How has attitude to used clothing changed, according to the passage?', '["It is now seen as a sign of taste", "It is still seen as a sign of poverty", "It is illegal in some countries", "It is only popular with older shoppers"]', array['It is now seen as a sign of taste'], 'Đoạn 1: người mua trẻ coi áo khoác vintage là dấu hiệu của gu thẩm mỹ.', 1),
('b4000000-0000-4000-8000-000000000004', 'true_false', 'The passage states that producing one cotton shirt uses thousands of litres of water.', null, array['true'], 'Đoạn 2 nêu đúng con số này.', 2),
('b4000000-0000-4000-8000-000000000004', 'multiple_choice', 'What is the ''rebound effect'' described in the passage?', '["Prices rising after a sale", "An efficiency gain that increases total consumption", "Clothes returning to the shop", "Shoppers regretting purchases"]', array['An efficiency gain that increases total consumption'], 'Đoạn 4: cải thiện hiệu quả lại làm tăng tổng mức tiêu dùng.', 3),
('b4000000-0000-4000-8000-000000000004', 'true_false', 'The writer believes second-hand shopping solves the main problem of the fashion industry.', null, array['false'], 'Đoạn cuối: nó tốt hơn mua mới nhưng không giải quyết vấn đề gốc là khối lượng sản xuất.', 4),
('b4000000-0000-4000-8000-000000000004', 'multiple_choice', 'What does the writer say is genuinely needed?', '["More resale platforms", "Slower purchasing habits", "Cheaper cotton", "Stricter shop rules"]', array['Slower purchasing habits'], 'Câu cuối: cần thói quen mua chậm lại, không chỉ cách chuyền tay quần áo thông minh hơn.', 5),
('b4000000-0000-4000-8000-000000000005', 'multiple_choice', 'Why do rumours spread more easily than accurate accounts?', '["They are written more clearly", "They can be made surprising", "They come from official sources", "They are shorter by law"]', array['They can be made surprising'], 'Đoạn 2: tin sai có thể được nhào thành phiên bản gây bất ngờ nhất, và bất ngờ khiến người ta chia sẻ.', 1),
('b4000000-0000-4000-8000-000000000005', 'multiple_choice', 'Why does the order of arrival matter?', '["The first version becomes the reference point", "Later posts are deleted", "Readers only read one article", "Corrections are always wrong"]', array['The first version becomes the reference point'], 'Đoạn 3: phiên bản đến trước thành điểm tham chiếu, thông tin sau bị đánh giá dựa trên nó.', 2),
('b4000000-0000-4000-8000-000000000005', 'true_false', 'According to the passage, removing false posts can make people suspicious.', null, array['true'], 'Đoạn 4: xoá bài sai có thể tạo cảm giác điều gì đó đang bị che giấu.', 3),
('b4000000-0000-4000-8000-000000000005', 'true_false', 'The passage says labelling false posts works equally well at any time.', null, array['false'], 'Đoạn 4: dán nhãn chỉ hiệu quả nếu xuất hiện trước khi người đọc hình thành quan điểm.', 4),
('b4000000-0000-4000-8000-000000000005', 'multiple_choice', 'What does the writer suggest is the most effective measure?', '["Banning anonymous accounts", "Adding a short delay before sharing", "Publishing more corrections", "Training journalists better"]', array['Adding a short delay before sharing'], 'Đoạn cuối: làm chậm khoảnh khắc chia sẻ, thêm hai giây là đủ để lý trí bắt kịp.', 5),
('b4000000-0000-4000-8000-000000000006', 'multiple_choice', 'Why were night trains withdrawn in the 1990s?', '["They were unsafe", "Budget airlines were far cheaper and faster", "Passengers disliked sleeping", "Governments banned them"]', array['Budget airlines were far cheaper and faster'], 'Đoạn 1: hãng bay giá rẻ vượt châu lục trong hai tiếng với giá bằng một cuốc taxi.', 1),
('b4000000-0000-4000-8000-000000000006', 'true_false', 'The passage says some governments have taxed short domestic flights.', null, array['true'], 'Đoạn 2 nêu đúng điều này.', 2),
('b4000000-0000-4000-8000-000000000006', 'multiple_choice', 'What does the writer say the airline model conceals?', '["The price of tickets", "The true door-to-door length of a flight", "The number of passengers", "The age of the aircraft"]', array['The true door-to-door length of a flight'], 'Đoạn 3: hai tiếng bay thành sáu bảy tiếng khi tính cả sân bay, an ninh và trung chuyển.', 3),
('b4000000-0000-4000-8000-000000000006', 'multiple_choice', 'Why are night train tickets rarely cheap?', '["Demand is too low", "Sleeping carriages are costly and carry fewer people", "Fuel is expensive", "Staff wages are high"]', array['Sleeping carriages are costly and carry fewer people'], 'Đoạn 4: toa giường đắt để chế tạo và chở được ít khách hơn toa ghế.', 4),
('b4000000-0000-4000-8000-000000000006', 'true_false', 'The writer concludes that the fastest option always saves the most time.', null, array['false'], 'Câu cuối nói ngược lại: lựa chọn nhanh nhất không phải lúc nào cũng tiết kiệm thời gian nhất.', 5),
('b4000000-0000-4000-8000-000000000007', 'multiple_choice', 'Why is the value of personal data ''invisible'' at the moment of exchange?', '["Companies hide their profits", "One person''s record alone is nearly worthless", "The data is encrypted", "Users are not told the price"]', array['One person''s record alone is nearly worthless'], 'Đoạn 2: một bản ghi đơn lẻ gần như vô giá trị, chỉ khi gộp hàng triệu bản mới có giá.', 1),
('b4000000-0000-4000-8000-000000000007', 'multiple_choice', 'What is the critics'' main argument?', '["Free services cost too much", "Consent without understanding is not real consent", "Data should be deleted monthly", "Advertising should be banned"]', array['Consent without understanding is not real consent'], 'Đoạn 3: sự đồng ý mà không hiểu thì không thực sự là đồng ý.', 2),
('b4000000-0000-4000-8000-000000000007', 'true_false', 'According to the passage, new government rules have solved the problem.', null, array['false'], 'Đoạn 4: hiệu quả tới nay còn hạn chế, phần lớn người dùng vẫn bấm ''accept''.', 3),
('b4000000-0000-4000-8000-000000000007', 'true_false', 'The writer suggests that ownership is hard to define for data because data can be copied endlessly.', null, array['true'], 'Đoạn cuối nêu đúng lý do này.', 4),
('b4000000-0000-4000-8000-000000000007', 'multiple_choice', 'What approach does the writer consider more workable?', '["Giving users legal ownership", "Restricting particular uses of data", "Banning free applications", "Paying users for their data"]', array['Restricting particular uses of data'], 'Đoạn cuối: hạn chế những mục đích sử dụng cụ thể thì hẹp hơn nhưng có thể thực thi được.', 5),
('b4000000-0000-4000-8000-000000000008', 'multiple_choice', 'What is survivorship bias, according to the passage?', '["Studying only the cases that succeeded", "Preferring older companies", "Trusting statistics too much", "Ignoring market research"]', array['Studying only the cases that succeeded'], 'Đoạn 2: vì chỉ xem xét những người còn tồn tại nên hành vi bị hiểu nhầm là nguyên nhân thành công.', 1),
('b4000000-0000-4000-8000-000000000008', 'multiple_choice', 'In the aircraft example, where was armour actually needed?', '["On the wings", "Where returning planes showed no damage", "On every surface", "Nowhere at all"]', array['Where returning planes showed no damage'], 'Đoạn 3: những chỗ không hư trên máy bay trở về chính là nơi bị bắn thì sẽ rơi.', 2),
('b4000000-0000-4000-8000-000000000008', 'true_false', 'The mathematician agreed with the engineers'' original proposal.', null, array['false'], 'Đoạn 3: nhà toán học chỉ ra lỗ hổng trong đề xuất của các kỹ sư.', 3),
('b4000000-0000-4000-8000-000000000008', 'true_false', 'The writer advises asking whether an outcome could be explained by luck.', null, array['true'], 'Đoạn 4 nêu đúng lời khuyên này.', 4),
('b4000000-0000-4000-8000-000000000008', 'multiple_choice', 'Why does the writer say the imbalance is ''not neutral''?', '["It costs companies money", "It shapes what managers believe to be true", "It makes books more expensive", "It slows down research"]', array['It shapes what managers believe to be true'], 'Câu cuối: sự mất cân bằng đó định hình niềm tin của cả một thế hệ quản lý.', 5),
('b4000000-0000-4000-8000-000000000009', 'multiple_choice', 'Why do retailers welcome electronic payment?', '["It attracts younger customers", "Counting and carrying cash is slow and risky", "It is legally required", "It reduces their taxes"]', array['Counting and carrying cash is slow and risky'], 'Đoạn 1 nêu đúng hai lý do này.', 1),
('b4000000-0000-4000-8000-000000000009', 'multiple_choice', 'Which groups does the writer say are most affected by the loss of cash?', '["Tourists and students", "Elderly people and informally paid workers", "Bank employees", "Shop owners"]', array['Elderly people and informally paid workers'], 'Đoạn 3 liệt kê người cao tuổi, người được trả lương không chính thức, và người bị đóng tài khoản.', 2),
('b4000000-0000-4000-8000-000000000009', 'true_false', 'The passage points out that cash needs no battery or signal.', null, array['true'], 'Đoạn 3 nêu đúng đặc điểm này.', 3),
('b4000000-0000-4000-8000-000000000009', 'true_false', 'The writer describes the compromise as motivated by nostalgia.', null, array['false'], 'Đoạn cuối: ''This is not nostalgia.''', 4),
('b4000000-0000-4000-8000-000000000009', 'multiple_choice', 'What does the writer mean by a system that can ''fail gracefully''?', '["A system that never breaks", "A system with an alternative when one method stops working", "A system run by the government", "A system that is cheap to repair"]', array['A system with an alternative when one method stops working'], 'Ý là hệ thống chỉ có một phương thức thì khi hỏng không còn cách nào thay thế.', 5),
('b4000000-0000-4000-8000-000000000010', 'multiple_choice', 'What is the availability heuristic?', '["Judging risk by how easily an example comes to mind", "Choosing the cheapest option", "Trusting official statistics", "Avoiding all unfamiliar situations"]', array['Judging risk by how easily an example comes to mind'], 'Đoạn 2 định nghĩa đúng như vậy.', 1),
('b4000000-0000-4000-8000-000000000010', 'multiple_choice', 'Why are road deaths less frightening than air accidents?', '["They happen less often", "They are reported briefly and leave no vivid impression", "They are not recorded", "They only affect drivers"]', array['They are reported briefly and leave no vivid impression'], 'Đoạn 2: tai nạn đường bộ được đưa tin ngắn và địa phương nên không để lại ấn tượng mạnh.', 2),
('b4000000-0000-4000-8000-000000000010', 'true_false', 'According to the passage, feeling in control makes people accept more danger.', null, array['true'], 'Đoạn 3 nêu đúng điều này.', 3),
('b4000000-0000-4000-8000-000000000010', 'multiple_choice', 'What does the treatment example show?', '["Doctors explain badly", "Identical facts feel different depending on wording", "Most treatments fail", "Patients dislike statistics"]', array['Identical facts feel different depending on wording'], 'Đoạn 4: ''cứu được 90%'' và ''mất 10%'' là như nhau nhưng cảm nhận khác nhau.', 4),
('b4000000-0000-4000-8000-000000000010', 'true_false', 'The writer claims that understanding these effects removes them completely.', null, array['false'], 'Đoạn cuối: ''Knowing about these effects does not remove them.''', 5);
