# -*- coding: utf-8 -*-
TOPIC = 9  # People — Con người
DATA = {
"person": [("She is a kind person.","Cô ấy là một người tốt bụng."),
 ("Only one person was waiting.","Chỉ có một người đang đợi."),
 ("He is the right person for this job.","Anh ấy là người phù hợp cho công việc này.")],
"man": [("The man is reading a book.","Người đàn ông đang đọc sách."),
 ("An old man sat by the window.","Một ông lão ngồi bên cửa sổ."),
 ("That man works at the bank.","Người đàn ông đó làm ở ngân hàng.")],
"woman": [("That woman is my teacher.","Người phụ nữ đó là cô giáo tôi."),
 ("A young woman asked for directions.","Một phụ nữ trẻ hỏi đường."),
 ("The woman next door is a doctor.","Người phụ nữ nhà bên là bác sĩ.")],
"child": [("The child is playing outside.","Đứa trẻ đang chơi bên ngoài."),
 ("Every child needs love.","Mọi đứa trẻ đều cần tình yêu thương."),
 ("The child fell asleep in the car.","Đứa bé ngủ quên trong xe.")],
"baby": [("The baby is sleeping.","Em bé đang ngủ."),
 ("The baby started walking last week.","Em bé bắt đầu biết đi tuần trước."),
 ("She is holding a baby.","Cô ấy đang bế một em bé.")],
"boy": [("The boy runs very fast.","Cậu bé chạy rất nhanh."),
 ("A boy is waiting at the gate.","Một cậu bé đang đợi ở cổng."),
 ("The boy helped an old woman.","Cậu bé giúp một bà cụ.")],
"girl": [("The girl likes drawing.","Cô bé thích vẽ."),
 ("A little girl waved at me.","Một cô bé vẫy tay chào tôi."),
 ("The girl won first prize.","Cô bé giành giải nhất.")],
"teenager": [("My son is a teenager now.","Con trai tôi giờ là thiếu niên."),
 ("Teenagers spend hours on phones.","Thiếu niên dành hàng giờ với điện thoại."),
 ("She was a shy teenager.","Cô ấy từng là một thiếu niên nhút nhát.")],
"adult": [("Adults pay full price.","Người lớn trả nguyên giá."),
 ("Only adults can drive a car.","Chỉ người lớn mới được lái ô tô."),
 ("Three adults and two children.","Ba người lớn và hai trẻ em.")],
"elderly": [("We should help elderly people.","Chúng ta nên giúp đỡ người lớn tuổi."),
 ("An elderly man lives next door.","Một cụ ông sống ở nhà bên."),
 ("The elderly need regular checkups.","Người lớn tuổi cần khám định kỳ.")],
"tall": [("He is tall and thin.","Anh ấy cao và gầy."),
 ("She is the tallest in her class.","Cô ấy cao nhất lớp."),
 ("Basketball players are usually tall.","Cầu thủ bóng rổ thường cao.")],
"short": [("She has short hair.","Cô ấy để tóc ngắn."),
 ("He is shorter than his brother.","Cậu ấy thấp hơn anh trai."),
 ("It was a short walk to school.","Đường đến trường ngắn thôi.")],
"thin": [("The cat is very thin.","Con mèo rất gầy."),
 ("He became thin after the illness.","Anh ấy gầy đi sau trận ốm."),
 ("This paper is very thin.","Tờ giấy này rất mỏng.")],
"slim": [("She stays slim by running.","Cô ấy giữ dáng thon nhờ chạy bộ."),
 ("He has a slim build.","Anh ấy có dáng người thon."),
 ("The dress makes her look slim.","Chiếc váy làm cô ấy trông thon thả.")],
"strong": [("He is strong enough to lift it.","Anh ấy đủ khoẻ để nhấc nó lên."),
 ("She has a strong personality.","Cô ấy có cá tính mạnh mẽ."),
 ("Farmers have strong arms.","Nông dân có đôi tay khoẻ.")],
"weak": [("I feel weak after the flu.","Tôi thấy yếu sau khi bị cúm."),
 ("His legs are still weak.","Chân anh ấy vẫn còn yếu."),
 ("The signal here is weak.","Sóng ở đây yếu.")],
"young": [("She looks very young.","Cô ấy trông rất trẻ."),
 ("He started working when he was young.","Anh ấy đi làm từ khi còn trẻ."),
 ("Young people learn languages faster.","Người trẻ học ngoại ngữ nhanh hơn.")],
"old": [("My grandfather is old but healthy.","Ông tôi già nhưng khoẻ."),
 ("This old house needs repair.","Ngôi nhà cũ này cần sửa."),
 ("How old are you?","Bạn bao nhiêu tuổi?")],
"beautiful": [("What a beautiful smile!","Nụ cười đẹp quá!"),
 ("The sunset is beautiful tonight.","Hoàng hôn tối nay thật đẹp."),
 ("She wore a beautiful dress.","Cô ấy mặc một chiếc váy đẹp.")],
"handsome": [("Her brother is handsome.","Anh trai cô ấy đẹp trai."),
 ("He looked handsome in that suit.","Anh ấy trông đẹp trai trong bộ vest đó."),
 ("A handsome young man opened the door.","Một chàng trai đẹp trai mở cửa.")],
"pretty": [("That is a pretty dress.","Đó là một chiếc váy xinh."),
 ("She has a pretty face.","Cô ấy có khuôn mặt xinh."),
 ("The garden looks pretty in spring.","Khu vườn trông xinh xắn vào mùa xuân.")],
"cute": [("The puppy is so cute.","Con chó con dễ thương quá."),
 ("She has a cute laugh.","Cô ấy có tiếng cười dễ thương."),
 ("What a cute little hat!","Cái mũ nhỏ dễ thương quá!")],
"hair": [("She has long black hair.","Cô ấy có mái tóc đen dài."),
 ("He cut his hair yesterday.","Anh ấy cắt tóc hôm qua."),
 ("Her hair is wet from the rain.","Tóc cô ấy ướt vì mưa.")],
"eye": [("His eyes are brown.","Mắt anh ấy màu nâu."),
 ("Close your eyes and rest.","Nhắm mắt lại và nghỉ ngơi."),
 ("Something got in my eye.","Có gì đó bay vào mắt tôi.")],
"face": [("She has a friendly face.","Cô ấy có khuôn mặt thân thiện."),
 ("Wash your face before bed.","Rửa mặt trước khi đi ngủ."),
 ("His face turned red.","Mặt anh ấy đỏ bừng.")],
"nose": [("The baby has a small nose.","Em bé có cái mũi nhỏ."),
 ("My nose is blocked.","Mũi tôi bị nghẹt."),
 ("She wrinkled her nose at the smell.","Cô ấy nhăn mũi vì mùi đó.")],
"mouth": [("Open your mouth, please.","Vui lòng há miệng ra."),
 ("Do not talk with your mouth full.","Đừng nói khi miệng đang đầy thức ăn."),
 ("He covered his mouth and coughed.","Anh ấy che miệng và ho.")],
"ear": [("Rabbits have long ears.","Thỏ có đôi tai dài."),
 ("My ears hurt on the plane.","Tai tôi đau khi đi máy bay."),
 ("She whispered in my ear.","Cô ấy thì thầm vào tai tôi.")],
"skin": [("Protect your skin from the sun.","Bảo vệ da khỏi ánh nắng."),
 ("Her skin is very soft.","Da cô ấy rất mềm."),
 ("Dry skin needs more cream.","Da khô cần thoa nhiều kem hơn.")],
"beard": [("He has a short beard.","Anh ấy để râu ngắn."),
 ("His beard is turning gray.","Râu anh ấy đang bạc."),
 ("He shaved off his beard.","Anh ấy cạo râu đi rồi.")],
"smile": [("Her smile is warm.","Nụ cười của cô ấy thật ấm áp."),
 ("He smiled at the children.","Anh ấy mỉm cười với bọn trẻ."),
 ("A smile costs nothing.","Một nụ cười chẳng mất gì.")],
"curly": [("She has curly hair.","Cô ấy có mái tóc xoăn."),
 ("His curly hair is hard to comb.","Tóc xoăn của anh ấy khó chải."),
 ("The baby has soft curly hair.","Em bé có mái tóc xoăn mềm.")],
"straight": [("His hair is straight.","Tóc anh ấy thẳng."),
 ("Draw a straight line here.","Vẽ một đường thẳng ở đây."),
 ("Go straight and then turn left.","Đi thẳng rồi rẽ trái.")],
"bald": [("My uncle is going bald.","Chú tôi đang bị hói."),
 ("The bald man smiled at us.","Người đàn ông hói đầu mỉm cười với chúng tôi."),
 ("He went bald in his thirties.","Anh ấy hói từ tuổi ba mươi.")],
"height": [("What is your height?","Chiều cao của bạn là bao nhiêu?"),
 ("They are the same height.","Họ cao bằng nhau."),
 ("Her height helps her in volleyball.","Chiều cao giúp cô ấy chơi bóng chuyền.")],
"weight": [("He checks his weight weekly.","Anh ấy kiểm tra cân nặng hàng tuần."),
 ("She lost weight last month.","Cô ấy giảm cân tháng trước."),
 ("The bag is over the weight limit.","Cái túi vượt quá giới hạn cân nặng.")],
"appearance": [("Do not judge by appearance.","Đừng đánh giá qua vẻ bề ngoài."),
 ("He cares a lot about his appearance.","Anh ấy rất chú ý đến vẻ ngoài."),
 ("Her appearance surprised everyone.","Vẻ ngoài của cô ấy khiến ai cũng bất ngờ.")],
"twin": [("They are twin sisters.","Họ là chị em sinh đôi."),
 ("My twin brother lives abroad.","Em trai sinh đôi của tôi sống ở nước ngoài."),
 ("The twins look exactly alike.","Cặp sinh đôi giống nhau y hệt.")],
"polite": [("He is always polite to guests.","Anh ấy luôn lịch sự với khách."),
 ("It is polite to say thank you.","Nói cảm ơn là lịch sự."),
 ("She gave a polite answer.","Cô ấy đưa ra một câu trả lời lịch sự.")],
"clever": [("She is a clever student.","Cô ấy là một học sinh thông minh."),
 ("That was a clever idea.","Đó là một ý tưởng thông minh."),
 ("He is clever with his hands.","Anh ấy khéo tay.")],
"eyebrow": [("She has thick eyebrows.","Cô ấy có đôi lông mày rậm."),
 ("He raised an eyebrow in surprise.","Anh ấy nhướn mày ngạc nhiên."),
 ("Her eyebrows are neatly shaped.","Lông mày cô ấy được tỉa gọn gàng.")],
"lip": [("Her lips are dry.","Môi cô ấy khô."),
 ("He bit his lip nervously.","Anh ấy cắn môi lo lắng."),
 ("Put some cream on your lips.","Thoa chút kem lên môi đi.")],
"tooth": [("The baby has one tooth.","Em bé có một cái răng."),
 ("I broke a tooth eating candy.","Tôi gãy răng khi ăn kẹo."),
 ("The dentist pulled out my bad tooth.","Nha sĩ nhổ cái răng sâu của tôi.")],
"shoulder": [("He carried the bag on his shoulder.","Anh ấy đeo túi trên vai."),
 ("My shoulder hurts after the gym.","Vai tôi đau sau khi tập."),
 ("She patted him on the shoulder.","Cô ấy vỗ vai anh ấy.")],
"hand": [("Wash your hands, please.","Vui lòng rửa tay."),
 ("He held her hand tightly.","Anh ấy nắm chặt tay cô ấy."),
 ("Raise your hand if you know.","Giơ tay nếu bạn biết.")],
"arm": [("He broke his left arm.","Anh ấy gãy tay trái."),
 ("She carried the baby in her arms.","Cô ấy bế em bé trên tay."),
 ("My arms ache from swimming.","Tay tôi mỏi vì bơi.")],
"leg": [("My legs hurt after the hike.","Chân tôi đau sau chuyến đi bộ."),
 ("The table has one broken leg.","Cái bàn gãy một chân."),
 ("He stretched his legs.","Anh ấy duỗi chân.")],
"foot": [("My foot is asleep.","Chân tôi bị tê."),
 ("She hurt her foot playing football.","Cô ấy đau chân khi đá bóng."),
 ("He came to school on foot.","Cậu ấy đi bộ đến trường.")],
"finger": [("She cut her finger.","Cô ấy đứt tay."),
 ("He pointed with his finger.","Anh ấy chỉ tay."),
 ("The ring does not fit my finger.","Chiếc nhẫn không vừa ngón tay tôi.")],
"chubby": [("The baby has chubby cheeks.","Em bé có đôi má phúng phính."),
 ("He was a chubby child.","Hồi bé cậu ấy mũm mĩm."),
 ("Her chubby hands are so cute.","Đôi bàn tay mũm mĩm của bé thật dễ thương.")],
}
