# -*- coding: utf-8 -*-
TOPIC = 8  # City — Thành phố
DATA = {
"city": [("Hanoi is a busy city.","Hà Nội là một thành phố nhộn nhịp."),
 ("She moved to the city last year.","Cô ấy chuyển lên thành phố năm ngoái."),
 ("This city never sleeps.","Thành phố này không bao giờ ngủ.")],
"town": [("She grew up in a small town.","Cô ấy lớn lên ở một thị trấn nhỏ."),
 ("The town has only one school.","Thị trấn chỉ có một trường học."),
 ("Everyone in town knows him.","Cả thị trấn ai cũng biết anh ấy.")],
"village": [("The village is quiet and green.","Ngôi làng yên tĩnh và xanh mát."),
 ("My grandparents live in a village.","Ông bà tôi sống ở một ngôi làng."),
 ("The whole village came to the festival.","Cả làng đến dự lễ hội.")],
"street": [("The street is full of shops.","Con phố đầy cửa hàng."),
 ("Cross the street at the light.","Qua đường ở chỗ đèn tín hiệu."),
 ("This street is closed for repairs.","Con phố này đóng để sửa chữa.")],
"road": [("This road leads to the beach.","Con đường này dẫn ra biển."),
 ("The road is under construction.","Con đường đang thi công."),
 ("Be careful, the road is wet.","Cẩn thận, đường trơn.")],
"building": [("That building is very tall.","Toà nhà đó rất cao."),
 ("The building was built in 1950.","Toà nhà được xây năm 1950."),
 ("Our office is in that white building.","Văn phòng chúng tôi ở toà nhà trắng kia.")],
"apartment": [("They rent a small apartment.","Họ thuê một căn hộ nhỏ."),
 ("My apartment is on the fifth floor.","Căn hộ của tôi ở tầng năm."),
 ("The apartment has a nice view.","Căn hộ có tầm nhìn đẹp.")],
"market": [("The market opens early.","Chợ mở cửa sớm."),
 ("She buys vegetables at the market.","Cô ấy mua rau ngoài chợ."),
 ("The market is crowded on Sunday.","Chợ đông vào Chủ nhật.")],
"supermarket": [("I buy food at the supermarket.","Tôi mua đồ ăn ở siêu thị."),
 ("The supermarket closes at ten.","Siêu thị đóng cửa lúc mười giờ."),
 ("There is a new supermarket nearby.","Có một siêu thị mới gần đây.")],
"mall": [("We met at the mall.","Chúng tôi gặp nhau ở trung tâm thương mại."),
 ("The mall has a cinema inside.","Trung tâm thương mại có rạp phim bên trong."),
 ("The mall is packed on weekends.","Trung tâm thương mại chật kín vào cuối tuần.")],
"restaurant": [("This restaurant serves noodles.","Nhà hàng này bán mì."),
 ("We booked a table at the restaurant.","Chúng tôi đặt bàn ở nhà hàng."),
 ("The restaurant is famous for seafood.","Nhà hàng nổi tiếng về hải sản.")],
"cafe": [("Let us meet at the cafe.","Gặp nhau ở quán cà phê nhé."),
 ("This cafe has free wifi.","Quán cà phê này có wifi miễn phí."),
 ("She works in a cafe on weekends.","Cô ấy làm ở quán cà phê vào cuối tuần.")],
"hotel": [("The hotel is near the beach.","Khách sạn ở gần biển."),
 ("We stayed at a cheap hotel.","Chúng tôi ở một khách sạn rẻ."),
 ("The hotel has a rooftop pool.","Khách sạn có hồ bơi trên sân thượng.")],
"hospital": [("The hospital is open all night.","Bệnh viện mở cửa cả đêm."),
 ("She works at the city hospital.","Cô ấy làm ở bệnh viện thành phố."),
 ("He was taken to hospital yesterday.","Anh ấy được đưa vào bệnh viện hôm qua.")],
"library": [("I study at the library.","Tôi học ở thư viện."),
 ("The library has thousands of books.","Thư viện có hàng nghìn cuốn sách."),
 ("Please be quiet in the library.","Vui lòng giữ yên lặng trong thư viện.")],
"park": [("We walk in the park.","Chúng tôi đi dạo trong công viên."),
 ("The park is beautiful in autumn.","Công viên rất đẹp vào mùa thu."),
 ("Children play football in the park.","Bọn trẻ đá bóng trong công viên.")],
"museum": [("The museum is free on Sunday.","Bảo tàng miễn phí vào Chủ nhật."),
 ("We spent two hours in the museum.","Chúng tôi ở bảo tàng hai tiếng."),
 ("The museum shows ancient pottery.","Bảo tàng trưng bày gốm cổ.")],
"cinema": [("We watched a film at the cinema.","Chúng tôi xem phim ở rạp."),
 ("The cinema was almost empty.","Rạp phim gần như trống."),
 ("There is a new cinema downtown.","Có một rạp phim mới ở trung tâm.")],
"station": [("The train station is crowded.","Nhà ga rất đông."),
 ("Meet me at the station at six.","Gặp tôi ở nhà ga lúc sáu giờ."),
 ("The bus station is behind the market.","Bến xe buýt ở sau chợ.")],
"bank": [("The bank closes at five.","Ngân hàng đóng cửa lúc năm giờ."),
 ("I opened an account at this bank.","Tôi mở tài khoản ở ngân hàng này."),
 ("There is a bank on every corner.","Góc phố nào cũng có ngân hàng.")],
"bridge": [("We crossed the long bridge.","Chúng tôi đi qua cây cầu dài."),
 ("The bridge connects two districts.","Cây cầu nối hai quận."),
 ("The old bridge is closed to cars.","Cầu cũ cấm ô tô.")],
"square": [("People gather in the square.","Mọi người tụ tập ở quảng trường."),
 ("The square is lit up at night.","Quảng trường sáng đèn về đêm."),
 ("There is a fountain in the square.","Có một đài phun nước giữa quảng trường.")],
"traffic": [("The traffic is heavy at rush hour.","Giao thông đông đúc vào giờ cao điểm."),
 ("Traffic moves slowly in the rain.","Xe cộ đi chậm khi trời mưa."),
 ("The traffic here is terrible.","Giao thông ở đây kinh khủng.")],
"sidewalk": [("Walk on the sidewalk, please.","Vui lòng đi trên vỉa hè."),
 ("The sidewalk is full of parked bikes.","Vỉa hè đầy xe đỗ."),
 ("They sell food on the sidewalk.","Họ bán đồ ăn trên vỉa hè.")],
"corner": [("The shop is on the corner.","Cửa hàng ở góc phố."),
 ("Turn left at the next corner.","Rẽ trái ở góc phố tới."),
 ("She waited at the corner.","Cô ấy đợi ở góc phố.")],
"downtown": [("She works downtown.","Cô ấy làm việc ở trung tâm."),
 ("Downtown is busy at night.","Trung tâm nhộn nhịp về đêm."),
 ("We drove downtown for dinner.","Chúng tôi lái xe vào trung tâm ăn tối.")],
"suburb": [("They moved to the suburbs.","Họ chuyển ra ngoại ô."),
 ("The suburb is quiet and green.","Vùng ngoại ô yên tĩnh và xanh."),
 ("Houses in the suburbs are cheaper.","Nhà ở ngoại ô rẻ hơn.")],
"factory": [("He works in a factory.","Anh ấy làm việc trong nhà máy."),
 ("The factory makes shoes.","Nhà máy sản xuất giày."),
 ("The factory employs three hundred people.","Nhà máy có ba trăm công nhân.")],
"office": [("Our office is on the third floor.","Văn phòng chúng tôi ở tầng ba."),
 ("The office is empty at lunchtime.","Văn phòng vắng vào giờ trưa."),
 ("She left the office at seven.","Cô ấy rời văn phòng lúc bảy giờ.")],
"pharmacy": [("Buy the medicine at the pharmacy.","Mua thuốc ở nhà thuốc."),
 ("The pharmacy is open until midnight.","Nhà thuốc mở đến nửa đêm."),
 ("There is a pharmacy next to the clinic.","Có một nhà thuốc cạnh phòng khám.")],
"bookstore": [("There is a bookstore nearby.","Có một hiệu sách gần đây."),
 ("She spent an hour in the bookstore.","Cô ấy ở hiệu sách một tiếng."),
 ("This bookstore sells old maps too.","Hiệu sách này bán cả bản đồ cũ.")],
"bakery": [("The bakery smells wonderful.","Tiệm bánh thơm nức."),
 ("I buy bread at the bakery every morning.","Tôi mua bánh mì ở tiệm mỗi sáng."),
 ("The bakery opens at five.","Tiệm bánh mở lúc năm giờ.")],
"temple": [("The old temple is famous.","Ngôi chùa cổ rất nổi tiếng."),
 ("We visited the temple at Tet.","Chúng tôi đi chùa dịp Tết."),
 ("The temple is over three hundred years old.","Ngôi chùa hơn ba trăm tuổi.")],
"stadium": [("The stadium was full of fans.","Sân vận động đầy cổ động viên."),
 ("The new stadium holds fifty thousand people.","Sân vận động mới chứa năm mươi nghìn người."),
 ("They built a stadium outside the city.","Họ xây một sân vận động ngoài thành phố.")],
"crossroads": [("Turn left at the crossroads.","Rẽ trái ở ngã tư."),
 ("There is a market at the crossroads.","Có một cái chợ ở ngã tư."),
 ("Wait for me at the crossroads.","Đợi tôi ở ngã tư nhé.")],
"neighborhood": [("It is a safe neighborhood.","Đây là một khu phố an toàn."),
 ("Our neighborhood is very quiet.","Khu phố chúng tôi rất yên tĩnh."),
 ("The whole neighborhood joined the clean up.","Cả khu phố tham gia dọn dẹp.")],
"avenue": [("The avenue is lined with trees.","Đại lộ hai bên rợp cây."),
 ("She lives on a wide avenue.","Cô ấy sống trên một đại lộ rộng."),
 ("The avenue leads to the palace.","Đại lộ dẫn tới cung điện.")],
"parking": [("The parking is behind the mall.","Bãi đỗ xe ở sau trung tâm thương mại."),
 ("Parking is free for customers.","Đỗ xe miễn phí cho khách."),
 ("There is no parking on this street.","Phố này không được đỗ xe.")],
"crowded": [("The bus is very crowded.","Xe buýt rất đông."),
 ("The beach was crowded on Sunday.","Bãi biển đông nghịt vào Chủ nhật."),
 ("I do not like crowded places.","Tôi không thích chỗ đông người.")],
"quiet": [("This street is quiet at night.","Con phố này yên tĩnh về đêm."),
 ("Please keep quiet in the library.","Vui lòng giữ yên lặng trong thư viện."),
 ("The village is very quiet.","Ngôi làng rất yên tĩnh.")],
"church": [("The old church stands on the hill.","Nhà thờ cổ nằm trên đồi."),
 ("They got married in this church.","Họ cưới nhau ở nhà thờ này."),
 ("The church bells ring at six.","Chuông nhà thờ đổ lúc sáu giờ.")],
"post office": [("I mailed the letter at the post office.","Tôi gửi thư ở bưu điện."),
 ("The post office is closed on Sunday.","Bưu điện đóng cửa Chủ nhật."),
 ("There is a post office near the market.","Có một bưu điện gần chợ.")],
"police station": [("The police station is around the corner.","Đồn công an ở ngay góc phố."),
 ("He reported the theft at the police station.","Anh ấy trình báo vụ trộm ở đồn công an."),
 ("The police station is open all day.","Đồn công an mở cửa cả ngày.")],
"fire station": [("The fire station is always open.","Trạm cứu hoả luôn mở cửa."),
 ("The fire station is next to the school.","Trạm cứu hoả cạnh trường học."),
 ("Trucks left the fire station quickly.","Xe rời trạm cứu hoả rất nhanh.")],
"gym": [("I go to the gym after work.","Tôi đến phòng tập sau giờ làm."),
 ("The gym opens at five in the morning.","Phòng tập mở lúc năm giờ sáng."),
 ("This gym has a swimming pool.","Phòng tập này có hồ bơi.")],
"playground": [("Children play at the playground.","Trẻ em chơi ở sân chơi."),
 ("The playground is next to the school.","Sân chơi ở cạnh trường."),
 ("They built a new playground last year.","Họ xây một sân chơi mới năm ngoái.")],
"roundabout": [("Take the second exit at the roundabout.","Ra lối thứ hai ở vòng xuyến."),
 ("The roundabout is always busy.","Vòng xuyến lúc nào cũng đông."),
 ("There are flowers in the roundabout.","Có hoa trồng giữa vòng xuyến.")],
"alley": [("Their house is down a narrow alley.","Nhà họ nằm sâu trong một con hẻm hẹp."),
 ("The alley is too small for cars.","Con hẻm quá nhỏ cho ô tô."),
 ("A cat ran into the alley.","Một con mèo chạy vào hẻm.")],
"streetlight": [("The streetlights come on at dusk.","Đèn đường bật lúc chạng vạng."),
 ("One streetlight is broken.","Một cái đèn đường bị hỏng."),
 ("She waited under the streetlight.","Cô ấy đợi dưới ánh đèn đường.")],
"skyscraper": [("That skyscraper has sixty floors.","Toà nhà chọc trời đó có sáu mươi tầng."),
 ("The skyscraper changed the skyline.","Toà nhà chọc trời làm đổi cả đường chân trời."),
 ("You can see the sea from the skyscraper.","Từ toà nhà chọc trời có thể nhìn thấy biển.")],
}
