# -*- coding: utf-8 -*-
TOPIC = 7  # Nature — Thiên nhiên
DATA = {
"sun": [("The sun is very bright today.","Hôm nay mặt trời rất chói."),
 ("The sun rises at six.","Mặt trời mọc lúc sáu giờ."),
 ("Do not look straight at the sun.","Đừng nhìn thẳng vào mặt trời.")],
"moon": [("The moon is full tonight.","Tối nay trăng tròn."),
 ("The moon looks orange tonight.","Tối nay trăng trông màu cam."),
 ("Children love stories about the moon.","Trẻ con thích những câu chuyện về mặt trăng.")],
"star": [("We counted the stars.","Chúng tôi đếm những vì sao."),
 ("The stars are clear tonight.","Đêm nay sao rất rõ."),
 ("A falling star crossed the sky.","Một ngôi sao băng vụt qua bầu trời.")],
"sky": [("The sky is blue.","Bầu trời màu xanh."),
 ("Dark clouds filled the sky.","Mây đen phủ kín bầu trời."),
 ("Birds flew across the sky.","Đàn chim bay ngang bầu trời.")],
"cloud": [("There are gray clouds.","Có những đám mây xám."),
 ("The clouds moved slowly.","Những đám mây trôi chậm."),
 ("Not a single cloud today.","Hôm nay không một gợn mây.")],
"rain": [("The rain is heavy.","Mưa rất to."),
 ("We waited for the rain to stop.","Chúng tôi chờ mưa tạnh."),
 ("The rain lasted all afternoon.","Mưa kéo dài cả buổi chiều.")],
"wind": [("The wind is strong.","Gió rất mạnh."),
 ("A cold wind blew from the north.","Một cơn gió lạnh thổi từ phương Bắc."),
 ("The wind knocked down a tree.","Gió quật đổ một cái cây.")],
"storm": [("A storm is coming.","Bão đang tới."),
 ("The storm damaged many roofs.","Cơn bão làm hỏng nhiều mái nhà."),
 ("We stayed home during the storm.","Chúng tôi ở nhà suốt cơn bão.")],
"thunder": [("I heard loud thunder.","Tôi nghe tiếng sấm rất to."),
 ("The dog is afraid of thunder.","Con chó sợ tiếng sấm."),
 ("Thunder woke the whole house.","Tiếng sấm đánh thức cả nhà.")],
"lightning": [("Lightning lit up the sky.","Tia chớp làm sáng cả bầu trời."),
 ("Do not stand under a tree during lightning.","Đừng đứng dưới gốc cây khi có sấm chớp."),
 ("Lightning struck the old tower.","Sét đánh trúng ngọn tháp cũ.")],
"snow": [("Snow covers the mountain.","Tuyết phủ kín ngọn núi."),
 ("It never snows in my city.","Thành phố tôi chưa bao giờ có tuyết."),
 ("The children played in the snow.","Bọn trẻ chơi trong tuyết.")],
"fog": [("The fog is thick this morning.","Sáng nay sương mù dày đặc."),
 ("Fog made driving dangerous.","Sương mù khiến việc lái xe nguy hiểm."),
 ("The fog cleared by noon.","Sương mù tan lúc giữa trưa.")],
"rainbow": [("A rainbow appeared after the rain.","Một cầu vồng hiện ra sau cơn mưa."),
 ("The rainbow had seven colors.","Cầu vồng có bảy màu."),
 ("She painted a rainbow on the wall.","Cô bé vẽ cầu vồng lên tường.")],
"river": [("The river flows to the sea.","Con sông chảy ra biển."),
 ("We swam in the river.","Chúng tôi bơi dưới sông."),
 ("The river is wide here.","Con sông ở đoạn này rộng.")],
"lake": [("We swam in the lake.","Chúng tôi bơi trong hồ."),
 ("The lake freezes in winter.","Hồ đóng băng vào mùa đông."),
 ("There is a small island in the lake.","Có một hòn đảo nhỏ giữa hồ.")],
"sea": [("The sea is calm today.","Hôm nay biển lặng."),
 ("We drove along the sea.","Chúng tôi lái xe dọc bờ biển."),
 ("The sea looks green here.","Biển ở đây trông màu xanh lục.")],
"ocean": [("The ocean is very deep.","Đại dương rất sâu."),
 ("Plastic is polluting the ocean.","Nhựa đang làm ô nhiễm đại dương."),
 ("They sailed across the ocean.","Họ vượt đại dương bằng thuyền buồm.")],
"mountain": [("They climbed the mountain.","Họ leo lên ngọn núi."),
 ("The mountain is covered with snow.","Ngọn núi phủ đầy tuyết."),
 ("We drove around the mountain.","Chúng tôi lái xe vòng quanh núi.")],
"hill": [("A small house sits on the hill.","Một ngôi nhà nhỏ nằm trên đồi."),
 ("We walked up the hill slowly.","Chúng tôi chậm rãi leo lên đồi."),
 ("The hill is green all year.","Ngọn đồi xanh quanh năm.")],
"forest": [("The forest is full of birds.","Khu rừng đầy tiếng chim."),
 ("They got lost in the forest.","Họ bị lạc trong rừng."),
 ("The forest is quiet at dawn.","Khu rừng yên tĩnh lúc bình minh.")],
"tree": [("The tree gives good shade.","Cái cây cho bóng mát."),
 ("They planted a tree in the yard.","Họ trồng một cái cây ngoài sân."),
 ("That tree is over a hundred years old.","Cây đó hơn một trăm tuổi.")],
"leaf": [("A yellow leaf fell down.","Một chiếc lá vàng rơi xuống."),
 ("The leaf floated on the water.","Chiếc lá trôi trên mặt nước."),
 ("Each leaf has a different shape.","Mỗi chiếc lá có hình dáng khác nhau.")],
"flower": [("She picked a red flower.","Cô ấy hái một bông hoa đỏ."),
 ("The flowers smell wonderful.","Những bông hoa thơm ngát."),
 ("This flower only blooms at night.","Loài hoa này chỉ nở về đêm.")],
"grass": [("The grass is green and soft.","Cỏ xanh và mềm."),
 ("We sat on the grass.","Chúng tôi ngồi trên cỏ."),
 ("The grass needs cutting.","Cỏ cần được cắt.")],
"beach": [("We relaxed on the beach.","Chúng tôi thư giãn trên bãi biển."),
 ("The beach is empty in winter.","Bãi biển vắng vào mùa đông."),
 ("They walked along the beach at sunset.","Họ đi dạo trên bãi biển lúc hoàng hôn.")],
"sand": [("The sand is warm.","Cát ấm."),
 ("She built a castle out of sand.","Cô bé xây lâu đài bằng cát."),
 ("Sand got into my shoes.","Cát chui vào giày tôi.")],
"desert": [("The desert is very dry.","Sa mạc rất khô cằn."),
 ("Few plants grow in the desert.","Ít cây cối mọc được ở sa mạc."),
 ("The desert is cold at night.","Sa mạc lạnh về đêm.")],
"island": [("They live on a small island.","Họ sống trên một hòn đảo nhỏ."),
 ("The island can only be reached by boat.","Chỉ có thể đến đảo bằng thuyền."),
 ("This island has no cars.","Hòn đảo này không có ô tô.")],
"valley": [("A river runs through the valley.","Một con sông chảy qua thung lũng."),
 ("The valley is full of flowers in spring.","Thung lũng đầy hoa vào mùa xuân."),
 ("Their village lies in a green valley.","Làng họ nằm trong một thung lũng xanh.")],
"waterfall": [("The waterfall is beautiful.","Thác nước rất đẹp."),
 ("We heard the waterfall from far away.","Chúng tôi nghe tiếng thác từ xa."),
 ("The waterfall is highest in the rainy season.","Thác nước cao nhất vào mùa mưa.")],
"cave": [("The cave is dark and cool.","Hang động tối và mát."),
 ("They explored the cave with lights.","Họ khám phá hang bằng đèn."),
 ("Bats live inside the cave.","Dơi sống trong hang.")],
"rock": [("He sat on a big rock.","Anh ấy ngồi trên một tảng đá lớn."),
 ("The rock is too heavy to move.","Tảng đá nặng quá không đẩy nổi."),
 ("Waves hit the rocks all day.","Sóng đập vào những tảng đá cả ngày.")],
"weather": [("The weather is nice today.","Hôm nay thời tiết đẹp."),
 ("The weather changed suddenly.","Thời tiết thay đổi đột ngột."),
 ("Check the weather before you go.","Xem thời tiết trước khi đi.")],
"temperature": [("The temperature is falling.","Nhiệt độ đang giảm."),
 ("The temperature reached forty degrees.","Nhiệt độ lên tới bốn mươi độ."),
 ("Water boils at a high temperature.","Nước sôi ở nhiệt độ cao.")],
"climate": [("Vietnam has a tropical climate.","Việt Nam có khí hậu nhiệt đới."),
 ("The climate here is dry.","Khí hậu ở đây khô."),
 ("Climate change affects farming.","Biến đổi khí hậu ảnh hưởng tới nông nghiệp.")],
"season": [("Autumn is my favorite season.","Mùa thu là mùa tôi thích nhất."),
 ("There are four seasons in the north.","Miền Bắc có bốn mùa."),
 ("The rainy season starts in May.","Mùa mưa bắt đầu từ tháng Năm.")],
"sunny": [("It is sunny and warm.","Trời nắng và ấm."),
 ("We had a sunny weekend.","Chúng tôi có một cuối tuần nắng đẹp."),
 ("Sunny days make me happy.","Những ngày nắng làm tôi vui.")],
"cloudy": [("The sky is cloudy.","Trời nhiều mây."),
 ("It was cloudy all morning.","Trời nhiều mây suốt buổi sáng."),
 ("A cloudy day is good for walking.","Ngày nhiều mây rất hợp để đi bộ.")],
"windy": [("It is windy near the sea.","Gần biển thì nhiều gió."),
 ("It was too windy to fly a kite.","Gió mạnh quá không thả diều được."),
 ("Windy weather makes me cold.","Thời tiết nhiều gió khiến tôi lạnh.")],
"humid": [("Summer here is hot and humid.","Mùa hè ở đây nóng và ẩm."),
 ("The air feels humid today.","Hôm nay không khí ẩm."),
 ("Humid weather is hard for my hair.","Thời tiết ẩm làm tóc tôi khó chịu.")],
"volcano": [("The volcano erupted last year.","Núi lửa phun trào năm ngoái."),
 ("They climbed to the top of the volcano.","Họ leo lên đỉnh núi lửa."),
 ("This volcano has been quiet for years.","Núi lửa này im lặng nhiều năm rồi.")],
"earthquake": [("The earthquake damaged many houses.","Trận động đất làm hỏng nhiều ngôi nhà."),
 ("We felt a small earthquake.","Chúng tôi cảm nhận một trận động đất nhỏ."),
 ("The earthquake lasted ten seconds.","Trận động đất kéo dài mười giây.")],
"flood": [("The flood covered the whole village.","Lũ ngập cả ngôi làng."),
 ("Heavy rain caused the flood.","Mưa lớn gây ra lũ."),
 ("The flood destroyed the rice fields.","Lũ phá huỷ những cánh đồng lúa.")],
"drought": [("The drought lasted three months.","Hạn hán kéo dài ba tháng."),
 ("The drought killed many crops.","Hạn hán làm chết nhiều hoa màu."),
 ("Farmers suffer most in a drought.","Nông dân khổ nhất khi hạn hán.")],
"soil": [("This soil is good for rice.","Loại đất này hợp trồng lúa."),
 ("The soil is dry and hard.","Đất khô và cứng."),
 ("Good soil makes strong plants.","Đất tốt cho cây khoẻ.")],
"mud": [("The path was full of mud.","Con đường đầy bùn."),
 ("His shoes are covered in mud.","Giày anh ấy dính đầy bùn."),
 ("The buffalo lay in the mud.","Con trâu nằm trong bùn.")],
"ice": [("The lake is covered with ice.","Mặt hồ phủ băng."),
 ("Put some ice in my drink.","Cho ít đá vào đồ uống của tôi."),
 ("The ice melted quickly.","Băng tan rất nhanh.")],
"stream": [("A small stream runs behind the house.","Một dòng suối nhỏ chảy sau nhà."),
 ("The stream dries up in summer.","Con suối cạn vào mùa hè."),
 ("We drank water from the stream.","Chúng tôi uống nước từ suối.")],
"coast": [("We drove along the coast.","Chúng tôi lái xe dọc bờ biển."),
 ("The coast is rocky here.","Bờ biển ở đây nhiều đá."),
 ("Their town is on the east coast.","Thị trấn của họ nằm ở bờ biển phía đông.")],
"jungle": [("Wild animals live in the jungle.","Thú hoang sống trong rừng rậm."),
 ("The jungle is hot and wet.","Rừng rậm nóng và ẩm."),
 ("They walked through the jungle for hours.","Họ đi bộ trong rừng rậm hàng giờ.")],
}
