# -*- coding: utf-8 -*-
TOPIC = 4  # Work & School — Công việc & trường học
DATA = {
"meeting": [("The meeting starts at nine.","Cuộc họp bắt đầu lúc chín giờ."),
 ("We have a meeting every Monday.","Chúng tôi họp vào mỗi thứ Hai."),
 ("The meeting lasted three hours.","Cuộc họp kéo dài ba tiếng.")],
"deadline": [("The deadline is next Friday.","Hạn chót là thứ Sáu tới."),
 ("I always work better near a deadline.","Tôi luôn làm tốt hơn khi gần hạn chót."),
 ("We missed the deadline by one day.","Chúng tôi trễ hạn một ngày.")],
"homework": [("Finish your homework first.","Làm xong bài tập về nhà trước đã."),
 ("The teacher gave us a lot of homework.","Cô giáo cho chúng tôi rất nhiều bài tập."),
 ("He does his homework after dinner.","Cậu ấy làm bài tập sau bữa tối.")],
"colleague": [("My colleagues are very friendly.","Đồng nghiệp của tôi rất thân thiện."),
 ("I asked a colleague for help.","Tôi nhờ một đồng nghiệp giúp đỡ."),
 ("She is a colleague from another department.","Cô ấy là đồng nghiệp ở phòng khác.")],
"schedule": [("Check your schedule for tomorrow.","Kiểm tra lịch của bạn cho ngày mai."),
 ("My schedule is full this week.","Lịch của tôi kín cả tuần này."),
 ("The schedule changed at the last minute.","Lịch thay đổi vào phút chót.")],
"salary": [("She earns a good salary.","Cô ấy có mức lương tốt."),
 ("My salary is paid on the fifth.","Lương của tôi trả vào ngày mùng năm."),
 ("He asked for a higher salary.","Anh ấy đề nghị tăng lương.")],
"assignment": [("I handed in my assignment early.","Tôi nộp bài tập lớn sớm."),
 ("This assignment is due on Monday.","Bài tập này hạn nộp thứ Hai."),
 ("The assignment took me all weekend.","Bài tập lớn ngốn của tôi cả cuối tuần.")],
"promotion": [("He got a promotion last month.","Anh ấy được thăng chức tháng trước."),
 ("She deserves a promotion.","Cô ấy xứng đáng được thăng chức."),
 ("A promotion means more responsibility.","Thăng chức đồng nghĩa với trách nhiệm lớn hơn.")],
"presentation": [("She gave a great presentation.","Cô ấy có một bài thuyết trình rất hay."),
 ("I am nervous about my presentation.","Tôi hồi hộp về bài thuyết trình của mình."),
 ("The presentation lasted twenty minutes.","Bài thuyết trình kéo dài hai mươi phút.")],
"teamwork": [("Good teamwork wins games.","Tinh thần đồng đội tốt sẽ thắng trận."),
 ("This project needs teamwork.","Dự án này cần làm việc nhóm."),
 ("Teamwork saved us a lot of time.","Làm việc nhóm giúp chúng tôi tiết kiệm nhiều thời gian.")],
"job": [("She found a new job.","Cô ấy tìm được công việc mới."),
 ("He lost his job last year.","Anh ấy mất việc năm ngoái."),
 ("This job pays quite well.","Công việc này lương khá tốt.")],
"work": [("I work from nine to five.","Tôi làm việc từ chín giờ đến năm giờ."),
 ("There is too much work today.","Hôm nay nhiều việc quá."),
 ("She works in a hospital.","Cô ấy làm việc ở bệnh viện.")],
"career": [("He built a successful career.","Anh ấy đã xây dựng một sự nghiệp thành công."),
 ("She changed her career at forty.","Cô ấy đổi nghề ở tuổi bốn mươi."),
 ("Teaching is a rewarding career.","Dạy học là một nghề đáng giá.")],
"boss": [("My boss is very fair.","Sếp tôi rất công bằng."),
 ("The boss wants to see you.","Sếp muốn gặp bạn."),
 ("She became the boss last year.","Cô ấy lên làm sếp từ năm ngoái.")],
"manager": [("The manager approved my leave.","Quản lý đã duyệt đơn nghỉ của tôi."),
 ("Our manager is on a business trip.","Quản lý của chúng tôi đang đi công tác."),
 ("He works as a sales manager.","Anh ấy làm quản lý kinh doanh.")],
"employee": [("The company has fifty employees.","Công ty có năm mươi nhân viên."),
 ("Every employee gets health insurance.","Mọi nhân viên đều có bảo hiểm y tế."),
 ("She is the newest employee here.","Cô ấy là nhân viên mới nhất ở đây.")],
"employer": [("My employer pays for training.","Công ty tôi trả tiền đào tạo."),
 ("A good employer listens to staff.","Người sử dụng lao động tốt biết lắng nghe nhân viên."),
 ("Her employer gave her three days off.","Chỗ làm cho cô ấy nghỉ ba ngày.")],
"staff": [("The staff here are helpful.","Nhân viên ở đây rất nhiệt tình."),
 ("We need more staff this summer.","Chúng tôi cần thêm nhân viên vào mùa hè này."),
 ("The whole staff came to the party.","Toàn thể nhân viên đến dự tiệc.")],
"interview": [("I have a job interview tomorrow.","Ngày mai tôi có buổi phỏng vấn xin việc."),
 ("The interview went very well.","Buổi phỏng vấn diễn ra rất tốt."),
 ("Dress neatly for the interview.","Hãy ăn mặc gọn gàng đi phỏng vấn.")],
"resume": [("Send your resume by email.","Gửi sơ yếu lý lịch của bạn qua email."),
 ("Keep your resume short and clear.","Hãy viết sơ yếu lý lịch ngắn gọn, rõ ràng."),
 ("She updated her resume last night.","Cô ấy cập nhật sơ yếu lý lịch tối qua.")],
"experience": [("She has five years of experience.","Cô ấy có năm năm kinh nghiệm."),
 ("No experience is needed for this job.","Công việc này không cần kinh nghiệm."),
 ("Experience matters more than degrees here.","Ở đây kinh nghiệm quan trọng hơn bằng cấp.")],
"skill": [("Communication is an important skill.","Giao tiếp là một kỹ năng quan trọng."),
 ("He learned a new skill this year.","Năm nay anh ấy học thêm một kỹ năng mới."),
 ("This job requires computer skills.","Công việc này đòi hỏi kỹ năng máy tính.")],
"task": [("This task takes about an hour.","Nhiệm vụ này mất khoảng một tiếng."),
 ("She finished every task on time.","Cô ấy hoàn thành mọi nhiệm vụ đúng hạn."),
 ("Divide the work into small tasks.","Hãy chia công việc thành các nhiệm vụ nhỏ.")],
"project": [("Our project ends in June.","Dự án của chúng tôi kết thúc vào tháng Sáu."),
 ("She is leading a new project.","Cô ấy đang dẫn dắt một dự án mới."),
 ("The project cost more than expected.","Dự án tốn kém hơn dự tính.")],
"report": [("Finish the report by Friday.","Hoàn thành báo cáo trước thứ Sáu."),
 ("He wrote a detailed report.","Anh ấy viết một bản báo cáo chi tiết."),
 ("The report is on your desk.","Bản báo cáo ở trên bàn bạn.")],
"email": [("I sent you an email.","Tôi đã gửi bạn một email."),
 ("Check your email this afternoon.","Kiểm tra email của bạn chiều nay."),
 ("She answers every email quickly.","Cô ấy trả lời email nào cũng nhanh.")],
"overtime": [("He works overtime every week.","Anh ấy làm thêm giờ mỗi tuần."),
 ("Overtime is paid double.","Làm thêm giờ được trả gấp đôi."),
 ("I do not want to work overtime tonight.","Tối nay tôi không muốn làm thêm giờ.")],
"break": [("Let us take a short break.","Chúng ta nghỉ giải lao một chút đi."),
 ("The lunch break is one hour.","Giờ nghỉ trưa kéo dài một tiếng."),
 ("She had a break between classes.","Cô ấy có giờ nghỉ giữa các tiết học.")],
"retire": [("My father retired last year.","Bố tôi nghỉ hưu năm ngoái."),
 ("She plans to retire at sixty.","Cô ấy dự định nghỉ hưu ở tuổi sáu mươi."),
 ("Many teachers retire early.","Nhiều giáo viên nghỉ hưu sớm.")],
"company": [("She works for a big company.","Cô ấy làm cho một công ty lớn."),
 ("The company opened a new office.","Công ty mở một văn phòng mới."),
 ("This company was founded in 1990.","Công ty này thành lập năm 1990.")],
"department": [("I work in the sales department.","Tôi làm ở phòng kinh doanh."),
 ("Each department has its own budget.","Mỗi phòng ban có ngân sách riêng."),
 ("She moved to another department.","Cô ấy chuyển sang phòng khác.")],
"customer": [("The customer asked for a refund.","Khách hàng yêu cầu hoàn tiền."),
 ("We have many loyal customers.","Chúng tôi có nhiều khách hàng trung thành."),
 ("The customer is always right.","Khách hàng luôn đúng.")],
"school": [("My school is near the park.","Trường tôi ở gần công viên."),
 ("School starts at seven thirty.","Trường vào học lúc bảy rưỡi."),
 ("She walks to school every day.","Cô bé đi bộ đến trường mỗi ngày.")],
"university": [("She studies at a university in Hanoi.","Cô ấy học ở một trường đại học tại Hà Nội."),
 ("The university has a large library.","Trường đại học có một thư viện lớn."),
 ("He applied to that university.","Anh ấy nộp đơn vào trường đại học đó.")],
"student": [("There are thirty students in my class.","Lớp tôi có ba mươi học sinh."),
 ("She is a hard working student.","Cô ấy là một học sinh chăm chỉ."),
 ("Students get a discount here.","Sinh viên được giảm giá ở đây.")],
"teacher": [("Our teacher explains things clearly.","Thầy giáo giảng rất dễ hiểu."),
 ("She wants to become a teacher.","Cô ấy muốn trở thành giáo viên."),
 ("The teacher praised his answer.","Thầy giáo khen câu trả lời của cậu ấy.")],
"classroom": [("The classroom is very bright.","Lớp học rất sáng sủa."),
 ("Please keep the classroom clean.","Vui lòng giữ lớp học sạch sẽ."),
 ("There are thirty desks in the classroom.","Trong lớp có ba mươi cái bàn.")],
"lesson": [("Today's lesson was interesting.","Bài học hôm nay rất thú vị."),
 ("The lesson lasts forty five minutes.","Tiết học kéo dài bốn mươi lăm phút."),
 ("I missed the lesson yesterday.","Hôm qua tôi lỡ mất tiết học.")],
"subject": [("Math is my favorite subject.","Toán là môn tôi thích nhất."),
 ("Which subject do you find hardest?","Bạn thấy môn nào khó nhất?"),
 ("She teaches two subjects.","Cô ấy dạy hai môn.")],
"exam": [("The exam starts at eight.","Kỳ thi bắt đầu lúc tám giờ."),
 ("He passed the exam easily.","Cậu ấy thi đỗ dễ dàng."),
 ("I am preparing for the final exam.","Tôi đang ôn thi cuối kỳ.")],
"test": [("We have a short test today.","Hôm nay chúng ta có bài kiểm tra ngắn."),
 ("She got full marks on the test.","Cô ấy được điểm tối đa bài kiểm tra."),
 ("The test was harder than I expected.","Bài kiểm tra khó hơn tôi tưởng.")],
"grade": [("She got a good grade.","Cô ấy được điểm cao."),
 ("My grades improved this term.","Điểm của tôi tiến bộ trong học kỳ này."),
 ("He was disappointed with his grade.","Cậu ấy thất vọng với điểm số của mình.")],
"degree": [("He has a degree in economics.","Anh ấy có bằng kinh tế."),
 ("She is studying for a master's degree.","Cô ấy đang học thạc sĩ."),
 ("A degree is not everything.","Bằng cấp không phải là tất cả.")],
"graduate": [("I will graduate next year.","Tôi sẽ tốt nghiệp vào năm sau."),
 ("She graduated with high marks.","Cô ấy tốt nghiệp với điểm cao."),
 ("Many graduates find work abroad.","Nhiều người tốt nghiệp tìm được việc ở nước ngoài.")],
"study": [("I study English every evening.","Tôi học tiếng Anh mỗi tối."),
 ("She is studying for her exam.","Cô ấy đang ôn thi."),
 ("They study together at the library.","Họ học cùng nhau ở thư viện.")],
"learn": [("Children learn very quickly.","Trẻ em học rất nhanh."),
 ("I want to learn how to swim.","Tôi muốn học bơi."),
 ("He learned Japanese in two years.","Anh ấy học tiếng Nhật trong hai năm.")],
"notebook": [("Write it in your notebook.","Hãy viết vào vở của bạn."),
 ("My notebook is almost full.","Quyển vở của tôi gần hết rồi."),
 ("She lost her notebook on the bus.","Cô ấy để quên vở trên xe buýt.")],
"pen": [("Can I borrow your pen?","Tôi mượn bút của bạn được không?"),
 ("This pen does not write well.","Cây bút này viết không ra mực."),
 ("Sign here with a blue pen.","Ký vào đây bằng bút xanh.")],
"scholarship": [("She won a full scholarship.","Cô ấy giành được học bổng toàn phần."),
 ("He applied for a scholarship abroad.","Anh ấy nộp đơn xin học bổng nước ngoài."),
 ("The scholarship covers all tuition.","Học bổng chi trả toàn bộ học phí.")],
"knowledge": [("Reading widens your knowledge.","Đọc sách mở rộng kiến thức của bạn."),
 ("His knowledge of history is impressive.","Kiến thức lịch sử của anh ấy thật ấn tượng."),
 ("Knowledge is more valuable than money.","Kiến thức quý hơn tiền bạc.")],
}
