# -*- coding: utf-8 -*-
TOPIC = 11  # Clothes — Quần áo
DATA = {
"clothes": [("I need to wash my clothes.","Tôi cần giặt quần áo."),
 ("She keeps her clothes very neat.","Cô ấy giữ quần áo rất gọn gàng."),
 ("Warm clothes are needed in winter.","Mùa đông cần quần áo ấm.")],
"shirt": [("He wears a white shirt.","Anh ấy mặc áo sơ mi trắng."),
 ("This shirt is too tight.","Chiếc áo này chật quá."),
 ("She ironed his shirt this morning.","Sáng nay cô ấy là áo cho anh.")],
"blouse": [("She bought a silk blouse.","Cô ấy mua một chiếc áo lụa."),
 ("That blouse suits you well.","Chiếc áo đó rất hợp với bạn."),
 ("The blouse has small buttons.","Chiếc áo có những chiếc cúc nhỏ.")],
"trousers": [("These trousers are too long.","Chiếc quần này dài quá."),
 ("He wears black trousers to work.","Anh ấy mặc quần đen đi làm."),
 ("The trousers need washing.","Cái quần cần giặt.")],
"jeans": [("She wears jeans every day.","Cô ấy mặc quần bò mỗi ngày."),
 ("These jeans are very comfortable.","Chiếc quần bò này rất thoải mái."),
 ("My old jeans finally tore.","Chiếc quần bò cũ của tôi rách rồi.")],
"skirt": [("Her skirt is dark blue.","Váy của cô ấy màu xanh đậm."),
 ("She wore a long skirt to the party.","Cô ấy mặc váy dài đi dự tiệc."),
 ("This skirt is too short for work.","Chiếc váy này quá ngắn để đi làm.")],
"dress": [("She bought a new dress.","Cô ấy mua một chiếc váy mới."),
 ("The dress fits her perfectly.","Chiếc váy vừa vặn với cô ấy."),
 ("That red dress is beautiful.","Chiếc váy đỏ đó rất đẹp.")],
"suit": [("He wore a suit to the interview.","Anh ấy mặc vest đi phỏng vấn."),
 ("This suit is made of wool.","Bộ vest này làm bằng len."),
 ("He bought a suit for the wedding.","Anh ấy mua một bộ vest cho đám cưới.")],
"jacket": [("Take a jacket, it is cold.","Mang áo khoác đi, trời lạnh đấy."),
 ("His jacket is hanging by the door.","Áo khoác của anh ấy treo cạnh cửa."),
 ("This jacket has deep pockets.","Chiếc áo khoác này có túi sâu.")],
"coat": [("She left her coat at home.","Cô ấy để quên áo choàng ở nhà."),
 ("A long coat keeps you warm.","Áo choàng dài giữ ấm cho bạn."),
 ("The coat is too heavy for spring.","Chiếc áo choàng quá dày cho mùa xuân.")],
"sweater": [("This sweater is very soft.","Chiếc áo len này rất mềm."),
 ("She knitted a sweater for me.","Cô ấy đan cho tôi một chiếc áo len."),
 ("Wear a sweater under your coat.","Mặc áo len bên trong áo choàng.")],
"shorts": [("He wears shorts in summer.","Mùa hè anh ấy mặc quần soóc."),
 ("These shorts are good for running.","Chiếc quần soóc này hợp để chạy bộ."),
 ("She packed two pairs of shorts.","Cô ấy xếp hai chiếc quần soóc.")],
"socks": [("My socks are wet.","Tất của tôi bị ướt."),
 ("He lost one of his socks.","Anh ấy mất một chiếc tất."),
 ("Wear warm socks in winter.","Đi tất ấm vào mùa đông.")],
"shoes": [("These shoes are too small.","Đôi giày này chật quá."),
 ("Take off your shoes at the door.","Cởi giày ở cửa nhé."),
 ("She bought running shoes yesterday.","Hôm qua cô ấy mua giày chạy bộ.")],
"boots": [("Her boots are covered in mud.","Đôi bốt của cô ấy dính đầy bùn."),
 ("Wear boots when it rains.","Đi bốt khi trời mưa."),
 ("These boots last for years.","Đôi bốt này dùng được nhiều năm.")],
"sandals": [("She wears sandals at the beach.","Cô ấy đi xăng đan ở bãi biển."),
 ("These sandals broke yesterday.","Đôi xăng đan này hỏng hôm qua."),
 ("Sandals are cool in summer.","Xăng đan mát vào mùa hè.")],
"sneakers": [("His sneakers are dirty.","Đôi giày thể thao của anh ấy bẩn."),
 ("She runs in white sneakers.","Cô ấy chạy bộ với đôi giày trắng."),
 ("These sneakers are very light.","Đôi giày thể thao này rất nhẹ.")],
"hat": [("Wear a hat in the sun.","Đội mũ khi ra nắng."),
 ("His hat blew away in the wind.","Chiếc mũ của anh ấy bay đi vì gió."),
 ("She bought a straw hat.","Cô ấy mua một chiếc mũ rơm.")],
"cap": [("He wears a cap every day.","Anh ấy đội mũ lưỡi trai mỗi ngày."),
 ("Take off your cap indoors.","Bỏ mũ ra khi vào nhà."),
 ("The cap has the team logo.","Chiếc mũ có logo của đội.")],
"scarf": [("She wrapped a scarf around her neck.","Cô ấy quàng khăn quanh cổ."),
 ("This scarf is made of silk.","Chiếc khăn này bằng lụa."),
 ("He gave her a scarf for winter.","Anh ấy tặng cô ấy một chiếc khăn cho mùa đông.")],
"gloves": [("Wear gloves, it is freezing.","Đeo găng tay đi, lạnh cóng rồi."),
 ("She lost one of her gloves.","Cô ấy làm mất một chiếc găng."),
 ("These gloves are made of leather.","Đôi găng này làm bằng da.")],
"belt": [("He tightened his belt.","Anh ấy thắt chặt dây lưng."),
 ("This belt is too long for me.","Chiếc thắt lưng này dài quá với tôi."),
 ("She bought a brown belt.","Cô ấy mua một chiếc thắt lưng nâu.")],
"tie": [("He wears a tie to the office.","Anh ấy đeo cà vạt đi làm."),
 ("That blue tie suits your shirt.","Chiếc cà vạt xanh đó hợp với áo bạn."),
 ("He loosened his tie after work.","Anh ấy nới cà vạt sau giờ làm.")],
"watch": [("My watch stopped working.","Đồng hồ của tôi ngừng chạy."),
 ("She wears a silver watch.","Cô ấy đeo một chiếc đồng hồ bạc."),
 ("This watch was a gift.","Chiếc đồng hồ này là quà tặng.")],
"ring": [("She wears a gold ring.","Cô ấy đeo nhẫn vàng."),
 ("The ring is too tight.","Chiếc nhẫn chật quá."),
 ("He gave her a ring last night.","Tối qua anh ấy tặng cô ấy một chiếc nhẫn.")],
"necklace": [("Her necklace is very pretty.","Chiếc vòng cổ của cô ấy rất đẹp."),
 ("She wore a pearl necklace.","Cô ấy đeo vòng cổ ngọc trai."),
 ("The necklace broke and fell.","Chiếc vòng cổ đứt và rơi xuống.")],
"bag": [("My bag is very heavy.","Túi của tôi rất nặng."),
 ("She left her bag on the bus.","Cô ấy để quên túi trên xe buýt."),
 ("This bag has many pockets.","Chiếc túi này có nhiều ngăn.")],
"backpack": [("He carries a black backpack.","Anh ấy đeo một chiếc ba lô đen."),
 ("Her backpack is full of books.","Ba lô của cô ấy đầy sách."),
 ("A good backpack lasts for years.","Một chiếc ba lô tốt dùng được nhiều năm.")],
"wallet": [("I left my wallet at home.","Tôi để quên ví ở nhà."),
 ("His wallet was stolen.","Ví của anh ấy bị trộm."),
 ("There is no money in my wallet.","Ví tôi hết tiền rồi.")],
"glasses": [("He cannot read without glasses.","Anh ấy không đọc được nếu không đeo kính."),
 ("Her glasses broke this morning.","Sáng nay kính của cô ấy bị gãy."),
 ("She wears glasses for driving.","Cô ấy đeo kính khi lái xe.")],
"uniform": [("Students wear a uniform.","Học sinh mặc đồng phục."),
 ("The nurse's uniform is white.","Đồng phục y tá màu trắng."),
 ("He put on his work uniform.","Anh ấy mặc đồng phục làm việc.")],
"pocket": [("The keys are in my pocket.","Chìa khoá ở trong túi tôi."),
 ("This coat has no pockets.","Chiếc áo choàng này không có túi."),
 ("He put his hands in his pockets.","Anh ấy đút tay vào túi.")],
"button": [("A button fell off my shirt.","Một chiếc cúc áo tôi bị rơi."),
 ("She sewed the button back on.","Cô ấy khâu lại chiếc cúc."),
 ("This coat has six buttons.","Chiếc áo choàng có sáu cúc.")],
"zipper": [("The zipper is stuck.","Khoá kéo bị kẹt."),
 ("My jacket zipper broke.","Khoá kéo áo khoác của tôi hỏng."),
 ("Pull the zipper up slowly.","Kéo khoá lên từ từ.")],
"size": [("What size do you wear?","Bạn mặc cỡ nào?"),
 ("This size is too big.","Cỡ này to quá."),
 ("Do you have a smaller size?","Bạn có cỡ nhỏ hơn không?")],
"wear": [("She wears a uniform to school.","Cô ấy mặc đồng phục đến trường."),
 ("What will you wear tonight?","Tối nay bạn sẽ mặc gì?"),
 ("Do not wear white to the beach.","Đừng mặc đồ trắng ra biển.")],
"fashion": [("She follows the latest fashion.","Cô ấy chạy theo thời trang mới nhất."),
 ("Fashion changes every year.","Thời trang thay đổi mỗi năm."),
 ("He works in the fashion industry.","Anh ấy làm trong ngành thời trang.")],
"cotton": [("This shirt is made of cotton.","Chiếc áo này làm bằng cotton."),
 ("Cotton is cool in hot weather.","Cotton mát khi trời nóng."),
 ("She prefers cotton to silk.","Cô ấy thích cotton hơn lụa.")],
"leather": [("He bought a leather jacket.","Anh ấy mua một chiếc áo khoác da."),
 ("Leather shoes last a long time.","Giày da bền lâu."),
 ("This bag is real leather.","Chiếc túi này là da thật.")],
"pyjamas": [("He wears warm pyjamas in winter.","Mùa đông anh ấy mặc bộ đồ ngủ ấm."),
 ("She stayed in her pyjamas all day.","Cô ấy mặc đồ ngủ cả ngày."),
 ("These pyjamas are too small now.","Bộ đồ ngủ này giờ chật rồi.")],
"swimsuit": [("Pack your swimsuit for the beach.","Nhớ mang đồ bơi ra biển."),
 ("Her swimsuit is bright blue.","Đồ bơi của cô ấy màu xanh sáng."),
 ("I forgot my swimsuit at the hotel.","Tôi để quên đồ bơi ở khách sạn.")],
"raincoat": [("Take a raincoat, it looks cloudy.","Mang áo mưa đi, trời có vẻ nhiều mây."),
 ("His raincoat is bright yellow.","Áo mưa của anh ấy màu vàng sáng."),
 ("A raincoat is useful in this season.","Áo mưa rất hữu ích mùa này.")],
"vest": [("He wore a vest under his jacket.","Anh ấy mặc áo gi lê bên trong áo khoác."),
 ("The vest keeps his chest warm.","Chiếc áo gi lê giữ ấm ngực anh ấy."),
 ("She bought a wool vest.","Cô ấy mua một chiếc áo gi lê len.")],
"sleeve": [("This shirt has short sleeves.","Chiếc áo này tay ngắn."),
 ("He rolled up his sleeves.","Anh ấy xắn tay áo lên."),
 ("The sleeve is torn.","Tay áo bị rách.")],
"collar": [("The collar of his shirt is dirty.","Cổ áo sơ mi của anh ấy bẩn."),
 ("She turned up her collar.","Cô ấy dựng cổ áo lên."),
 ("This collar is too stiff.","Cổ áo này cứng quá.")],
"heel": [("She broke the heel of her shoe.","Cô ấy gãy gót giày."),
 ("These heels hurt my feet.","Đôi giày cao gót này làm đau chân tôi."),
 ("She cannot run in high heels.","Cô ấy không chạy được với giày cao gót.")],
"slipper": [("Please wear slippers indoors.","Vui lòng đi dép trong nhà."),
 ("His slippers are by the door.","Đôi dép của anh ấy ở cạnh cửa."),
 ("These slippers are very soft.","Đôi dép này rất êm.")],
"silk": [("This silk dress is expensive.","Chiếc váy lụa này đắt."),
 ("Silk feels cool on the skin.","Lụa chạm vào da thấy mát."),
 ("She bought silk from Hoi An.","Cô ấy mua lụa ở Hội An.")],
"wool": [("A wool sweater keeps you warm.","Áo len giữ ấm cho bạn."),
 ("This blanket is pure wool.","Chiếc chăn này bằng len nguyên chất."),
 ("Wool can be itchy for some people.","Len có thể gây ngứa với một số người.")],
"jewelry": [("She keeps her jewelry in a box.","Cô ấy cất trang sức trong hộp."),
 ("He bought jewelry for his wife.","Anh ấy mua trang sức cho vợ."),
 ("Do not wear jewelry when swimming.","Đừng đeo trang sức khi bơi.")],
}
