# -*- coding: utf-8 -*-
TOPIC = 12  # Home — Nhà cửa
DATA = {
"house": [("Their house has a red roof.","Nhà họ có mái đỏ."),
 ("They bought a house last year.","Họ mua một ngôi nhà năm ngoái."),
 ("The house is empty now.","Ngôi nhà giờ trống không.")],
"home": [("I go home at six.","Tôi về nhà lúc sáu giờ."),
 ("There is no place like home.","Không đâu bằng nhà mình."),
 ("She works from home on Fridays.","Cô ấy làm việc ở nhà vào thứ Sáu.")],
"room": [("This room is very bright.","Căn phòng này rất sáng."),
 ("The house has four rooms.","Ngôi nhà có bốn phòng."),
 ("Please clean your room.","Hãy dọn phòng của con.")],
"bedroom": [("My bedroom is upstairs.","Phòng ngủ của tôi ở trên lầu."),
 ("The bedroom faces the garden.","Phòng ngủ nhìn ra vườn."),
 ("She painted her bedroom blue.","Cô ấy sơn phòng ngủ màu xanh.")],
"kitchen": [("She is cooking in the kitchen.","Cô ấy đang nấu ăn trong bếp."),
 ("The kitchen is small but tidy.","Nhà bếp nhỏ nhưng gọn gàng."),
 ("We eat breakfast in the kitchen.","Chúng tôi ăn sáng trong bếp.")],
"bathroom": [("The bathroom is on the left.","Phòng tắm ở bên trái."),
 ("Someone is in the bathroom.","Có người đang ở trong phòng tắm."),
 ("The bathroom needs cleaning.","Phòng tắm cần dọn dẹp.")],
"door": [("Please close the door.","Vui lòng đóng cửa."),
 ("Someone is knocking at the door.","Có người gõ cửa."),
 ("The door is locked.","Cửa đã khoá.")],
"window": [("Open the window for fresh air.","Mở cửa sổ cho thoáng."),
 ("The window faces the street.","Cửa sổ nhìn ra phố."),
 ("Rain came in through the window.","Mưa hắt vào qua cửa sổ.")],
"wall": [("The wall is painted white.","Bức tường được sơn trắng."),
 ("She hung a photo on the wall.","Cô ấy treo một bức ảnh lên tường."),
 ("There is a crack in the wall.","Có một vết nứt trên tường.")],
"floor": [("We live on the fifth floor.","Chúng tôi sống ở tầng năm."),
 ("The floor is wet, be careful.","Sàn ướt, cẩn thận nhé."),
 ("He sat on the floor.","Anh ấy ngồi xuống sàn.")],
"ceiling": [("The ceiling is very high.","Trần nhà rất cao."),
 ("There is a lamp on the ceiling.","Có một cái đèn trên trần."),
 ("Water is dripping from the ceiling.","Nước đang nhỏ giọt từ trần nhà.")],
"roof": [("The roof leaks when it rains.","Mái nhà dột khi trời mưa."),
 ("They fixed the roof last week.","Họ sửa mái nhà tuần trước."),
 ("Birds sit on the roof every morning.","Chim đậu trên mái mỗi sáng.")],
"stairs": [("Be careful on the stairs.","Cẩn thận khi đi cầu thang."),
 ("She ran down the stairs.","Cô ấy chạy xuống cầu thang."),
 ("The stairs are made of wood.","Cầu thang làm bằng gỗ.")],
"garden": [("They grow flowers in the garden.","Họ trồng hoa trong vườn."),
 ("The garden needs water.","Khu vườn cần tưới nước."),
 ("We had lunch in the garden.","Chúng tôi ăn trưa ngoài vườn.")],
"garage": [("The car is in the garage.","Xe ở trong nhà để xe."),
 ("The garage is full of old boxes.","Nhà để xe đầy thùng cũ."),
 ("He fixed the bike in the garage.","Anh ấy sửa xe trong nhà để xe.")],
"table": [("Put the plates on the table.","Đặt đĩa lên bàn."),
 ("The table is made of wood.","Chiếc bàn làm bằng gỗ."),
 ("We sat around the table.","Chúng tôi ngồi quanh bàn.")],
"chair": [("This chair is broken.","Cái ghế này bị hỏng."),
 ("Please take a chair.","Mời bạn ngồi ghế."),
 ("She pulled the chair closer.","Cô ấy kéo ghế lại gần.")],
"sofa": [("He fell asleep on the sofa.","Anh ấy ngủ quên trên ghế sofa."),
 ("The sofa is too big for this room.","Ghế sofa to quá so với phòng này."),
 ("We bought a new sofa.","Chúng tôi mua một bộ sofa mới.")],
"bed": [("Make your bed every morning.","Dọn giường mỗi sáng."),
 ("The bed is very comfortable.","Chiếc giường rất êm."),
 ("He lay on the bed and rested.","Anh ấy nằm lên giường nghỉ.")],
"pillow": [("This pillow is too soft.","Cái gối này mềm quá."),
 ("She hugged her pillow.","Cô ấy ôm chiếc gối."),
 ("I need another pillow.","Tôi cần thêm một cái gối.")],
"blanket": [("She needs a warm blanket.","Cô ấy cần một cái chăn ấm."),
 ("The blanket fell on the floor.","Chiếc chăn rơi xuống sàn."),
 ("He wrapped the baby in a blanket.","Anh ấy quấn em bé trong chăn.")],
"wardrobe": [("Her wardrobe is full of clothes.","Tủ quần áo của cô ấy đầy đồ."),
 ("The wardrobe does not fit here.","Cái tủ quần áo không vừa chỗ này."),
 ("He hung his suit in the wardrobe.","Anh ấy treo bộ vest vào tủ.")],
"shelf": [("The books are on the shelf.","Sách ở trên kệ."),
 ("She put the vase on a high shelf.","Cô ấy đặt bình hoa lên kệ cao."),
 ("This shelf is full already.","Cái kệ này đầy rồi.")],
"mirror": [("She looked in the mirror.","Cô ấy soi gương."),
 ("The mirror is above the sink.","Chiếc gương ở phía trên bồn rửa."),
 ("The mirror broke into pieces.","Chiếc gương vỡ tan.")],
"lamp": [("Turn on the lamp, it is dark.","Bật đèn lên, tối rồi."),
 ("The lamp is next to the bed.","Cái đèn ở cạnh giường."),
 ("This lamp gives soft light.","Cái đèn này cho ánh sáng dịu.")],
"curtain": [("Close the curtain, please.","Vui lòng kéo rèm lại."),
 ("The curtain is light blue.","Rèm cửa màu xanh nhạt."),
 ("Sunlight came through the curtain.","Nắng lọt qua tấm rèm.")],
"carpet": [("The carpet needs cleaning.","Tấm thảm cần được giặt."),
 ("She spilled tea on the carpet.","Cô ấy làm đổ trà lên thảm."),
 ("A soft carpet covers the floor.","Một tấm thảm mềm phủ kín sàn.")],
"fridge": [("Put the milk in the fridge.","Cất sữa vào tủ lạnh."),
 ("The fridge is almost empty.","Tủ lạnh gần như trống."),
 ("Our fridge stopped working.","Tủ lạnh nhà tôi hỏng rồi.")],
"stove": [("The soup is on the stove.","Nồi canh đang ở trên bếp."),
 ("Turn off the stove when you finish.","Tắt bếp khi bạn xong việc."),
 ("She cleaned the stove after cooking.","Cô ấy lau bếp sau khi nấu.")],
"oven": [("The cake is in the oven.","Chiếc bánh đang ở trong lò."),
 ("Preheat the oven first.","Làm nóng lò trước."),
 ("Our oven is very old.","Cái lò nhà tôi rất cũ.")],
"sink": [("The dishes are in the sink.","Bát đĩa ở trong bồn rửa."),
 ("The sink is blocked.","Bồn rửa bị tắc."),
 ("She washed her hands in the sink.","Cô ấy rửa tay ở bồn.")],
"towel": [("Bring me a clean towel.","Lấy cho tôi một cái khăn sạch."),
 ("The towel is still wet.","Cái khăn vẫn còn ướt."),
 ("He dried his hair with a towel.","Anh ấy lau tóc bằng khăn.")],
"cupboard": [("The cups are in the cupboard.","Cốc ở trong tủ chén."),
 ("She opened the cupboard door.","Cô ấy mở cánh tủ chén."),
 ("The cupboard is above the sink.","Tủ chén ở phía trên bồn rửa.")],
"drawer": [("The keys are in the top drawer.","Chìa khoá ở ngăn kéo trên cùng."),
 ("This drawer will not open.","Ngăn kéo này không mở được."),
 ("He put the letter in a drawer.","Anh ấy cất lá thư vào ngăn kéo.")],
"key": [("I lost my house key.","Tôi làm mất chìa khoá nhà."),
 ("The key does not fit this lock.","Chìa khoá không vừa ổ khoá này."),
 ("She gave me a spare key.","Cô ấy đưa tôi một chìa dự phòng.")],
"furniture": [("The furniture is all new.","Đồ nội thất đều mới."),
 ("We moved the furniture yesterday.","Hôm qua chúng tôi chuyển đồ đạc."),
 ("This furniture is made of wood.","Bộ nội thất này làm bằng gỗ.")],
"tidy": [("Her room is always tidy.","Phòng cô ấy lúc nào cũng gọn gàng."),
 ("Please tidy the living room.","Hãy dọn gọn phòng khách."),
 ("He keeps his desk tidy.","Anh ấy giữ bàn làm việc gọn gàng.")],
"messy": [("His room is very messy.","Phòng cậu ấy rất bừa bộn."),
 ("The kitchen was messy after the party.","Nhà bếp bừa bộn sau bữa tiệc."),
 ("Do not leave the table messy.","Đừng để bàn bừa bộn.")],
"rent": [("The rent is due on the first.","Tiền thuê nhà đến hạn vào ngày mùng một."),
 ("They rent a house near the school.","Họ thuê một ngôi nhà gần trường."),
 ("The rent went up this year.","Tiền thuê tăng trong năm nay.")],
"neighborly": [("That was a neighborly thing to do.","Đó là một hành động đầy tình làng nghĩa xóm."),
 ("They are always neighborly and kind.","Họ luôn thân thiện như hàng xóm tốt."),
 ("A neighborly greeting starts the day well.","Một lời chào hàng xóm mở đầu ngày mới thật tốt.")],
"living room": [("We watch TV in the living room.","Chúng tôi xem tivi ở phòng khách."),
 ("The living room gets sun all morning.","Phòng khách có nắng suốt buổi sáng."),
 ("Guests wait in the living room.","Khách ngồi đợi ở phòng khách.")],
"dining room": [("Dinner is served in the dining room.","Bữa tối được dọn ở phòng ăn."),
 ("The dining room has a long table.","Phòng ăn có một cái bàn dài."),
 ("We rarely use the dining room.","Chúng tôi ít khi dùng phòng ăn.")],
"balcony": [("She grows herbs on the balcony.","Cô ấy trồng rau thơm trên ban công."),
 ("The balcony looks over the street.","Ban công nhìn xuống phố."),
 ("We drink coffee on the balcony.","Chúng tôi uống cà phê ngoài ban công.")],
"basement": [("We store old boxes in the basement.","Chúng tôi để thùng cũ dưới tầng hầm."),
 ("The basement is cold and dark.","Tầng hầm lạnh và tối."),
 ("Water leaked into the basement.","Nước rò vào tầng hầm.")],
"attic": [("The attic is full of dust.","Gác mái đầy bụi."),
 ("They found old photos in the attic.","Họ tìm thấy ảnh cũ trên gác mái."),
 ("The attic is used for storage.","Gác mái dùng để chứa đồ.")],
"doorbell": [("Someone is ringing the doorbell.","Có người đang bấm chuông cửa."),
 ("The doorbell is broken.","Chuông cửa bị hỏng."),
 ("I did not hear the doorbell.","Tôi không nghe thấy chuông cửa.")],
"fence": [("A wooden fence surrounds the garden.","Một hàng rào gỗ bao quanh khu vườn."),
 ("The fence needs painting.","Hàng rào cần sơn lại."),
 ("The dog jumped over the fence.","Con chó nhảy qua hàng rào.")],
"yard": [("The children play in the yard.","Bọn trẻ chơi ngoài sân."),
 ("He parked his bike in the yard.","Anh ấy để xe đạp ngoài sân."),
 ("The yard is covered with leaves.","Sân phủ đầy lá.")],
"washing machine": [("The washing machine is broken.","Máy giặt bị hỏng."),
 ("Put the clothes in the washing machine.","Bỏ quần áo vào máy giặt."),
 ("Our washing machine is very quiet.","Máy giặt nhà tôi rất êm.")],
"air conditioner": [("Turn on the air conditioner, please.","Vui lòng bật máy điều hoà."),
 ("The air conditioner uses a lot of power.","Máy điều hoà tốn nhiều điện."),
 ("Our air conditioner needs cleaning.","Máy điều hoà nhà tôi cần vệ sinh.")],
}
