# -*- coding: utf-8 -*-
TOPIC = 6  # Health — Sức khoẻ
DATA = {
"healthy": [("Stay healthy by exercising.","Hãy giữ sức khoẻ bằng cách tập thể dục."),
 ("She eats very healthy food.","Cô ấy ăn rất lành mạnh."),
 ("My grandfather is still healthy at eighty.","Ông tôi tám mươi vẫn còn khoẻ.")],
"exercise": [("Daily exercise is important.","Tập thể dục hằng ngày rất quan trọng."),
 ("He exercises before breakfast.","Anh ấy tập thể dục trước bữa sáng."),
 ("This exercise is good for your back.","Bài tập này tốt cho lưng.")],
"medicine": [("Take this medicine after meals.","Uống thuốc này sau bữa ăn."),
 ("The medicine tastes bitter.","Thuốc có vị đắng."),
 ("Keep medicine away from children.","Để thuốc xa tầm tay trẻ em.")],
"headache": [("I have a bad headache.","Tôi bị đau đầu nặng."),
 ("Loud noise gives me a headache.","Tiếng ồn làm tôi đau đầu."),
 ("Her headache lasted all day.","Cơn đau đầu của cô ấy kéo dài cả ngày.")],
"fever": [("The child has a fever.","Đứa bé bị sốt."),
 ("His fever went down last night.","Cơn sốt của anh ấy đã hạ tối qua."),
 ("Call the doctor if the fever continues.","Gọi bác sĩ nếu vẫn còn sốt.")],
"recover": [("She recovered quickly.","Cô ấy hồi phục nhanh."),
 ("It took him a month to recover.","Anh ấy mất một tháng để hồi phục."),
 ("Rest well and you will recover.","Nghỉ ngơi tốt thì bạn sẽ khoẻ lại.")],
"appointment": [("I have a doctor's appointment.","Tôi có hẹn khám bác sĩ."),
 ("She cancelled her appointment.","Cô ấy huỷ lịch hẹn."),
 ("Make an appointment before you come.","Hãy đặt lịch hẹn trước khi đến.")],
"symptom": [("A cough is a common symptom.","Ho là một triệu chứng thường gặp."),
 ("Tell the doctor all your symptoms.","Hãy kể cho bác sĩ mọi triệu chứng của bạn."),
 ("The symptoms appeared two days ago.","Các triệu chứng xuất hiện hai ngày trước.")],
"breathe": [("Breathe slowly and relax.","Hãy thở chậm và thư giãn."),
 ("It is hard to breathe in this smoke.","Khó thở trong làn khói này."),
 ("She could not breathe through her nose.","Cô ấy không thở được bằng mũi.")],
"injury": [("He has a knee injury.","Anh ấy bị chấn thương đầu gối."),
 ("The injury kept her out for a month.","Chấn thương khiến cô ấy nghỉ một tháng."),
 ("It was a serious injury.","Đó là một chấn thương nghiêm trọng.")],
"doctor": [("The doctor will see you now.","Bác sĩ sẽ khám cho bạn bây giờ."),
 ("She wants to become a doctor.","Cô ấy muốn trở thành bác sĩ."),
 ("The doctor told me to rest.","Bác sĩ bảo tôi nghỉ ngơi.")],
"nurse": [("The nurse checked my temperature.","Y tá đo nhiệt độ cho tôi."),
 ("A nurse works long hours.","Y tá làm việc nhiều giờ liền."),
 ("The nurse was very gentle.","Cô y tá rất nhẹ nhàng.")],
"dentist": [("I visit the dentist twice a year.","Tôi đi khám nha sĩ hai lần một năm."),
 ("The dentist pulled out my tooth.","Nha sĩ nhổ răng cho tôi."),
 ("Children are often afraid of the dentist.","Trẻ con thường sợ nha sĩ.")],
"clinic": [("There is a clinic near my house.","Có một phòng khám gần nhà tôi."),
 ("The clinic opens at seven.","Phòng khám mở cửa lúc bảy giờ."),
 ("She works at a small clinic.","Cô ấy làm ở một phòng khám nhỏ.")],
"illness": [("He missed work due to illness.","Anh ấy nghỉ làm vì ốm."),
 ("Her illness lasted two weeks.","Bệnh của cô ấy kéo dài hai tuần."),
 ("Stress can cause illness.","Căng thẳng có thể gây bệnh.")],
"disease": [("This disease spreads quickly.","Căn bệnh này lây lan nhanh."),
 ("Heart disease is common in older people.","Bệnh tim thường gặp ở người lớn tuổi."),
 ("The disease can be treated early.","Bệnh có thể chữa được nếu phát hiện sớm.")],
"pain": [("I feel a sharp pain here.","Tôi thấy đau nhói ở đây."),
 ("The pain went away after an hour.","Cơn đau biến mất sau một tiếng."),
 ("She is in a lot of pain.","Cô ấy đang rất đau.")],
"cough": [("She has a bad cough.","Cô ấy ho nặng."),
 ("This syrup helps with a cough.","Loại si rô này giúp giảm ho."),
 ("He coughs all night.","Anh ấy ho suốt đêm.")],
"sneeze": [("Cover your mouth when you sneeze.","Che miệng khi bạn hắt hơi."),
 ("Dust makes me sneeze.","Bụi làm tôi hắt hơi."),
 ("She let out a loud sneeze.","Cô ấy hắt hơi một cái rõ to.")],
"cold": [("I caught a cold last week.","Tuần trước tôi bị cảm."),
 ("A cold usually lasts a few days.","Cảm lạnh thường kéo dài vài ngày."),
 ("Drink hot tea when you have a cold.","Uống trà nóng khi bị cảm.")],
"flu": [("The flu kept him in bed.","Cúm khiến anh ấy nằm bẹp trên giường."),
 ("Many students got the flu.","Nhiều học sinh bị cúm."),
 ("A flu shot can protect you.","Tiêm phòng cúm có thể bảo vệ bạn.")],
"sore throat": [("I have a sore throat today.","Hôm nay tôi bị đau họng."),
 ("Honey helps a sore throat.","Mật ong giúp giảm đau họng."),
 ("A sore throat is the first sign.","Đau họng là dấu hiệu đầu tiên.")],
"stomachache": [("He had a stomachache all night.","Anh ấy đau bụng suốt đêm."),
 ("Too much candy gives you a stomachache.","Ăn nhiều kẹo quá sẽ đau bụng."),
 ("Her stomachache went away after lunch.","Cơn đau bụng của cô ấy hết sau bữa trưa.")],
"toothache": [("A toothache kept me awake.","Cơn đau răng làm tôi mất ngủ."),
 ("See a dentist about that toothache.","Đi khám nha sĩ về cơn đau răng đó."),
 ("Sweet food makes my toothache worse.","Đồ ngọt làm răng tôi đau hơn.")],
"allergy": [("She has an allergy to nuts.","Cô ấy bị dị ứng với các loại hạt."),
 ("My allergy gets worse in spring.","Dị ứng của tôi nặng hơn vào mùa xuân."),
 ("Do you have any food allergy?","Bạn có dị ứng thức ăn nào không?")],
"infection": [("The wound got an infection.","Vết thương bị nhiễm trùng."),
 ("Antibiotics treat this infection.","Kháng sinh chữa được loại nhiễm trùng này."),
 ("Wash your hands to prevent infection.","Rửa tay để phòng nhiễm trùng.")],
"virus": [("A virus caused the outbreak.","Một loại vi rút gây ra đợt bùng phát."),
 ("This virus spreads through the air.","Vi rút này lây qua không khí."),
 ("The virus is not dangerous.","Loại vi rút này không nguy hiểm.")],
"vaccine": [("The vaccine is free for children.","Vắc xin miễn phí cho trẻ em."),
 ("She got her second vaccine yesterday.","Cô ấy tiêm mũi vắc xin thứ hai hôm qua."),
 ("The vaccine took years to develop.","Vắc xin mất nhiều năm để phát triển.")],
"pill": [("Take one pill after meals.","Uống một viên sau bữa ăn."),
 ("This pill is very small.","Viên thuốc này rất nhỏ."),
 ("He forgot to take his pills.","Anh ấy quên uống thuốc.")],
"prescription": [("The doctor wrote a prescription.","Bác sĩ viết đơn thuốc."),
 ("You need a prescription for this medicine.","Bạn cần đơn thuốc để mua loại thuốc này."),
 ("I lost my prescription.","Tôi làm mất đơn thuốc rồi.")],
"treatment": [("The treatment lasts three weeks.","Đợt điều trị kéo dài ba tuần."),
 ("This treatment is very expensive.","Phương pháp điều trị này rất đắt."),
 ("Early treatment gives better results.","Điều trị sớm cho kết quả tốt hơn.")],
"surgery": [("He needs surgery on his knee.","Anh ấy cần phẫu thuật đầu gối."),
 ("The surgery took four hours.","Ca phẫu thuật kéo dài bốn tiếng."),
 ("She recovered well after surgery.","Cô ấy hồi phục tốt sau phẫu thuật.")],
"ambulance": [("Call an ambulance immediately.","Gọi xe cứu thương ngay."),
 ("The ambulance arrived in ten minutes.","Xe cứu thương đến sau mười phút."),
 ("An ambulance rushed him to hospital.","Xe cứu thương đưa anh ấy vào viện gấp.")],
"emergency": [("This is an emergency.","Đây là trường hợp khẩn cấp."),
 ("Go to the emergency room.","Hãy đến phòng cấp cứu."),
 ("Keep this number for an emergency.","Giữ số này để dùng khi khẩn cấp.")],
"blood": [("He donates blood every year.","Anh ấy hiến máu mỗi năm."),
 ("The nurse took a blood sample.","Y tá lấy mẫu máu."),
 ("My blood pressure is normal.","Huyết áp của tôi bình thường.")],
"heart": [("Running is good for your heart.","Chạy bộ tốt cho tim."),
 ("His heart beats too fast.","Tim anh ấy đập quá nhanh."),
 ("She has a weak heart.","Cô ấy bị tim yếu.")],
"lung": [("Smoking damages your lungs.","Hút thuốc làm hại phổi."),
 ("He has a lung problem.","Anh ấy có vấn đề về phổi."),
 ("Deep breathing fills the lungs.","Hít sâu làm phổi đầy khí.")],
"bone": [("He broke a bone in his arm.","Anh ấy bị gãy xương tay."),
 ("Milk makes your bones strong.","Sữa giúp xương chắc khoẻ."),
 ("The bone healed in six weeks.","Xương lành sau sáu tuần.")],
"muscle": [("My muscles ache after the gym.","Cơ bắp tôi đau nhức sau khi tập."),
 ("Swimming builds strong muscles.","Bơi lội giúp cơ bắp săn chắc."),
 ("He pulled a muscle while running.","Anh ấy bị căng cơ khi chạy.")],
"stomach": [("Do not swim on a full stomach.","Đừng bơi khi vừa ăn no."),
 ("My stomach hurts.","Bụng tôi đau."),
 ("Ginger is good for the stomach.","Gừng tốt cho dạ dày.")],
"diet": [("A balanced diet keeps you strong.","Chế độ ăn cân bằng giúp bạn khoẻ."),
 ("She is on a strict diet.","Cô ấy đang ăn kiêng nghiêm ngặt."),
 ("Your diet affects your health.","Chế độ ăn ảnh hưởng tới sức khoẻ.")],
"nutrition": [("Good nutrition matters for children.","Dinh dưỡng tốt rất quan trọng với trẻ em."),
 ("She studies nutrition at university.","Cô ấy học dinh dưỡng ở đại học."),
 ("Poor nutrition causes many problems.","Dinh dưỡng kém gây ra nhiều vấn đề.")],
"vitamin": [("Oranges are rich in vitamin C.","Cam giàu vitamin C."),
 ("She takes a vitamin every morning.","Cô ấy uống vitamin mỗi sáng."),
 ("Sunlight gives you vitamin D.","Ánh nắng cho bạn vitamin D.")],
"sleep": [("Adults need eight hours of sleep.","Người lớn cần ngủ tám tiếng."),
 ("I could not sleep last night.","Tối qua tôi không ngủ được."),
 ("Good sleep improves your memory.","Ngủ ngon cải thiện trí nhớ.")],
"fitness": [("Swimming improves your fitness.","Bơi lội cải thiện thể lực."),
 ("He goes to a fitness class.","Anh ấy đi học lớp thể hình."),
 ("Her fitness improved in three months.","Thể lực của cô ấy tiến bộ sau ba tháng.")],
"dizzy": [("I felt dizzy after standing up.","Tôi thấy chóng mặt sau khi đứng dậy."),
 ("She gets dizzy on boats.","Cô ấy bị chóng mặt khi đi thuyền."),
 ("Sit down if you feel dizzy.","Hãy ngồi xuống nếu bạn thấy chóng mặt.")],
"wound": [("Clean the wound with water.","Rửa vết thương bằng nước."),
 ("The wound is healing well.","Vết thương đang lành tốt."),
 ("He had a deep wound on his leg.","Anh ấy có một vết thương sâu ở chân.")],
"bandage": [("The nurse put on a bandage.","Y tá băng lại vết thương."),
 ("Change the bandage every day.","Thay băng mỗi ngày."),
 ("The bandage is too tight.","Băng quấn chặt quá.")],
"checkup": [("I have a checkup every year.","Tôi khám sức khoẻ định kỳ mỗi năm."),
 ("The checkup showed no problems.","Kết quả khám không có vấn đề gì."),
 ("Book a checkup before you travel.","Đặt lịch khám trước khi bạn đi xa.")],
"hygiene": [("Good hygiene prevents disease.","Vệ sinh tốt phòng ngừa bệnh tật."),
 ("Hand hygiene is very important.","Vệ sinh tay rất quan trọng."),
 ("The restaurant has poor hygiene.","Nhà hàng đó vệ sinh kém.")],
}
