# -*- coding: utf-8 -*-
TOPIC = 5  # Family — Gia đình
DATA = {
"parents": [("My parents live in Hue.","Bố mẹ tôi sống ở Huế."),
 ("Her parents are both teachers.","Bố mẹ cô ấy đều là giáo viên."),
 ("I visit my parents every month.","Tôi về thăm bố mẹ mỗi tháng.")],
"sibling": [("Do you have any siblings?","Bạn có anh chị em ruột nào không?"),
 ("She has three siblings.","Cô ấy có ba anh chị em."),
 ("Siblings often argue when they are young.","Anh chị em hay cãi nhau khi còn nhỏ.")],
"relative": [("We visit our relatives at Tet.","Chúng tôi thăm họ hàng vào dịp Tết."),
 ("All my relatives live nearby.","Họ hàng tôi đều sống gần đây."),
 ("She is a distant relative of mine.","Cô ấy là họ hàng xa của tôi.")],
"neighbor": [("Our neighbor is very kind.","Hàng xóm của chúng tôi rất tốt bụng."),
 ("The neighbors invited us for dinner.","Hàng xóm mời chúng tôi ăn tối."),
 ("I borrowed a ladder from my neighbor.","Tôi mượn thang của hàng xóm.")],
"friendly": [("The staff here are friendly.","Nhân viên ở đây rất thân thiện."),
 ("She has a friendly smile.","Cô ấy có nụ cười thân thiện."),
 ("Our new neighbor seems friendly.","Người hàng xóm mới có vẻ thân thiện.")],
"honest": [("He is an honest person.","Anh ấy là người trung thực."),
 ("Please give me an honest answer.","Hãy cho tôi một câu trả lời thật lòng."),
 ("Being honest is not always easy.","Sống trung thực không phải lúc nào cũng dễ.")],
"generous": [("She is generous with her time.","Cô ấy rất hào phóng về thời gian."),
 ("That was a generous gift.","Đó là một món quà hào phóng."),
 ("He is generous to everyone.","Anh ấy hào phóng với tất cả mọi người.")],
"grandparents": [("My grandparents tell great stories.","Ông bà tôi kể chuyện rất hay."),
 ("We stay with our grandparents in summer.","Mùa hè chúng tôi ở với ông bà."),
 ("Her grandparents live in the countryside.","Ông bà cô ấy sống ở quê.")],
"couple": [("They are a lovely couple.","Họ là một cặp đôi đáng yêu."),
 ("The couple has been married ten years.","Cặp vợ chồng đó cưới nhau mười năm rồi."),
 ("A young couple moved in next door.","Một cặp vợ chồng trẻ dọn đến nhà bên.")],
"stranger": [("Don't talk to strangers.","Đừng nói chuyện với người lạ."),
 ("A stranger helped me find the way.","Một người lạ đã giúp tôi tìm đường."),
 ("He is no longer a stranger to us.","Anh ấy không còn là người lạ với chúng tôi nữa.")],
"family": [("My family has five people.","Gia đình tôi có năm người."),
 ("Family always comes first.","Gia đình luôn là trên hết."),
 ("We eat dinner as a family.","Cả nhà chúng tôi ăn tối cùng nhau.")],
"father": [("My father works in a factory.","Bố tôi làm ở nhà máy."),
 ("Her father taught her to drive.","Bố cô ấy dạy cô ấy lái xe."),
 ("He became a father last month.","Anh ấy làm bố từ tháng trước.")],
"mother": [("My mother cooks very well.","Mẹ tôi nấu ăn rất ngon."),
 ("She looks just like her mother.","Cô ấy giống mẹ như đúc."),
 ("His mother is a nurse.","Mẹ anh ấy là y tá.")],
"dad": [("My dad taught me to swim.","Bố tôi dạy tôi bơi."),
 ("Dad is fixing the bicycle.","Bố đang sửa xe đạp."),
 ("I call my dad every Sunday.","Tôi gọi cho bố mỗi Chủ nhật.")],
"mom": [("Mom is in the kitchen.","Mẹ đang ở trong bếp."),
 ("My mom makes the best soup.","Mẹ tôi nấu canh ngon nhất."),
 ("She looks after her mom.","Cô ấy chăm sóc mẹ mình.")],
"son": [("Their son is ten years old.","Con trai họ mười tuổi."),
 ("He is very proud of his son.","Anh ấy rất tự hào về con trai."),
 ("Their son just started school.","Con trai họ vừa vào lớp một.")],
"daughter": [("My daughter loves drawing.","Con gái tôi thích vẽ."),
 ("Their daughter studies abroad.","Con gái họ du học nước ngoài."),
 ("She has one son and one daughter.","Cô ấy có một trai một gái.")],
"brother": [("My brother studies in Da Nang.","Anh trai tôi học ở Đà Nẵng."),
 ("He is my younger brother.","Cậu ấy là em trai tôi."),
 ("My brother and I look alike.","Tôi và anh trai giống nhau.")],
"sister": [("I have one older sister.","Tôi có một chị gái."),
 ("Her sister is getting married.","Chị cô ấy sắp cưới."),
 ("My sister lives in the same city.","Chị tôi sống cùng thành phố.")],
"grandfather": [("My grandfather is eighty.","Ông tôi tám mươi tuổi."),
 ("Grandfather drinks tea every morning.","Ông uống trà mỗi sáng."),
 ("He learned chess from his grandfather.","Cậu ấy học cờ từ ông nội.")],
"grandmother": [("My grandmother tells great stories.","Bà tôi kể chuyện rất hay."),
 ("Grandmother made these cakes.","Bà làm mấy cái bánh này."),
 ("Her grandmother is ninety years old.","Bà cô ấy chín mươi tuổi.")],
"grandson": [("She visits her grandson often.","Bà thường xuyên đến thăm cháu trai."),
 ("Their grandson just turned six.","Cháu trai họ vừa tròn sáu tuổi."),
 ("He is the youngest grandson.","Cậu ấy là cháu trai út.")],
"granddaughter": [("Their granddaughter just turned five.","Cháu gái họ vừa tròn năm tuổi."),
 ("She bought a doll for her granddaughter.","Bà mua búp bê cho cháu gái."),
 ("Their granddaughter lives with them.","Cháu gái sống cùng ông bà.")],
"uncle": [("My uncle lives in Hue.","Chú tôi sống ở Huế."),
 ("Uncle brought us fruit from his garden.","Chú mang cho chúng tôi trái cây trong vườn."),
 ("His uncle is a doctor.","Chú anh ấy là bác sĩ.")],
"aunt": [("My aunt makes delicious cakes.","Cô tôi làm bánh rất ngon."),
 ("We stayed at my aunt's house.","Chúng tôi ở nhà cô tôi."),
 ("Her aunt lives in Australia.","Dì cô ấy sống ở Úc.")],
"cousin": [("My cousin studies medicine.","Anh họ tôi học y."),
 ("I have many cousins.","Tôi có nhiều anh chị em họ."),
 ("She is my cousin on my mother's side.","Cô ấy là em họ bên ngoại của tôi.")],
"nephew": [("I bought my nephew a toy.","Tôi mua cho cháu trai một món đồ chơi."),
 ("Her nephew is very naughty.","Cháu trai cô ấy nghịch lắm."),
 ("My nephew starts school this year.","Cháu trai tôi năm nay vào lớp một.")],
"niece": [("My niece is very shy.","Cháu gái tôi rất nhút nhát."),
 ("His niece won a singing contest.","Cháu gái anh ấy thắng cuộc thi hát."),
 ("I take my niece to the park.","Tôi dẫn cháu gái ra công viên.")],
"husband": [("Her husband is a teacher.","Chồng cô ấy là giáo viên."),
 ("My husband cooks on weekends.","Chồng tôi nấu ăn vào cuối tuần."),
 ("She met her husband at work.","Cô ấy gặp chồng mình ở chỗ làm.")],
"wife": [("His wife works at a bank.","Vợ anh ấy làm ở ngân hàng."),
 ("He bought flowers for his wife.","Anh ấy mua hoa tặng vợ."),
 ("My wife and I travel a lot.","Tôi và vợ đi du lịch nhiều.")],
"marry": [("They will marry in October.","Họ sẽ cưới vào tháng Mười."),
 ("She did not want to marry young.","Cô ấy không muốn lấy chồng sớm."),
 ("He asked her to marry him.","Anh ấy cầu hôn cô ấy.")],
"wedding": [("The wedding is in October.","Đám cưới tổ chức vào tháng Mười."),
 ("We danced all night at the wedding.","Chúng tôi nhảy suốt đêm ở đám cưới."),
 ("Their wedding was very simple.","Đám cưới của họ rất giản dị.")],
"divorce": [("They divorced two years ago.","Họ ly hôn hai năm trước."),
 ("Divorce is never easy for children.","Ly hôn không bao giờ dễ dàng với trẻ con."),
 ("She filed for divorce last month.","Cô ấy nộp đơn ly hôn tháng trước.")],
"engaged": [("My sister got engaged.","Chị tôi đã đính hôn."),
 ("They have been engaged for a year.","Họ đính hôn được một năm rồi."),
 ("She is engaged to a doctor.","Cô ấy đính hôn với một bác sĩ.")],
"pregnant": [("She is six months pregnant.","Cô ấy mang thai sáu tháng."),
 ("Pregnant women need extra rest.","Phụ nữ mang thai cần nghỉ ngơi nhiều hơn."),
 ("My sister is pregnant again.","Chị tôi lại mang thai.")],
"raise": [("They raised four children.","Họ nuôi bốn người con."),
 ("It is hard to raise a child alone.","Nuôi con một mình rất vất vả."),
 ("My grandparents raised me.","Ông bà đã nuôi tôi lớn.")],
"childhood": [("He had a happy childhood.","Anh ấy có một tuổi thơ hạnh phúc."),
 ("I spent my childhood in the countryside.","Tôi lớn lên ở vùng quê."),
 ("She still keeps her childhood toys.","Cô ấy vẫn giữ đồ chơi hồi bé.")],
"adopt": [("They adopted a little boy.","Họ nhận nuôi một cậu bé."),
 ("She was adopted as a baby.","Cô ấy được nhận nuôi từ khi còn bé."),
 ("Many families adopt children each year.","Nhiều gia đình nhận con nuôi mỗi năm.")],
"in-laws": [("We visit my in-laws at Tet.","Chúng tôi thăm bên nhà chồng vào dịp Tết."),
 ("My in-laws live very close to us.","Nhà chồng tôi ở rất gần."),
 ("Her in-laws are very kind.","Bên nhà chồng cô ấy rất tử tế.")],
"mother-in-law": [("My mother-in-law is very kind.","Mẹ chồng tôi rất tốt bụng."),
 ("His mother-in-law cooks for the family.","Mẹ vợ anh ấy nấu ăn cho cả nhà."),
 ("She gets along well with her mother-in-law.","Cô ấy hợp với mẹ chồng.")],
"household": [("Our household has six members.","Hộ gia đình chúng tôi có sáu người."),
 ("She manages the household budget.","Cô ấy quản lý chi tiêu gia đình."),
 ("Every household received a letter.","Mỗi hộ gia đình đều nhận được một lá thư.")],
"ancestor": [("We honor our ancestors.","Chúng tôi thờ cúng tổ tiên."),
 ("His ancestors came from the north.","Tổ tiên anh ấy đến từ miền Bắc."),
 ("Our ancestors built this temple.","Tổ tiên chúng tôi xây ngôi đền này.")],
"generation": [("Three generations live together.","Ba thế hệ sống chung một nhà."),
 ("The younger generation thinks differently.","Thế hệ trẻ nghĩ khác."),
 ("This recipe passed down three generations.","Công thức này truyền qua ba đời.")],
"close": [("I am very close to my sister.","Tôi rất thân với chị gái."),
 ("They have stayed close since childhood.","Họ thân nhau từ nhỏ tới giờ."),
 ("We are a close family.","Nhà tôi là một gia đình gắn bó.")],
"support": [("My family supports my decision.","Gia đình ủng hộ quyết định của tôi."),
 ("She supported him through hard times.","Cô ấy ở bên anh ấy qua lúc khó khăn."),
 ("Thank you for your support.","Cảm ơn sự ủng hộ của bạn.")],
"care": [("She cares for her old parents.","Cô ấy chăm sóc bố mẹ già."),
 ("Take care of yourself.","Hãy giữ gìn sức khoẻ nhé."),
 ("He does not care what others think.","Anh ấy không quan tâm người khác nghĩ gì.")],
"trust": [("I trust my brother completely.","Tôi hoàn toàn tin tưởng anh trai."),
 ("Trust takes years to build.","Niềm tin cần nhiều năm để xây dựng."),
 ("She lost his trust.","Cô ấy đánh mất niềm tin của anh ấy.")],
"respect": [("Children should respect their elders.","Trẻ em nên tôn trọng người lớn tuổi."),
 ("He has great respect for his teacher.","Anh ấy rất kính trọng thầy giáo."),
 ("Respect is earned, not given.","Sự tôn trọng phải giành lấy, không phải được cho.")],
"friend": [("She is my best friend.","Cô ấy là bạn thân nhất của tôi."),
 ("I made new friends at work.","Tôi có thêm bạn mới ở chỗ làm."),
 ("A true friend helps you in trouble.","Bạn thật sự là người giúp bạn lúc khó khăn.")],
"friendship": [("Their friendship began at school.","Tình bạn của họ bắt đầu từ thời đi học."),
 ("Friendship needs time and care.","Tình bạn cần thời gian và sự vun đắp."),
 ("Their friendship lasted forty years.","Tình bạn của họ kéo dài bốn mươi năm.")],
}
