# -*- coding: utf-8 -*-
TOPIC = 2  # Food — Đồ ăn & thức uống
DATA = {
"meal": [("Dinner is my favorite meal.","Bữa tối là bữa tôi thích nhất."),
 ("She cooks three meals a day.","Cô ấy nấu ba bữa mỗi ngày."),
 ("Take this medicine after each meal.","Uống thuốc này sau mỗi bữa ăn.")],
"vegetable": [("Eat more vegetables every day.","Hãy ăn nhiều rau hơn mỗi ngày."),
 ("She grows vegetables in her garden.","Cô ấy trồng rau trong vườn."),
 ("This vegetable soup is very light.","Món canh rau này rất thanh.")],
"delicious": [("This soup is delicious.","Món canh này rất ngon."),
 ("What a delicious cake!","Bánh ngon quá!"),
 ("The food smells delicious.","Đồ ăn thơm quá.")],
"recipe": [("I found a simple recipe online.","Tôi tìm được một công thức đơn giản trên mạng."),
 ("This recipe needs only five ingredients.","Công thức này chỉ cần năm nguyên liệu."),
 ("My grandmother gave me her recipe.","Bà tôi cho tôi công thức của bà.")],
"taste": [("The cake tastes sweet.","Cái bánh có vị ngọt."),
 ("Can I taste the soup?","Tôi nếm thử canh được không?"),
 ("This tea has a strange taste.","Trà này có vị lạ.")],
"order": [("Let us order some noodles.","Chúng ta gọi mì đi."),
 ("She ordered fish for dinner.","Cô ấy gọi món cá cho bữa tối."),
 ("Our order has not arrived yet.","Món chúng tôi gọi vẫn chưa ra.")],
"spicy": [("I love spicy food.","Tôi thích đồ ăn cay."),
 ("This sauce is too spicy for me.","Nước sốt này cay quá với tôi."),
 ("Is the soup spicy?","Món canh có cay không?")],
"ingredient": [("Salt is a common ingredient.","Muối là một nguyên liệu thông dụng."),
 ("Mix all the ingredients in a bowl.","Trộn tất cả nguyên liệu vào một cái bát."),
 ("Fresh ingredients make better food.","Nguyên liệu tươi làm món ăn ngon hơn.")],
"beverage": [("They serve hot beverages here.","Ở đây có phục vụ đồ uống nóng."),
 ("No beverages are allowed inside.","Không được mang đồ uống vào trong."),
 ("Water is the healthiest beverage.","Nước lọc là thức uống lành mạnh nhất.")],
"leftover": [("We had leftovers for lunch.","Chúng tôi ăn đồ thừa vào bữa trưa."),
 ("Put the leftovers in the fridge.","Cất đồ ăn thừa vào tủ lạnh."),
 ("There are no leftovers tonight.","Tối nay không còn đồ thừa.")],
"rice": [("We eat rice every day.","Chúng tôi ăn cơm mỗi ngày."),
 ("Vietnam exports a lot of rice.","Việt Nam xuất khẩu rất nhiều gạo."),
 ("Wash the rice before cooking.","Vo gạo trước khi nấu.")],
"bread": [("She buys fresh bread each morning.","Cô ấy mua bánh mì tươi mỗi sáng."),
 ("This bread is still warm.","Ổ bánh mì này vẫn còn ấm."),
 ("I had bread and eggs for breakfast.","Tôi ăn bánh mì với trứng vào bữa sáng.")],
"noodle": [("This noodle soup is famous here.","Món mì nước này nổi tiếng ở đây."),
 ("She ordered fried noodles.","Cô ấy gọi món mì xào."),
 ("The noodles are too soft.","Sợi mì mềm quá.")],
"soup": [("The soup is still hot.","Món canh vẫn còn nóng."),
 ("He made chicken soup for me.","Anh ấy nấu súp gà cho tôi."),
 ("This soup needs more salt.","Món canh này cần thêm muối.")],
"meat": [("He does not eat meat.","Anh ấy không ăn thịt."),
 ("Cook the meat until it is done.","Nấu thịt cho tới khi chín."),
 ("This meat is very tender.","Miếng thịt này rất mềm.")],
"beef": [("The beef is very tender.","Thịt bò rất mềm."),
 ("She ordered beef noodle soup.","Cô ấy gọi món phở bò."),
 ("Beef is more expensive than pork.","Thịt bò đắt hơn thịt lợn.")],
"pork": [("Grilled pork is my favorite.","Thịt lợn nướng là món tôi thích nhất."),
 ("This pork is a bit dry.","Miếng thịt lợn này hơi khô."),
 ("They sell fresh pork every morning.","Họ bán thịt lợn tươi mỗi sáng.")],
"seafood": [("This restaurant serves fresh seafood.","Nhà hàng này phục vụ hải sản tươi."),
 ("I am allergic to seafood.","Tôi bị dị ứng hải sản."),
 ("Seafood is cheaper near the coast.","Hải sản rẻ hơn ở gần biển.")],
"shrimp": [("I ordered fried shrimp.","Tôi gọi món tôm chiên."),
 ("These shrimp are very fresh.","Mấy con tôm này rất tươi."),
 ("She peeled the shrimp carefully.","Cô ấy bóc tôm cẩn thận.")],
"egg": [("I eat two eggs for breakfast.","Tôi ăn hai quả trứng vào bữa sáng."),
 ("Boil the egg for five minutes.","Luộc trứng năm phút."),
 ("We need eggs for this cake.","Chúng ta cần trứng cho cái bánh này.")],
"milk": [("Children should drink milk.","Trẻ em nên uống sữa."),
 ("The milk has gone bad.","Sữa hỏng rồi."),
 ("I take my coffee with milk.","Tôi uống cà phê với sữa.")],
"cheese": [("She put cheese on the bread.","Cô ấy phết phô mai lên bánh mì."),
 ("This cheese smells strong.","Loại phô mai này mùi nồng."),
 ("He does not like cheese.","Anh ấy không thích phô mai.")],
"butter": [("Spread butter on the toast.","Phết bơ lên bánh mì nướng."),
 ("The butter is in the fridge.","Bơ ở trong tủ lạnh."),
 ("This cake needs more butter.","Cái bánh này cần thêm bơ.")],
"sugar": [("I take my coffee without sugar.","Tôi uống cà phê không đường."),
 ("Add two spoons of sugar.","Thêm hai thìa đường."),
 ("Too much sugar is bad for you.","Ăn nhiều đường quá không tốt.")],
"salt": [("Add a little salt to the soup.","Cho một chút muối vào canh."),
 ("There is too much salt in this dish.","Món này mặn quá."),
 ("Pass me the salt, please.","Đưa tôi lọ muối với.")],
"pepper": [("Too much pepper makes it hot.","Nhiều tiêu quá làm món ăn cay."),
 ("Add salt and pepper to taste.","Nêm muối tiêu vừa ăn."),
 ("She sprinkled pepper on the eggs.","Cô ấy rắc tiêu lên trứng.")],
"sauce": [("This fish sauce is very salty.","Nước mắm này rất mặn."),
 ("Pour the sauce over the rice.","Rưới nước sốt lên cơm."),
 ("He made a special sauce.","Anh ấy làm một loại nước sốt đặc biệt.")],
"oil": [("Heat the oil in the pan.","Đun nóng dầu trong chảo."),
 ("Use less oil when you cook.","Dùng ít dầu hơn khi nấu ăn."),
 ("Olive oil is good for your heart.","Dầu ô liu tốt cho tim.")],
"fruit": [("Eat fruit after every meal.","Ăn trái cây sau mỗi bữa ăn."),
 ("This shop sells tropical fruit.","Cửa hàng này bán trái cây nhiệt đới."),
 ("Fruit is cheaper in summer.","Trái cây rẻ hơn vào mùa hè.")],
"apple": [("An apple a day keeps you healthy.","Mỗi ngày một quả táo giúp bạn khoẻ mạnh."),
 ("She cut the apple into four pieces.","Cô ấy cắt quả táo làm bốn phần."),
 ("These apples are very sweet.","Mấy quả táo này rất ngọt.")],
"banana": [("Monkeys love bananas.","Khỉ rất thích chuối."),
 ("I eat a banana before running.","Tôi ăn một quả chuối trước khi chạy."),
 ("The bananas are not ripe yet.","Chuối chưa chín.")],
"orange": [("This orange is very sweet.","Quả cam này rất ngọt."),
 ("She drinks orange juice every morning.","Cô ấy uống nước cam mỗi sáng."),
 ("Peel the orange before eating.","Bóc vỏ cam trước khi ăn.")],
"mango": [("Vietnamese mangoes are delicious.","Xoài Việt Nam rất ngon."),
 ("This mango is not ripe.","Quả xoài này chưa chín."),
 ("She made mango sticky rice.","Cô ấy làm món xôi xoài.")],
"tomato": [("Add two tomatoes to the salad.","Thêm hai quả cà chua vào món salad."),
 ("Tomatoes grow well in this soil.","Cà chua mọc tốt trên loại đất này."),
 ("I do not like raw tomato.","Tôi không thích cà chua sống.")],
"potato": [("She is boiling potatoes.","Cô ấy đang luộc khoai tây."),
 ("Fried potatoes are very popular.","Khoai tây chiên rất được ưa chuộng."),
 ("Peel the potatoes first.","Gọt vỏ khoai tây trước.")],
"onion": [("Cutting onions makes me cry.","Thái hành làm tôi chảy nước mắt."),
 ("Add the onion to the hot oil.","Cho hành vào dầu nóng."),
 ("This soup has too much onion.","Món canh này nhiều hành quá.")],
"garlic": [("Add garlic for more flavor.","Thêm tỏi cho đậm vị."),
 ("She fried the garlic first.","Cô ấy phi tỏi trước."),
 ("Garlic is good for your health.","Tỏi tốt cho sức khoẻ.")],
"salad": [("I ordered a green salad.","Tôi gọi một đĩa salad rau."),
 ("She makes salad with fresh herbs.","Cô ấy làm salad với rau thơm tươi."),
 ("This salad needs more dressing.","Đĩa salad này cần thêm nước trộn.")],
"sandwich": [("He made a chicken sandwich.","Anh ấy làm một cái bánh mì kẹp gà."),
 ("I take a sandwich to work.","Tôi mang bánh mì kẹp đi làm."),
 ("This sandwich is too big to finish.","Cái bánh mì kẹp này to quá ăn không hết.")],
"cake": [("She baked a birthday cake.","Cô ấy nướng một chiếc bánh sinh nhật."),
 ("This cake is too sweet.","Cái bánh này ngọt quá."),
 ("Cut the cake into eight pieces.","Cắt bánh thành tám phần.")],
"coffee": [("Vietnamese coffee is very strong.","Cà phê Việt Nam rất đậm."),
 ("I drink coffee every morning.","Tôi uống cà phê mỗi sáng."),
 ("This coffee has gone cold.","Cốc cà phê này nguội rồi.")],
"tea": [("My grandfather drinks green tea.","Ông tôi uống trà xanh."),
 ("Would you like some tea?","Bạn dùng chút trà nhé?"),
 ("The tea is still too hot.","Trà vẫn còn nóng quá.")],
"juice": [("I would like some orange juice.","Tôi muốn một chút nước cam."),
 ("She makes fresh juice every morning.","Cô ấy ép nước hoa quả tươi mỗi sáng."),
 ("This juice has no sugar.","Loại nước ép này không đường.")],
"sweet": [("This cake is too sweet.","Cái bánh này ngọt quá."),
 ("She likes sweet drinks.","Cô ấy thích đồ uống ngọt."),
 ("The mango tastes very sweet.","Quả xoài rất ngọt.")],
"sour": [("The lemon tastes sour.","Quả chanh có vị chua."),
 ("This soup is a little sour.","Món canh này hơi chua."),
 ("Green mangoes are sour.","Xoài xanh thì chua.")],
"salty": [("The soup is a bit salty.","Món canh hơi mặn."),
 ("Do not eat too much salty food.","Đừng ăn quá nhiều đồ mặn."),
 ("Sea water is salty.","Nước biển thì mặn.")],
"fresh": [("These vegetables are very fresh.","Mấy loại rau này rất tươi."),
 ("I want fresh fish, not frozen.","Tôi muốn cá tươi, không phải cá đông lạnh."),
 ("The bread is fresh from the oven.","Bánh mì vừa ra lò còn tươi.")],
"fry": [("Fry the eggs for two minutes.","Chiên trứng trong hai phút."),
 ("She is frying fish in the kitchen.","Cô ấy đang chiên cá trong bếp."),
 ("Do not fry the food too long.","Đừng chiên đồ ăn quá lâu.")],
"boil": [("Boil the water before drinking.","Đun sôi nước trước khi uống."),
 ("The soup is boiling now.","Nồi canh đang sôi."),
 ("She boiled two eggs for breakfast.","Cô ấy luộc hai quả trứng cho bữa sáng.")],
"hungry": [("I am hungry after work.","Tôi đói sau khi đi làm về."),
 ("The children are always hungry.","Bọn trẻ lúc nào cũng đói."),
 ("Do not go shopping when you are hungry.","Đừng đi chợ lúc đang đói.")],
}
