# -*- coding: utf-8 -*-
TOPIC = 14  # Time — Thời gian
DATA = {
"time": [("What time is it?","Mấy giờ rồi?"),
 ("I do not have time today.","Hôm nay tôi không có thời gian."),
 ("Time passes quickly when you are busy.","Thời gian trôi nhanh khi bạn bận rộn.")],
"hour": [("The trip takes one hour.","Chuyến đi mất một tiếng."),
 ("She waited for half an hour.","Cô ấy đợi nửa tiếng."),
 ("We work eight hours a day.","Chúng tôi làm việc tám tiếng mỗi ngày.")],
"minute": [("Wait one minute, please.","Vui lòng đợi một phút."),
 ("The bus leaves in ten minutes.","Xe buýt chạy sau mười phút nữa."),
 ("He was five minutes late.","Anh ấy trễ năm phút.")],
"second": [("It only takes a second.","Chỉ mất một giây thôi."),
 ("Wait a second, I am coming.","Đợi một giây, tôi tới ngay."),
 ("The light changes every thirty seconds.","Đèn đổi mỗi ba mươi giây.")],
"day": [("Today is a beautiful day.","Hôm nay là một ngày đẹp trời."),
 ("I work five days a week.","Tôi làm việc năm ngày một tuần."),
 ("The day passed very slowly.","Ngày hôm đó trôi rất chậm.")],
"week": [("See you next week.","Hẹn gặp bạn tuần sau."),
 ("She was away for a week.","Cô ấy đi vắng một tuần."),
 ("There are seven days in a week.","Một tuần có bảy ngày.")],
"month": [("My birthday is next month.","Sinh nhật tôi vào tháng sau."),
 ("He paid the rent this month.","Anh ấy trả tiền thuê tháng này."),
 ("The course lasts three months.","Khoá học kéo dài ba tháng.")],
"year": [("She moved here last year.","Cô ấy chuyển đến đây năm ngoái."),
 ("A year has twelve months.","Một năm có mười hai tháng."),
 ("This year has been very busy.","Năm nay rất bận rộn.")],
"today": [("Today is Monday.","Hôm nay là thứ Hai."),
 ("I feel much better today.","Hôm nay tôi thấy khoẻ hơn nhiều."),
 ("What are you doing today?","Hôm nay bạn làm gì?")],
"tomorrow": [("I will call you tomorrow.","Mai tôi sẽ gọi cho bạn."),
 ("Tomorrow is a holiday.","Ngày mai là ngày nghỉ."),
 ("The exam is tomorrow morning.","Kỳ thi vào sáng mai.")],
"yesterday": [("I met her yesterday.","Tôi gặp cô ấy hôm qua."),
 ("Yesterday was very hot.","Hôm qua trời rất nóng."),
 ("He arrived yesterday evening.","Anh ấy đến vào tối qua.")],
"morning": [("I run every morning.","Tôi chạy bộ mỗi sáng."),
 ("Good morning, everyone.","Chào buổi sáng cả nhà."),
 ("The morning air is very fresh.","Không khí buổi sáng rất trong lành.")],
"afternoon": [("We meet in the afternoon.","Chúng tôi gặp nhau vào buổi chiều."),
 ("The afternoon was hot and quiet.","Buổi chiều nóng và yên ắng."),
 ("She sleeps a little in the afternoon.","Cô ấy ngủ một chút vào buổi chiều.")],
"evening": [("We eat dinner in the evening.","Chúng tôi ăn tối vào buổi tối."),
 ("The evening was cool and windy.","Buổi tối mát và nhiều gió."),
 ("He studies every evening.","Anh ấy học vào mỗi tối.")],
"night": [("The baby slept all night.","Em bé ngủ suốt đêm."),
 ("It gets cold at night.","Về đêm trời trở lạnh."),
 ("She works the night shift.","Cô ấy làm ca đêm.")],
"midnight": [("The party ended at midnight.","Bữa tiệc kết thúc lúc nửa đêm."),
 ("He came home after midnight.","Anh ấy về nhà sau nửa đêm."),
 ("The shop closes at midnight.","Cửa hàng đóng cửa lúc nửa đêm.")],
"noon": [("We have lunch at noon.","Chúng tôi ăn trưa lúc mười hai giờ."),
 ("The sun is strongest at noon.","Nắng gắt nhất vào giữa trưa."),
 ("The meeting starts at noon.","Cuộc họp bắt đầu lúc giữa trưa.")],
"early": [("She always arrives early.","Cô ấy luôn đến sớm."),
 ("I get up early on weekdays.","Tôi dậy sớm vào ngày thường."),
 ("It is too early to decide.","Còn quá sớm để quyết định.")],
"late": [("Sorry, I am late.","Xin lỗi, tôi đến muộn."),
 ("He went to bed late last night.","Tối qua anh ấy đi ngủ muộn."),
 ("The train is ten minutes late.","Tàu trễ mười phút.")],
"clock": [("The clock on the wall is slow.","Chiếc đồng hồ trên tường chạy chậm."),
 ("Look at the clock, we must go.","Nhìn đồng hồ kìa, chúng ta phải đi thôi."),
 ("The clock struck three.","Đồng hồ điểm ba giờ.")],
"calendar": [("Mark the date on your calendar.","Đánh dấu ngày đó lên lịch của bạn."),
 ("The calendar hangs by the door.","Cuốn lịch treo cạnh cửa."),
 ("I checked the calendar for holidays.","Tôi xem lịch để biết ngày nghỉ.")],
"date": [("What is the date today?","Hôm nay ngày mấy?"),
 ("Please write the date here.","Vui lòng ghi ngày vào đây."),
 ("We set a date for the wedding.","Chúng tôi đã chọn ngày cưới.")],
"weekend": [("We go hiking on the weekend.","Chúng tôi đi leo núi vào cuối tuần."),
 ("Have a nice weekend!","Chúc bạn cuối tuần vui vẻ!"),
 ("The weekend passed too quickly.","Cuối tuần trôi qua nhanh quá.")],
"holiday": [("Tet is my favorite holiday.","Tết là ngày lễ tôi thích nhất."),
 ("The office is closed on the holiday.","Văn phòng đóng cửa vào ngày lễ."),
 ("We travel during every holiday.","Chúng tôi đi chơi vào mỗi kỳ nghỉ lễ.")],
"birthday": [("Her birthday is in May.","Sinh nhật cô ấy vào tháng Năm."),
 ("Happy birthday to you!","Chúc mừng sinh nhật bạn!"),
 ("We baked a cake for his birthday.","Chúng tôi nướng bánh mừng sinh nhật anh ấy.")],
"century": [("This temple is a century old.","Ngôi đền này đã một trăm năm tuổi."),
 ("The last century changed everything.","Thế kỷ trước đã thay đổi mọi thứ."),
 ("We live in the twenty first century.","Chúng ta sống ở thế kỷ hai mươi mốt.")],
"decade": [("He lived there for a decade.","Anh ấy sống ở đó một thập kỷ."),
 ("The city changed a lot in one decade.","Thành phố thay đổi nhiều trong một thập kỷ."),
 ("It was the best decade of her life.","Đó là thập kỷ đẹp nhất đời cô ấy.")],
"always": [("She always arrives on time.","Cô ấy luôn đến đúng giờ."),
 ("I always drink tea in the morning.","Tôi luôn uống trà vào buổi sáng."),
 ("He always forgets his keys.","Anh ấy luôn quên chìa khoá.")],
"often": [("We often eat out on Friday.","Chúng tôi thường ăn ngoài vào thứ Sáu."),
 ("How often do you exercise?","Bạn tập thể dục bao lâu một lần?"),
 ("It often rains in the afternoon.","Trời thường mưa vào buổi chiều.")],
"sometimes": [("Sometimes I walk to work.","Đôi khi tôi đi bộ đi làm."),
 ("She sometimes forgets her phone.","Thỉnh thoảng cô ấy quên điện thoại."),
 ("Sometimes the bus is very late.","Đôi khi xe buýt rất trễ.")],
"never": [("I never drink coffee at night.","Tôi không bao giờ uống cà phê buổi tối."),
 ("She has never been abroad.","Cô ấy chưa bao giờ ra nước ngoài."),
 ("He never forgets a birthday.","Anh ấy chẳng bao giờ quên sinh nhật ai.")],
"usually": [("I usually get up at six.","Tôi thường dậy lúc sáu giờ."),
 ("She usually walks to school.","Cô ấy thường đi bộ đến trường."),
 ("We usually eat rice for lunch.","Chúng tôi thường ăn cơm trưa.")],
"daily": [("This is my daily routine.","Đây là nếp sinh hoạt hằng ngày của tôi."),
 ("The shop has daily deliveries.","Cửa hàng nhận hàng mỗi ngày."),
 ("He reads a daily newspaper.","Anh ấy đọc báo hằng ngày.")],
"weekly": [("We have a weekly meeting.","Chúng tôi họp hàng tuần."),
 ("She writes a weekly report.","Cô ấy viết báo cáo hàng tuần."),
 ("The class is weekly, not daily.","Lớp học theo tuần, không phải hằng ngày.")],
"monthly": [("I pay the bill monthly.","Tôi thanh toán hoá đơn hàng tháng."),
 ("The magazine is monthly.","Tạp chí ra hàng tháng."),
 ("We do a monthly check of the car.","Chúng tôi kiểm tra xe hàng tháng.")],
"half": [("Half of the class is absent.","Nửa lớp vắng mặt."),
 ("Give me half a kilo, please.","Cho tôi nửa cân."),
 ("The glass is half full.","Cái ly đầy một nửa.")],
"dozen": [("I bought a dozen eggs.","Tôi mua một tá trứng."),
 ("She ordered a dozen roses.","Cô ấy đặt một tá hoa hồng."),
 ("A dozen people waited outside.","Cả tá người đợi bên ngoài.")],
"hundred": [("There are two hundred students.","Có hai trăm học sinh."),
 ("The book costs one hundred thousand dong.","Cuốn sách giá một trăm nghìn đồng."),
 ("A hundred years is a long time.","Một trăm năm là quãng thời gian dài.")],
"thousand": [("The book costs a thousand dong.","Cuốn sách giá một nghìn đồng."),
 ("A thousand people came to the show.","Một nghìn người đến xem buổi diễn."),
 ("She saved a thousand dollars.","Cô ấy tiết kiệm được một nghìn đô la.")],
"million": [("The city has five million people.","Thành phố có năm triệu dân."),
 ("He won a million dong.","Anh ấy trúng một triệu đồng."),
 ("A million stars filled the sky.","Cả triệu vì sao lấp đầy bầu trời.")],
"moment": [("Wait a moment, please.","Vui lòng đợi một lát."),
 ("It was the best moment of my life.","Đó là khoảnh khắc đẹp nhất đời tôi."),
 ("She left a moment ago.","Cô ấy vừa đi cách đây một lát.")],
"period": [("This was a difficult period.","Đó là một giai đoạn khó khăn."),
 ("The rainy period lasts four months.","Giai đoạn mưa kéo dài bốn tháng."),
 ("He rested for a short period.","Anh ấy nghỉ một khoảng ngắn.")],
"era": [("We live in a digital era.","Chúng ta sống trong thời đại số."),
 ("That era ended long ago.","Thời đại đó đã kết thúc từ lâu."),
 ("It was the era of great change.","Đó là thời đại của những đổi thay lớn.")],
"past": [("Do not worry about the past.","Đừng lo về quá khứ."),
 ("In the past, people wrote letters.","Ngày xưa người ta viết thư."),
 ("She learned from her past.","Cô ấy học được từ quá khứ.")],
"present": [("Focus on the present.","Hãy tập trung vào hiện tại."),
 ("The present situation is difficult.","Tình hình hiện tại rất khó khăn."),
 ("Live in the present, not the past.","Sống ở hiện tại, đừng sống trong quá khứ.")],
"future": [("She is planning for the future.","Cô ấy đang lên kế hoạch cho tương lai."),
 ("Nobody knows the future.","Không ai biết được tương lai."),
 ("In the future, cars may fly.","Trong tương lai, ô tô có thể bay.")],
"recently": [("I saw him recently.","Gần đây tôi có gặp anh ấy."),
 ("She recently changed her job.","Cô ấy vừa đổi việc gần đây."),
 ("Prices have risen recently.","Giá cả tăng lên gần đây.")],
"soon": [("The bus will arrive soon.","Xe buýt sắp tới rồi."),
 ("See you soon!","Hẹn sớm gặp lại!"),
 ("She will be back soon.","Cô ấy sẽ về sớm thôi.")],
"already": [("I have already eaten.","Tôi đã ăn rồi."),
 ("She already knows the answer.","Cô ấy đã biết câu trả lời rồi."),
 ("The film has already started.","Bộ phim đã bắt đầu rồi.")],
"forever": [("Nothing lasts forever.","Không có gì là mãi mãi."),
 ("I will remember this forever.","Tôi sẽ nhớ điều này mãi mãi."),
 ("They promised to stay friends forever.","Họ hứa làm bạn mãi mãi.")],
}
