# -*- coding: utf-8 -*-
TOPIC = 1  # Daily Life — Đời sống hằng ngày
DATA = {
"wake up": [("I wake up at six every morning.","Tôi thức dậy lúc sáu giờ mỗi sáng."),
 ("She does not wake up easily.","Cô ấy không dễ thức dậy."),
 ("We wake up late on Sundays.","Chúng tôi dậy muộn vào Chủ nhật.")],
"breakfast": [("She has breakfast at home.","Cô ấy ăn sáng ở nhà."),
 ("Breakfast is the most important meal.","Bữa sáng là bữa quan trọng nhất."),
 ("I skipped breakfast this morning.","Sáng nay tôi bỏ bữa sáng.")],
"brush": [("I brush my teeth twice a day.","Tôi đánh răng hai lần một ngày."),
 ("She brushes her hair before bed.","Cô ấy chải tóc trước khi đi ngủ."),
 ("Do not forget to brush your teeth.","Đừng quên đánh răng nhé.")],
"shower": [("He takes a shower after work.","Anh ấy tắm sau khi đi làm về."),
 ("The shower is not working today.","Vòi sen hôm nay không chảy."),
 ("I need a cold shower.","Tôi cần tắm nước lạnh.")],
"housework": [("We share the housework.","Chúng tôi chia nhau việc nhà."),
 ("Housework takes her two hours.","Việc nhà chiếm của cô ấy hai tiếng."),
 ("My brother never does any housework.","Anh trai tôi chẳng bao giờ làm việc nhà.")],
"routine": [("A good morning routine helps a lot.","Thói quen buổi sáng tốt giúp ích rất nhiều."),
 ("His daily routine never changes.","Lịch sinh hoạt hằng ngày của anh ấy không đổi."),
 ("I want to build a new routine.","Tôi muốn xây dựng một nếp sinh hoạt mới.")],
"errand": [("I need to run a few errands today.","Hôm nay tôi cần chạy vài việc vặt."),
 ("She left to do an errand.","Cô ấy ra ngoài làm một việc vặt."),
 ("Errands take up my whole morning.","Mấy việc vặt ngốn hết buổi sáng của tôi.")],
"chore": [("Washing dishes is my least favorite chore.","Rửa bát là việc vặt tôi ghét nhất."),
 ("The children each have a chore.","Mỗi đứa trẻ có một việc nhà riêng."),
 ("He finished his chores early.","Cậu ấy làm xong việc nhà sớm.")],
"commute": [("She commutes to the city by train.","Cô ấy đi tàu vào thành phố làm việc."),
 ("My commute takes forty minutes.","Quãng đường đi làm của tôi mất bốn mươi phút."),
 ("A long commute makes me tired.","Đi làm xa khiến tôi mệt.")],
"bedtime": [("His bedtime is ten o'clock.","Giờ đi ngủ của cậu ấy là mười giờ."),
 ("Read a book before bedtime.","Hãy đọc sách trước giờ đi ngủ."),
 ("The children have a strict bedtime.","Bọn trẻ có giờ đi ngủ nghiêm ngặt.")],
"get up": [("I get up at half past six.","Tôi dậy lúc sáu rưỡi."),
 ("You should get up earlier.","Bạn nên dậy sớm hơn."),
 ("They get up when the sun rises.","Họ dậy khi mặt trời mọc.")],
"wash": [("She washes her hands before eating.","Cô ấy rửa tay trước khi ăn."),
 ("I wash my car every weekend.","Tôi rửa xe mỗi cuối tuần."),
 ("Please wash these vegetables.","Vui lòng rửa chỗ rau này.")],
"bath": [("He takes a warm bath at night.","Anh ấy tắm bồn nước ấm vào buổi tối."),
 ("The baby loves her evening bath.","Em bé rất thích tắm buổi tối."),
 ("A hot bath helps me sleep.","Tắm nước nóng giúp tôi dễ ngủ.")],
"soap": [("Use soap to wash your hands.","Dùng xà phòng để rửa tay."),
 ("This soap smells like lemon.","Cục xà phòng này thơm mùi chanh."),
 ("We ran out of soap.","Chúng ta hết xà phòng rồi.")],
"toothbrush": [("My toothbrush is blue.","Bàn chải của tôi màu xanh."),
 ("Change your toothbrush every three months.","Hãy thay bàn chải ba tháng một lần."),
 ("He packed a toothbrush for the trip.","Anh ấy mang theo bàn chải cho chuyến đi.")],
"toothpaste": [("We ran out of toothpaste.","Chúng ta hết kem đánh răng rồi."),
 ("This toothpaste tastes like mint.","Kem đánh răng này vị bạc hà."),
 ("Put a little toothpaste on the brush.","Bóp một ít kem đánh răng lên bàn chải.")],
"shampoo": [("This shampoo smells nice.","Dầu gội này thơm."),
 ("She bought shampoo for dry hair.","Cô ấy mua dầu gội cho tóc khô."),
 ("The shampoo bottle is almost empty.","Chai dầu gội gần hết rồi.")],
"comb": [("She combs her hair every morning.","Cô ấy chải tóc mỗi sáng."),
 ("I lost my comb.","Tôi làm mất cái lược rồi."),
 ("Use a comb, not your fingers.","Dùng lược đi, đừng dùng tay.")],
"get dressed": [("I get dressed in five minutes.","Tôi mặc quần áo trong năm phút."),
 ("Please get dressed quickly.","Mặc quần áo nhanh lên."),
 ("The children get dressed by themselves.","Bọn trẻ tự mặc quần áo.")],
"make the bed": [("Please make the bed before you leave.","Hãy dọn giường trước khi bạn đi."),
 ("I make the bed every morning.","Tôi dọn giường mỗi sáng."),
 ("Did you make the bed today?","Hôm nay bạn dọn giường chưa?")],
"lunch": [("We have lunch at noon.","Chúng tôi ăn trưa lúc mười hai giờ."),
 ("Lunch is included in the price.","Bữa trưa đã tính trong giá."),
 ("She brought lunch from home.","Cô ấy mang cơm trưa từ nhà.")],
"dinner": [("Dinner is ready at seven.","Bữa tối xong lúc bảy giờ."),
 ("We had dinner with our neighbors.","Chúng tôi ăn tối với hàng xóm."),
 ("What is for dinner tonight?","Tối nay ăn gì thế?")],
"snack": [("I had a snack after school.","Tôi ăn nhẹ sau giờ học."),
 ("She keeps snacks in her bag.","Cô ấy để đồ ăn vặt trong túi."),
 ("This snack is too salty.","Món ăn vặt này mặn quá.")],
"cook": [("My father cooks on Sunday.","Bố tôi nấu ăn vào Chủ nhật."),
 ("I cook dinner for my family.","Tôi nấu bữa tối cho gia đình."),
 ("She cooks better than anyone.","Cô ấy nấu ăn ngon hơn ai hết.")],
"dishes": [("I wash the dishes after dinner.","Tôi rửa bát sau bữa tối."),
 ("The dishes are still in the sink.","Bát đĩa vẫn còn trong bồn."),
 ("He broke two dishes yesterday.","Hôm qua anh ấy làm vỡ hai cái đĩa.")],
"laundry": [("She does the laundry on Saturday.","Cô ấy giặt giũ vào thứ Bảy."),
 ("The laundry is still wet.","Đồ giặt vẫn còn ướt."),
 ("Put your laundry in the basket.","Bỏ đồ giặt vào giỏ.")],
"iron": [("He irons his shirt every morning.","Anh ấy là áo sơ mi mỗi sáng."),
 ("Be careful, the iron is hot.","Cẩn thận, bàn là đang nóng."),
 ("This shirt does not need an iron.","Chiếc áo này không cần là.")],
"sweep": [("I sweep the floor twice a day.","Tôi quét nhà hai lần một ngày."),
 ("She sweeps the yard every morning.","Cô ấy quét sân mỗi sáng."),
 ("Please sweep under the table.","Vui lòng quét dưới gầm bàn.")],
"mop": [("She mops the kitchen floor.","Cô ấy lau sàn bếp."),
 ("The mop is behind the door.","Cây lau nhà ở sau cửa."),
 ("I mop the floor after cooking.","Tôi lau nhà sau khi nấu ăn.")],
"vacuum": [("We vacuum the carpet every week.","Chúng tôi hút bụi thảm mỗi tuần."),
 ("The vacuum is very noisy.","Máy hút bụi kêu rất to."),
 ("He forgot to vacuum the bedroom.","Anh ấy quên hút bụi phòng ngủ.")],
"trash": [("Take out the trash, please.","Vui lòng đem rác đi đổ."),
 ("The trash bin is full.","Thùng rác đầy rồi."),
 ("Do not throw trash on the street.","Đừng vứt rác ra đường.")],
"clean": [("I clean my room on Sunday.","Tôi dọn phòng vào Chủ nhật."),
 ("The kitchen is very clean.","Nhà bếp rất sạch sẽ."),
 ("She cleans the windows once a month.","Cô ấy lau cửa sổ mỗi tháng một lần.")],
"shopping": [("We go shopping on the weekend.","Chúng tôi đi mua sắm vào cuối tuần."),
 ("Shopping online saves time.","Mua sắm trực tuyến tiết kiệm thời gian."),
 ("She hates shopping for clothes.","Cô ấy ghét đi mua quần áo.")],
"nap": [("He takes a short nap after lunch.","Anh ấy ngủ trưa một lát sau khi ăn."),
 ("A twenty minute nap is enough.","Ngủ trưa hai mươi phút là đủ."),
 ("The baby is having a nap.","Em bé đang ngủ.")],
"rest": [("You should rest for an hour.","Bạn nên nghỉ một tiếng."),
 ("She needs rest after the trip.","Cô ấy cần nghỉ ngơi sau chuyến đi."),
 ("Let us rest under that tree.","Chúng ta nghỉ dưới gốc cây kia đi.")],
"relax": [("I relax by listening to music.","Tôi thư giãn bằng cách nghe nhạc."),
 ("Relax, everything will be fine.","Thư giãn đi, mọi chuyện sẽ ổn."),
 ("He relaxes in the garden.","Anh ấy thư giãn ngoài vườn.")],
"sleepy": [("I feel sleepy after lunch.","Tôi thấy buồn ngủ sau bữa trưa."),
 ("The children look sleepy.","Bọn trẻ trông buồn ngủ."),
 ("Coffee keeps me from getting sleepy.","Cà phê giúp tôi không buồn ngủ.")],
"awake": [("The baby is still awake.","Em bé vẫn còn thức."),
 ("I stayed awake until midnight.","Tôi thức đến nửa đêm."),
 ("Are you awake yet?","Bạn dậy chưa?")],
"alarm clock": [("My alarm clock rings at six.","Đồng hồ báo thức của tôi reo lúc sáu giờ."),
 ("I forgot to set the alarm clock.","Tôi quên đặt đồng hồ báo thức."),
 ("His alarm clock is very loud.","Đồng hồ báo thức của anh ấy kêu rất to.")],
"hobby": [("Reading is my favorite hobby.","Đọc sách là sở thích yêu thích của tôi."),
 ("What is your hobby?","Sở thích của bạn là gì?"),
 ("Gardening became her new hobby.","Làm vườn trở thành sở thích mới của cô ấy.")],
"habit": [("Getting up early is a good habit.","Dậy sớm là một thói quen tốt."),
 ("Smoking is a bad habit.","Hút thuốc là một thói quen xấu."),
 ("It takes time to change a habit.","Thay đổi một thói quen cần thời gian.")],
"free time": [("What do you do in your free time?","Bạn làm gì trong thời gian rảnh?"),
 ("I have very little free time.","Tôi có rất ít thời gian rảnh."),
 ("She spends her free time painting.","Cô ấy dành thời gian rảnh để vẽ.")],
"busy": [("I am busy every Monday.","Tôi bận vào mỗi thứ Hai."),
 ("The office is busy in the morning.","Văn phòng bận rộn vào buổi sáng."),
 ("Sorry, I am too busy today.","Xin lỗi, hôm nay tôi bận quá.")],
"hurry": [("Hurry up or we will be late.","Nhanh lên không thì muộn mất."),
 ("There is no need to hurry.","Không cần phải vội."),
 ("She left in a hurry.","Cô ấy vội vã rời đi.")],
"prepare": [("She prepares dinner at six.","Cô ấy chuẩn bị bữa tối lúc sáu giờ."),
 ("I need time to prepare.","Tôi cần thời gian chuẩn bị."),
 ("They prepare the room for guests.","Họ chuẩn bị phòng cho khách.")],
"arrive": [("I arrive at work before eight.","Tôi đến chỗ làm trước tám giờ."),
 ("The train arrives at nine.","Tàu đến lúc chín giờ."),
 ("We arrived home very late.","Chúng tôi về đến nhà rất muộn.")],
"rush hour": [("Traffic is terrible during rush hour.","Giao thông kinh khủng vào giờ cao điểm."),
 ("Avoid the road at rush hour.","Tránh con đường đó vào giờ cao điểm."),
 ("Rush hour starts around five.","Giờ cao điểm bắt đầu khoảng năm giờ.")],
"weekday": [("I only work on weekdays.","Tôi chỉ làm việc vào các ngày trong tuần."),
 ("The museum is quiet on weekdays.","Bảo tàng vắng vào ngày thường."),
 ("She studies every weekday evening.","Cô ấy học vào mỗi tối ngày thường.")],
"chat": [("We chat online every evening.","Chúng tôi trò chuyện trực tuyến mỗi tối."),
 ("They had a long chat over coffee.","Họ trò chuyện rất lâu bên tách cà phê."),
 ("I chat with my sister every day.","Tôi nói chuyện với chị gái mỗi ngày.")],
"newspaper": [("He reads the newspaper with coffee.","Anh ấy đọc báo bên tách cà phê."),
 ("The newspaper comes every morning.","Báo được giao mỗi sáng."),
 ("I saw her photo in the newspaper.","Tôi thấy ảnh cô ấy trên báo.")],
}
