# -*- coding: utf-8 -*-
TOPIC = 3  # Travel — Du lịch
DATA = {
"trip": [("We are planning a trip to Da Nang.","Chúng tôi đang lên kế hoạch cho chuyến đi Đà Nẵng."),
 ("The trip lasted five days.","Chuyến đi kéo dài năm ngày."),
 ("Have a safe trip!","Chúc bạn đi đường bình an!")],
"luggage": [("Don't forget your luggage.","Đừng quên hành lý của bạn."),
 ("My luggage is too heavy.","Hành lý của tôi nặng quá."),
 ("They lost my luggage at the airport.","Họ làm thất lạc hành lý của tôi ở sân bay.")],
"ticket": [("I booked two tickets online.","Tôi đã đặt hai vé trên mạng."),
 ("Show your ticket at the gate.","Xuất trình vé ở cửa."),
 ("The ticket costs one million dong.","Vé giá một triệu đồng.")],
"airport": [("The airport is far from here.","Sân bay cách đây khá xa."),
 ("We arrived at the airport early.","Chúng tôi đến sân bay sớm."),
 ("The airport was crowded last night.","Sân bay đông nghịt tối qua.")],
"passport": [("Please show me your passport.","Vui lòng cho tôi xem hộ chiếu."),
 ("My passport expires next year.","Hộ chiếu của tôi hết hạn năm sau."),
 ("Keep your passport in a safe place.","Hãy cất hộ chiếu ở nơi an toàn.")],
"destination": [("Our destination is the old town.","Điểm đến của chúng tôi là phố cổ."),
 ("Hoi An is a popular destination.","Hội An là một điểm đến nổi tiếng."),
 ("We reached our destination at noon.","Chúng tôi tới nơi lúc giữa trưa.")],
"reservation": [("I made a hotel reservation.","Tôi đã đặt phòng khách sạn."),
 ("Do you have a reservation?","Bạn đã đặt chỗ chưa?"),
 ("She cancelled her reservation.","Cô ấy đã huỷ đặt chỗ.")],
"sightseeing": [("We went sightseeing all day.","Chúng tôi đi tham quan cả ngày."),
 ("There is a sightseeing bus downtown.","Có xe buýt tham quan ở trung tâm."),
 ("Sightseeing is tiring but fun.","Đi tham quan mệt nhưng vui.")],
"itinerary": [("Send me the full itinerary.","Gửi tôi lịch trình đầy đủ nhé."),
 ("Our itinerary changed at the last minute.","Lịch trình của chúng tôi thay đổi vào phút chót."),
 ("The itinerary includes three cities.","Lịch trình gồm ba thành phố.")],
"souvenir": [("She bought a souvenir for her mom.","Cô ấy mua quà lưu niệm cho mẹ."),
 ("This shop sells cheap souvenirs.","Cửa hàng này bán quà lưu niệm rẻ."),
 ("I kept the ticket as a souvenir.","Tôi giữ tấm vé làm kỷ niệm.")],
"travel": [("They travel abroad every summer.","Họ đi nước ngoài mỗi mùa hè."),
 ("I love to travel by train.","Tôi thích đi du lịch bằng tàu."),
 ("Travel opens your mind.","Đi đây đó giúp bạn mở mang đầu óc.")],
"journey": [("The journey took six hours.","Hành trình mất sáu tiếng."),
 ("It was a long and tiring journey.","Đó là một hành trình dài và mệt."),
 ("We began our journey at dawn.","Chúng tôi bắt đầu hành trình lúc rạng sáng.")],
"tourist": [("Many tourists visit Hoi An.","Nhiều khách du lịch tới Hội An."),
 ("This street is full of tourists.","Con phố này đầy khách du lịch."),
 ("Tourists should respect local customs.","Khách du lịch nên tôn trọng phong tục địa phương.")],
"guide": [("Our guide speaks three languages.","Hướng dẫn viên của chúng tôi nói được ba thứ tiếng."),
 ("The guide told us the history.","Hướng dẫn viên kể cho chúng tôi về lịch sử."),
 ("We hired a local guide.","Chúng tôi thuê một hướng dẫn viên địa phương.")],
"map": [("Can you read this map?","Bạn đọc được bản đồ này không?"),
 ("The map shows every small street.","Bản đồ hiện cả những con phố nhỏ."),
 ("I downloaded an offline map.","Tôi đã tải bản đồ ngoại tuyến.")],
"flight": [("My flight leaves at noon.","Chuyến bay của tôi khởi hành lúc trưa."),
 ("The flight was delayed two hours.","Chuyến bay bị hoãn hai tiếng."),
 ("It is a six hour flight.","Đó là chuyến bay sáu tiếng.")],
"airplane": [("The airplane is taking off.","Máy bay đang cất cánh."),
 ("This airplane holds three hundred people.","Chiếc máy bay này chở được ba trăm người."),
 ("I am afraid of airplanes.","Tôi sợ đi máy bay.")],
"airline": [("Which airline are you flying with?","Bạn bay hãng nào?"),
 ("The airline lost my bag.","Hãng hàng không làm mất túi của tôi."),
 ("This airline has cheap tickets.","Hãng này có vé rẻ.")],
"boarding pass": [("Please show your boarding pass.","Vui lòng xuất trình thẻ lên máy bay."),
 ("I printed my boarding pass at home.","Tôi in thẻ lên máy bay ở nhà."),
 ("Keep the boarding pass until you land.","Giữ thẻ lên máy bay cho tới khi hạ cánh.")],
"gate": [("Our gate number is twelve.","Cửa ra máy bay của chúng ta là số mười hai."),
 ("The gate closes ten minutes before departure.","Cửa đóng mười phút trước giờ bay."),
 ("They changed our gate again.","Họ lại đổi cửa của chúng tôi.")],
"departure": [("The departure time is nine thirty.","Giờ khởi hành là chín rưỡi."),
 ("Check the departure board.","Xem bảng khởi hành đi."),
 ("Our departure was delayed by fog.","Giờ khởi hành bị hoãn vì sương mù.")],
"arrival": [("Check the arrival board.","Xem bảng giờ đến đi."),
 ("His arrival surprised everyone.","Việc anh ấy đến khiến ai cũng bất ngờ."),
 ("The arrival time is four in the afternoon.","Giờ đến là bốn giờ chiều.")],
"delay": [("There is a two hour delay.","Có sự chậm trễ hai tiếng."),
 ("The delay was caused by bad weather.","Sự chậm trễ là do thời tiết xấu."),
 ("We apologize for the delay.","Chúng tôi xin lỗi vì sự chậm trễ.")],
"customs": [("We waited at customs.","Chúng tôi chờ ở hải quan."),
 ("Customs checked every bag.","Hải quan kiểm tra từng túi."),
 ("Going through customs took an hour.","Làm thủ tục hải quan mất một tiếng.")],
"visa": [("You need a visa to enter.","Bạn cần thị thực để nhập cảnh."),
 ("My visa is valid for three months.","Thị thực của tôi có giá trị ba tháng."),
 ("She applied for a student visa.","Cô ấy xin thị thực du học.")],
"train": [("The train to Hue leaves at eight.","Tàu đi Huế khởi hành lúc tám giờ."),
 ("I prefer the train to the bus.","Tôi thích đi tàu hơn xe buýt."),
 ("The train was very crowded.","Tàu rất đông.")],
"bus": [("I take the bus to work.","Tôi đi xe buýt đi làm."),
 ("The bus stops in front of the school.","Xe buýt dừng trước cổng trường."),
 ("We missed the last bus.","Chúng tôi lỡ chuyến xe buýt cuối.")],
"taxi": [("Let us call a taxi.","Chúng ta gọi taxi đi."),
 ("The taxi driver was very kind.","Bác tài xế taxi rất tốt bụng."),
 ("A taxi to the airport is expensive.","Đi taxi ra sân bay khá đắt.")],
"ferry": [("We crossed the river by ferry.","Chúng tôi qua sông bằng phà."),
 ("The ferry leaves every hour.","Phà chạy mỗi giờ một chuyến."),
 ("The ferry was full of motorbikes.","Chiếc phà đầy xe máy.")],
"ship": [("The ship sails at dawn.","Con tàu nhổ neo lúc rạng sáng."),
 ("This ship carries containers.","Con tàu này chở công-ten-nơ."),
 ("We watched the ship leave the port.","Chúng tôi nhìn con tàu rời cảng.")],
"platform": [("The train arrives at platform three.","Tàu đến ở sân ga số ba."),
 ("She waited alone on the platform.","Cô ấy đợi một mình trên sân ga."),
 ("Which platform is it?","Sân ga nào vậy?")],
"suitcase": [("My suitcase is too heavy.","Va li của tôi nặng quá."),
 ("She packed her suitcase last night.","Cô ấy soạn va li tối qua."),
 ("The suitcase would not close.","Cái va li không đóng lại được.")],
"check in": [("We check in at two o'clock.","Chúng tôi nhận phòng lúc hai giờ."),
 ("You can check in online.","Bạn có thể làm thủ tục trực tuyến."),
 ("Please check in one hour early.","Vui lòng làm thủ tục sớm một tiếng.")],
"check out": [("Please check out before noon.","Vui lòng trả phòng trước mười hai giờ."),
 ("We check out tomorrow morning.","Chúng tôi trả phòng sáng mai."),
 ("Can I check out later?","Tôi trả phòng muộn hơn được không?")],
"book": [("I booked a room online.","Tôi đã đặt phòng trên mạng."),
 ("Book your ticket early to save money.","Đặt vé sớm để tiết kiệm tiền."),
 ("She booked a table for four.","Cô ấy đặt bàn cho bốn người.")],
"accommodation": [("The accommodation was clean and cheap.","Chỗ ở sạch sẽ và rẻ."),
 ("We are still looking for accommodation.","Chúng tôi vẫn đang tìm chỗ ở."),
 ("Accommodation is included in the tour.","Chỗ ở đã bao gồm trong tour.")],
"hostel": [("We stayed in a small hostel.","Chúng tôi ở một nhà nghỉ nhỏ."),
 ("The hostel has free breakfast.","Nhà nghỉ có bữa sáng miễn phí."),
 ("A hostel is cheaper than a hotel.","Nhà nghỉ rẻ hơn khách sạn.")],
"resort": [("The resort has two pools.","Khu nghỉ dưỡng có hai hồ bơi."),
 ("We spent the weekend at a beach resort.","Chúng tôi nghỉ cuối tuần ở khu nghỉ dưỡng biển."),
 ("This resort is fully booked.","Khu nghỉ dưỡng này đã kín phòng.")],
"abroad": [("She studies abroad.","Cô ấy du học nước ngoài."),
 ("They moved abroad last year.","Họ chuyển ra nước ngoài năm ngoái."),
 ("Working abroad is not easy.","Làm việc ở nước ngoài không dễ.")],
"foreign": [("He speaks two foreign languages.","Anh ấy nói được hai ngoại ngữ."),
 ("Foreign tourists love this market.","Khách nước ngoài rất thích cái chợ này."),
 ("This is my first foreign trip.","Đây là chuyến đi nước ngoài đầu tiên của tôi.")],
"currency": [("What is the local currency?","Tiền tệ ở đây là gì?"),
 ("The currency here is very weak.","Đồng tiền ở đây rất yếu."),
 ("You can change currency at the airport.","Bạn có thể đổi tiền ở sân bay.")],
"exchange": [("Where can I exchange money?","Tôi đổi tiền ở đâu được?"),
 ("The exchange rate is good today.","Tỉ giá hôm nay tốt."),
 ("She exchanged dollars for dong.","Cô ấy đổi đô la sang tiền đồng.")],
"insurance": [("Travel insurance is important.","Bảo hiểm du lịch rất quan trọng."),
 ("Does the insurance cover lost bags?","Bảo hiểm có bồi thường hành lý thất lạc không?"),
 ("I bought insurance for the whole trip.","Tôi mua bảo hiểm cho cả chuyến đi.")],
"adventure": [("The trip was a real adventure.","Chuyến đi đúng là một cuộc phiêu lưu."),
 ("He loves adventure sports.","Anh ấy thích các môn thể thao mạo hiểm."),
 ("Every journey is an adventure.","Mỗi hành trình đều là một cuộc phiêu lưu.")],
"explore": [("We explored the old town.","Chúng tôi khám phá phố cổ."),
 ("I want to explore the countryside.","Tôi muốn khám phá vùng quê."),
 ("They explored the cave with a guide.","Họ khám phá hang động cùng hướng dẫn viên.")],
"landmark": [("This tower is a famous landmark.","Tháp này là một địa danh nổi tiếng."),
 ("The bridge is the city's main landmark.","Cây cầu là địa danh chính của thành phố."),
 ("We visited every landmark in one day.","Chúng tôi thăm hết các địa danh trong một ngày.")],
"postcard": [("She sent me a postcard.","Cô ấy gửi cho tôi một tấm bưu thiếp."),
 ("I bought a postcard at the museum.","Tôi mua một tấm bưu thiếp ở bảo tàng."),
 ("The view looks like a postcard.","Khung cảnh đẹp như bưu thiếp.")],
"camera": [("Do not forget your camera.","Đừng quên máy ảnh của bạn."),
 ("My camera ran out of battery.","Máy ảnh của tôi hết pin."),
 ("She takes photos with an old camera.","Cô ấy chụp ảnh bằng một chiếc máy ảnh cũ.")],
"vacation": [("We are on vacation next week.","Tuần sau chúng tôi đi nghỉ."),
 ("She took a two week vacation.","Cô ấy nghỉ phép hai tuần."),
 ("Where did you go on vacation?","Kỳ nghỉ vừa rồi bạn đi đâu?")],
"route": [("This route is much shorter.","Tuyến đường này ngắn hơn nhiều."),
 ("The bus route changed last month.","Tuyến xe buýt đã đổi từ tháng trước."),
 ("We took a scenic route home.","Chúng tôi về theo một tuyến đường đẹp.")],
}
