# -*- coding: utf-8 -*-
TOPIC = 13  # Animals — Động vật
DATA = {
"animal": [("This animal only comes out at night.","Con vật này chỉ ra ngoài vào ban đêm."),
 ("Every animal needs clean water.","Mọi loài vật đều cần nước sạch."),
 ("The zoo has animals from Africa.","Sở thú có động vật từ châu Phi.")],
"dog": [("Their dog barks at every stranger.","Con chó của họ sủa mỗi khi có người lạ."),
 ("She walks her dog every evening.","Cô ấy dắt chó đi dạo mỗi tối."),
 ("The dog is sleeping under the table.","Con chó đang ngủ dưới gầm bàn.")],
"cat": [("The cat is sleeping on the sofa.","Con mèo đang ngủ trên ghế sofa."),
 ("Her cat is black and white.","Con mèo của cô ấy đen trắng."),
 ("The cat caught a mouse.","Con mèo bắt được một con chuột.")],
"bird": [("A bird is singing outside.","Một con chim đang hót bên ngoài."),
 ("The bird flew away quickly.","Con chim bay đi rất nhanh."),
 ("We saw a large bird by the lake.","Chúng tôi thấy một con chim lớn bên hồ.")],
"fish": [("The fish swim in circles.","Đàn cá bơi thành vòng tròn."),
 ("He caught a big fish this morning.","Sáng nay anh ấy bắt được một con cá to."),
 ("This fish lives in fresh water.","Loài cá này sống ở nước ngọt.")],
"horse": [("The horse is running in the field.","Con ngựa đang chạy trên cánh đồng."),
 ("She learned to ride a horse.","Cô ấy học cưỡi ngựa."),
 ("The horse drank from the stream.","Con ngựa uống nước từ dòng suối.")],
"cow": [("The cow is eating grass.","Con bò đang ăn cỏ."),
 ("We get milk from a cow.","Chúng ta lấy sữa từ con bò."),
 ("A cow stood in the middle of the road.","Một con bò đứng giữa đường.")],
"pig": [("The pig is very fat.","Con lợn rất béo."),
 ("They keep three pigs on the farm.","Họ nuôi ba con lợn ở trang trại."),
 ("The pig rolled in the mud.","Con lợn lăn trong bùn.")],
"chicken": [("The chicken laid two eggs.","Con gà đẻ hai quả trứng."),
 ("She feeds the chicken every morning.","Cô ấy cho gà ăn mỗi sáng."),
 ("A chicken ran across the yard.","Một con gà chạy ngang sân.")],
"duck": [("The duck is swimming in the pond.","Con vịt đang bơi trong ao."),
 ("A duck walked past our table.","Một con vịt đi ngang qua bàn chúng tôi."),
 ("The duck has bright orange feet.","Con vịt có đôi chân màu cam sáng.")],
"goat": [("The goat is climbing the rock.","Con dê đang leo lên tảng đá."),
 ("They keep a goat for milk.","Họ nuôi dê lấy sữa."),
 ("The goat ate my paper!","Con dê ăn mất tờ giấy của tôi!")],
"sheep": [("The sheep are on the hill.","Đàn cừu đang ở trên đồi."),
 ("He counts sheep to fall asleep.","Anh ấy đếm cừu để dễ ngủ."),
 ("The sheep has thick white wool.","Con cừu có bộ lông trắng dày.")],
"buffalo": [("The buffalo is resting in the mud.","Con trâu đang nghỉ trong bùn."),
 ("A buffalo pulls the plough.","Con trâu kéo cày."),
 ("The buffalo is very strong.","Con trâu rất khoẻ.")],
"rabbit": [("The rabbit is eating a carrot.","Con thỏ đang ăn cà rốt."),
 ("A white rabbit ran into the bushes.","Một con thỏ trắng chạy vào bụi cây."),
 ("Her pet rabbit has long ears.","Con thỏ cưng của cô ấy có tai dài.")],
"mouse": [("The cat is chasing a mouse.","Con mèo đang đuổi một con chuột."),
 ("A mouse ran under the fridge.","Một con chuột chạy xuống dưới tủ lạnh."),
 ("The mouse is very small and gray.","Con chuột rất nhỏ và màu xám.")],
"elephant": [("The elephant is the largest land animal.","Voi là loài vật trên cạn lớn nhất."),
 ("An elephant never forgets.","Voi không bao giờ quên."),
 ("The elephant sprayed water with its trunk.","Con voi phun nước bằng vòi.")],
"tiger": [("The tiger has orange and black stripes.","Con hổ có vằn cam và đen."),
 ("A tiger hunts alone.","Hổ săn mồi một mình."),
 ("The tiger slept all afternoon.","Con hổ ngủ suốt buổi chiều.")],
"lion": [("The lion is called the king of animals.","Sư tử được gọi là chúa tể muôn loài."),
 ("A lion roared in the distance.","Một con sư tử gầm từ xa."),
 ("The lion rested under a tree.","Con sư tử nghỉ dưới gốc cây.")],
"bear": [("The bear is looking for food.","Con gấu đang tìm thức ăn."),
 ("A brown bear lives in this forest.","Một con gấu nâu sống trong khu rừng này."),
 ("The bear sleeps all winter.","Con gấu ngủ suốt mùa đông.")],
"monkey": [("The monkey is sitting on a branch.","Con khỉ đang ngồi trên cành cây."),
 ("A monkey stole my banana.","Một con khỉ cướp mất quả chuối của tôi."),
 ("Monkeys are very clever.","Khỉ rất thông minh.")],
"snake": [("The snake moved through the grass.","Con rắn trườn qua đám cỏ."),
 ("Not every snake is dangerous.","Không phải con rắn nào cũng nguy hiểm."),
 ("She is afraid of every snake.","Cô ấy sợ mọi loài rắn.")],
"frog": [("The frog jumped into the pond.","Con ếch nhảy xuống ao."),
 ("A frog was singing all night.","Một con ếch kêu suốt đêm."),
 ("The frog has smooth green skin.","Con ếch có làn da xanh trơn.")],
"turtle": [("The turtle moves very slowly.","Con rùa di chuyển rất chậm."),
 ("A turtle swam past the boat.","Một con rùa bơi ngang qua thuyền."),
 ("The turtle hid inside its shell.","Con rùa rụt vào mai.")],
"butterfly": [("A butterfly landed on the flower.","Một con bướm đậu lên bông hoa."),
 ("The butterfly has blue wings.","Con bướm có đôi cánh xanh."),
 ("Children chased the butterfly.","Bọn trẻ đuổi theo con bướm.")],
"bee": [("A bee is on the flower.","Một con ong đang đậu trên hoa."),
 ("The bee stung my hand.","Con ong chích vào tay tôi."),
 ("Every bee helps make honey.","Mỗi con ong đều góp phần làm mật.")],
"ant": [("An ant is carrying a leaf.","Một con kiến đang tha chiếc lá."),
 ("There is an ant on the table.","Có một con kiến trên bàn."),
 ("The ant is small but strong.","Con kiến nhỏ nhưng khoẻ.")],
"spider": [("A spider made a web in the corner.","Một con nhện giăng tơ ở góc nhà."),
 ("The spider has eight legs.","Con nhện có tám chân."),
 ("She screamed when she saw the spider.","Cô ấy hét lên khi thấy con nhện.")],
"insect": [("This insect only lives one day.","Loài côn trùng này chỉ sống một ngày."),
 ("An insect flew into the room.","Một con côn trùng bay vào phòng."),
 ("Some insects help our garden.","Một số côn trùng có ích cho khu vườn.")],
"wing": [("The bird hurt its wing.","Con chim bị đau cánh."),
 ("A butterfly wing is very thin.","Cánh bướm rất mỏng."),
 ("The bird spread its wings wide.","Con chim dang rộng đôi cánh.")],
"tail": [("The dog wagged its tail.","Con chó vẫy đuôi."),
 ("The cat has a long tail.","Con mèo có cái đuôi dài."),
 ("A fish moves with its tail.","Cá bơi bằng đuôi.")],
"feather": [("I found a white feather.","Tôi nhặt được một chiếc lông vũ trắng."),
 ("The feather floated to the ground.","Chiếc lông vũ nhẹ nhàng rơi xuống đất."),
 ("A duck feather keeps out water.","Lông vịt không thấm nước.")],
"fur": [("The cat has soft fur.","Con mèo có bộ lông mềm."),
 ("Bears grow thick fur in winter.","Gấu mọc lông dày vào mùa đông."),
 ("Her dog's fur is snow white.","Lông con chó của cô ấy trắng như tuyết.")],
"pet": [("A dog is a popular pet.","Chó là thú cưng phổ biến."),
 ("She has three pets at home.","Cô ấy nuôi ba con thú cưng ở nhà."),
 ("My pet sleeps on my bed.","Thú cưng của tôi ngủ trên giường tôi.")],
"wild": [("Wild animals live in the forest.","Thú hoang sống trong rừng."),
 ("Do not feed wild birds.","Đừng cho chim hoang ăn."),
 ("This flower grows wild here.","Loài hoa này mọc hoang ở đây.")],
"farm": [("They keep cows on the farm.","Họ nuôi bò ở trang trại."),
 ("The farm is outside the village.","Trang trại nằm ngoài làng."),
 ("He works on his family farm.","Anh ấy làm ở trang trại của gia đình.")],
"zoo": [("We took the children to the zoo.","Chúng tôi đưa bọn trẻ đi sở thú."),
 ("The zoo opens at eight.","Sở thú mở cửa lúc tám giờ."),
 ("This zoo protects rare animals.","Sở thú này bảo tồn các loài quý hiếm.")],
"cage": [("The bird is in a cage.","Con chim ở trong lồng."),
 ("He cleaned the cage this morning.","Sáng nay anh ấy dọn lồng."),
 ("The cage door was left open.","Cửa lồng bị bỏ ngỏ.")],
"nest": [("There is a nest in the tree.","Có một cái tổ trên cây."),
 ("The bird built a nest of grass.","Con chim làm tổ bằng cỏ."),
 ("Three eggs lay in the nest.","Ba quả trứng nằm trong tổ.")],
"bark": [("Dogs bark at strangers.","Chó sủa người lạ."),
 ("The dog barks every night.","Con chó sủa mỗi đêm."),
 ("I heard a loud bark outside.","Tôi nghe tiếng sủa to bên ngoài.")],
"feed": [("I feed my cat twice a day.","Tôi cho mèo ăn hai lần một ngày."),
 ("Do not feed the animals here.","Đừng cho động vật ăn ở đây."),
 ("She feeds the chickens every morning.","Cô ấy cho gà ăn mỗi sáng.")],
"goose": [("A goose is swimming in the pond.","Một con ngỗng đang bơi trong ao."),
 ("The goose chased the children.","Con ngỗng đuổi theo bọn trẻ."),
 ("A goose is larger than a duck.","Ngỗng to hơn vịt.")],
"deer": [("We saw a deer in the forest.","Chúng tôi thấy một con hươu trong rừng."),
 ("The deer ran into the trees.","Con hươu chạy vào rừng cây."),
 ("A young deer stood by the road.","Một con hươu non đứng bên đường.")],
"fox": [("The fox ran into the bushes.","Con cáo chạy vào bụi cây."),
 ("A fox visits our garden at night.","Một con cáo hay ghé vườn nhà tôi ban đêm."),
 ("The fox has a thick red tail.","Con cáo có cái đuôi đỏ rậm.")],
"wolf": [("A wolf howled in the night.","Một con sói tru trong đêm."),
 ("The wolf hunts with its group.","Sói săn mồi theo bầy."),
 ("We saw a gray wolf from far away.","Chúng tôi thấy một con sói xám từ xa.")],
"whale": [("The whale is the largest animal.","Cá voi là loài vật lớn nhất."),
 ("A whale jumped out of the water.","Một con cá voi nhảy khỏi mặt nước."),
 ("The whale swam beside our boat.","Con cá voi bơi cạnh thuyền chúng tôi.")],
"dolphin": [("A dolphin is very intelligent.","Cá heo rất thông minh."),
 ("The dolphin jumped high above the waves.","Con cá heo nhảy cao trên sóng."),
 ("We watched a dolphin near the shore.","Chúng tôi ngắm một con cá heo gần bờ.")],
"shark": [("A shark lives in warm seas.","Cá mập sống ở vùng biển ấm."),
 ("The shark swam slowly past us.","Con cá mập bơi chậm ngang qua chúng tôi."),
 ("Not every shark attacks people.","Không phải con cá mập nào cũng tấn công người.")],
"crab": [("We caught a crab on the beach.","Chúng tôi bắt được một con cua trên bãi biển."),
 ("The crab walked sideways.","Con cua đi ngang."),
 ("A small crab hid under the rock.","Một con cua nhỏ trốn dưới tảng đá.")],
"mosquito": [("A mosquito bit my arm.","Một con muỗi cắn vào tay tôi."),
 ("The mosquito kept me awake.","Con muỗi khiến tôi mất ngủ."),
 ("Use a net to keep the mosquito out.","Dùng màn để tránh muỗi.")],
"parrot": [("The parrot can say my name.","Con vẹt biết gọi tên tôi."),
 ("Her parrot is green and yellow.","Con vẹt của cô ấy màu xanh vàng."),
 ("The parrot repeated every word.","Con vẹt nhại lại từng từ.")],
}
