# -*- coding: utf-8 -*-
TOPIC = 10  # Emotions — Cảm xúc
DATA = {
"happy": [("I am happy to see you.","Tôi vui khi gặp bạn."),
 ("She looks happy today.","Hôm nay cô ấy trông vui vẻ."),
 ("Small things make me happy.","Những điều nhỏ bé làm tôi vui.")],
"sad": [("She looks sad today.","Hôm nay cô ấy trông buồn."),
 ("The ending of the film was sad.","Cái kết của bộ phim thật buồn."),
 ("He felt sad after saying goodbye.","Anh ấy buồn sau khi nói lời tạm biệt.")],
"angry": [("He was angry about the news.","Anh ấy tức giận vì tin đó."),
 ("Do not drive when you are angry.","Đừng lái xe khi đang tức giận."),
 ("She gets angry very easily.","Cô ấy rất dễ nổi giận.")],
"afraid": [("I am afraid of the dark.","Tôi sợ bóng tối."),
 ("Do not be afraid to ask.","Đừng ngại hỏi."),
 ("He is afraid of losing his job.","Anh ấy sợ mất việc.")],
"scared": [("The child looked scared.","Đứa bé trông hoảng sợ."),
 ("I was scared by the loud noise.","Tôi hoảng vì tiếng động lớn."),
 ("She is scared of flying.","Cô ấy sợ đi máy bay.")],
"worried": [("She is worried about the exam.","Cô ấy lo lắng về kỳ thi."),
 ("His parents are worried about him.","Bố mẹ anh ấy lo cho anh ấy."),
 ("Do not be worried, it will be fine.","Đừng lo, sẽ ổn thôi.")],
"nervous": [("I feel nervous before speaking.","Tôi hồi hộp trước khi phát biểu."),
 ("She was nervous at the interview.","Cô ấy hồi hộp trong buổi phỏng vấn."),
 ("He gets nervous around new people.","Anh ấy hồi hộp khi gặp người lạ.")],
"excited": [("We are excited about the trip.","Chúng tôi háo hức về chuyến đi."),
 ("The children are excited for Tet.","Bọn trẻ háo hức chờ Tết."),
 ("She was too excited to sleep.","Cô ấy phấn khích quá không ngủ được.")],
"bored": [("The students look bored.","Học sinh trông chán nản."),
 ("I get bored on long trips.","Tôi thấy chán trong những chuyến đi dài."),
 ("He was bored of the same routine.","Anh ấy chán cái nếp sinh hoạt lặp lại.")],
"tired": [("I am tired after work.","Tôi mệt sau khi đi làm."),
 ("She looked tired this morning.","Sáng nay cô ấy trông mệt."),
 ("He is tired of waiting.","Anh ấy chán chờ đợi rồi.")],
"surprised": [("She was surprised by the gift.","Cô ấy bất ngờ vì món quà."),
 ("I am surprised to see you here.","Tôi ngạc nhiên khi thấy bạn ở đây."),
 ("Everyone was surprised by the result.","Ai cũng bất ngờ về kết quả.")],
"confused": [("I am confused by this question.","Tôi bối rối trước câu hỏi này."),
 ("She looked confused at the map.","Cô ấy bối rối nhìn tấm bản đồ."),
 ("The instructions left me confused.","Hướng dẫn khiến tôi rối trí.")],
"calm": [("Please stay calm.","Hãy bình tĩnh."),
 ("She stayed calm during the storm.","Cô ấy bình tĩnh suốt cơn bão."),
 ("His calm voice helped everyone.","Giọng nói bình tĩnh của anh ấy giúp mọi người.")],
"relaxed": [("I feel relaxed at the beach.","Tôi thấy thư thái ở bãi biển."),
 ("He looks relaxed after the holiday.","Anh ấy trông thư thái sau kỳ nghỉ."),
 ("The music made me relaxed.","Bản nhạc khiến tôi thư giãn.")],
"proud": [("His parents are proud of him.","Bố mẹ anh ấy tự hào về anh ấy."),
 ("She is proud of her work.","Cô ấy tự hào về công việc của mình."),
 ("We are proud to be here.","Chúng tôi tự hào có mặt ở đây.")],
"shy": [("She is shy with strangers.","Cô ấy nhút nhát với người lạ."),
 ("He was too shy to speak.","Cậu ấy nhút nhát quá không dám nói."),
 ("The shy boy sat in the corner.","Cậu bé nhút nhát ngồi ở góc.")],
"lonely": [("He feels lonely sometimes.","Đôi khi anh ấy thấy cô đơn."),
 ("She was lonely in the big city.","Cô ấy cô đơn giữa thành phố lớn."),
 ("A pet helps when you feel lonely.","Nuôi thú cưng giúp bạn bớt cô đơn.")],
"jealous": [("Do not be jealous of others.","Đừng ghen tị với người khác."),
 ("He was jealous of her success.","Anh ta ghen tị với thành công của cô ấy."),
 ("She gets jealous very easily.","Cô ấy rất dễ ghen.")],
"grateful": [("I am grateful for your help.","Tôi biết ơn sự giúp đỡ của bạn."),
 ("She is grateful to her teachers.","Cô ấy biết ơn các thầy cô."),
 ("We should be grateful for small things.","Chúng ta nên biết ơn những điều nhỏ bé.")],
"disappointed": [("We were disappointed by the result.","Chúng tôi thất vọng vì kết quả."),
 ("He was disappointed in himself.","Anh ấy thất vọng về chính mình."),
 ("She looked disappointed but said nothing.","Cô ấy trông thất vọng nhưng không nói gì.")],
"upset": [("She was upset after the call.","Cô ấy buồn bực sau cuộc gọi."),
 ("Do not get upset over small things.","Đừng bực mình vì chuyện nhỏ."),
 ("He was upset that nobody told him.","Anh ấy bực vì không ai nói cho biết.")],
"cheerful": [("He has a cheerful voice.","Anh ấy có giọng nói vui tươi."),
 ("She is always cheerful in the morning.","Cô ấy luôn vui vẻ vào buổi sáng."),
 ("The room has a cheerful yellow color.","Căn phòng có màu vàng tươi vui.")],
"anxious": [("She feels anxious in crowds.","Cô ấy lo âu khi ở chỗ đông người."),
 ("He was anxious about the results.","Anh ấy lo lắng về kết quả."),
 ("Coffee makes me anxious.","Cà phê khiến tôi bồn chồn.")],
"confident": [("He is confident when speaking.","Anh ấy tự tin khi nói."),
 ("She is confident about the future.","Cô ấy tự tin về tương lai."),
 ("Practice makes you confident.","Luyện tập giúp bạn tự tin.")],
"embarrassed": [("I felt embarrassed at the party.","Tôi ngượng ở bữa tiệc."),
 ("He was embarrassed by his mistake.","Anh ấy xấu hổ vì sai lầm của mình."),
 ("She got embarrassed when everyone looked.","Cô ấy ngượng khi ai cũng nhìn.")],
"frustrated": [("He was frustrated by the delay.","Anh ấy bực bội vì bị trễ."),
 ("I feel frustrated when nothing works.","Tôi bực khi chẳng cái gì chạy."),
 ("She became frustrated with the slow internet.","Cô ấy bực mình vì mạng chậm.")],
"hopeful": [("We are hopeful about the future.","Chúng tôi hy vọng vào tương lai."),
 ("She sounded hopeful on the phone.","Giọng cô ấy đầy hy vọng qua điện thoại."),
 ("They remain hopeful despite the news.","Họ vẫn hy vọng dù có tin đó.")],
"curious": [("Children are naturally curious.","Trẻ em vốn tò mò."),
 ("I am curious about your plan.","Tôi tò mò về kế hoạch của bạn."),
 ("She gave me a curious look.","Cô ấy nhìn tôi đầy tò mò.")],
"satisfied": [("I am satisfied with the service.","Tôi hài lòng với dịch vụ."),
 ("He is never satisfied with his work.","Anh ấy chẳng bao giờ hài lòng với việc mình làm."),
 ("The customer left satisfied.","Khách hàng ra về hài lòng.")],
"annoyed": [("He was annoyed by the noise.","Anh ấy khó chịu vì tiếng ồn."),
 ("She looked annoyed at the question.","Cô ấy tỏ vẻ khó chịu với câu hỏi."),
 ("I get annoyed when people are late.","Tôi khó chịu khi người ta đến muộn.")],
"delighted": [("She was delighted with the news.","Cô ấy vui sướng với tin đó."),
 ("We are delighted to have you here.","Chúng tôi rất vui vì có bạn ở đây."),
 ("He was delighted by the surprise.","Anh ấy vui sướng vì món bất ngờ.")],
"stressed": [("I feel stressed before deadlines.","Tôi căng thẳng trước hạn chót."),
 ("She is stressed about money.","Cô ấy căng thẳng vì tiền bạc."),
 ("Exercise helps when you are stressed.","Tập thể dục giúp ích khi bạn căng thẳng.")],
"comfortable": [("This chair is comfortable.","Cái ghế này thoải mái."),
 ("I feel comfortable with her.","Tôi thấy thoải mái khi ở bên cô ấy."),
 ("Wear comfortable shoes for the trip.","Hãy đi giày thoải mái cho chuyến đi.")],
"guilty": [("He felt guilty about lying.","Anh ấy thấy tội lỗi vì đã nói dối."),
 ("She looked guilty when asked.","Cô ấy tỏ vẻ có lỗi khi bị hỏi."),
 ("I feel guilty for forgetting her birthday.","Tôi thấy có lỗi vì quên sinh nhật cô ấy.")],
"brave": [("She is brave and calm.","Cô ấy dũng cảm và bình tĩnh."),
 ("It was brave of him to speak up.","Anh ấy thật dũng cảm khi lên tiếng."),
 ("The brave firefighter saved two children.","Người lính cứu hoả dũng cảm cứu hai đứa trẻ.")],
"patient": [("Be patient with beginners.","Hãy kiên nhẫn với người mới."),
 ("She is very patient with children.","Cô ấy rất kiên nhẫn với trẻ con."),
 ("You need to be patient to learn a language.","Bạn cần kiên nhẫn để học một ngôn ngữ.")],
"mood": [("She is in a good mood today.","Hôm nay cô ấy tâm trạng tốt."),
 ("Music can change your mood.","Âm nhạc có thể thay đổi tâm trạng."),
 ("He is in a bad mood this morning.","Sáng nay anh ấy tâm trạng không vui.")],
"feeling": [("It is a strange feeling.","Đó là một cảm giác lạ."),
 ("I had a feeling you would come.","Tôi có cảm giác bạn sẽ đến."),
 ("Do not hide your feelings.","Đừng giấu cảm xúc của bạn.")],
"laugh": [("We laughed all evening.","Chúng tôi cười suốt buổi tối."),
 ("His jokes always make me laugh.","Mấy câu đùa của anh ấy luôn làm tôi cười."),
 ("Do not laugh at other people.","Đừng cười nhạo người khác.")],
"cry": [("The baby began to cry.","Em bé bắt đầu khóc."),
 ("The film made her cry.","Bộ phim làm cô ấy khóc."),
 ("It is okay to cry sometimes.","Đôi khi khóc cũng không sao.")],
"joyful": [("It was a joyful reunion.","Đó là một cuộc đoàn tụ hân hoan."),
 ("The wedding was a joyful day.","Đám cưới là một ngày hân hoan."),
 ("Her joyful laugh filled the room.","Tiếng cười hân hoan của cô ấy vang khắp phòng.")],
"miserable": [("He felt miserable in the rain.","Anh ấy khổ sở trong mưa."),
 ("She was miserable after the loss.","Cô ấy khổ sở sau thất bại."),
 ("The cold weather made us miserable.","Thời tiết lạnh làm chúng tôi khổ sở.")],
"furious": [("She was furious about the delay.","Cô ấy giận dữ vì bị trễ."),
 ("He was furious when he heard the news.","Anh ấy nổi giận khi nghe tin."),
 ("My boss was furious this morning.","Sáng nay sếp tôi giận dữ.")],
"terrified": [("The child was terrified of dogs.","Đứa bé khiếp sợ chó."),
 ("She was terrified during the storm.","Cô ấy khiếp sợ trong cơn bão."),
 ("He looked terrified but kept walking.","Anh ấy trông khiếp sợ nhưng vẫn bước tiếp.")],
"amazed": [("We were amazed by the view.","Chúng tôi kinh ngạc trước khung cảnh."),
 ("I am amazed at how fast she learns.","Tôi kinh ngạc vì cô ấy học nhanh thế."),
 ("The children were amazed by the magic.","Bọn trẻ kinh ngạc trước màn ảo thuật.")],
"ashamed": [("He was ashamed of his mistake.","Anh ấy hổ thẹn vì lỗi lầm của mình."),
 ("She felt ashamed for shouting.","Cô ấy thấy hổ thẹn vì đã quát lên."),
 ("There is nothing to be ashamed of.","Chẳng có gì phải hổ thẹn cả.")],
"relieved": [("I felt relieved after the exam.","Tôi nhẹ nhõm sau kỳ thi."),
 ("She was relieved to hear he was safe.","Cô ấy nhẹ nhõm khi biết anh ấy an toàn."),
 ("He looked relieved when it ended.","Anh ấy trông nhẹ nhõm khi mọi chuyện kết thúc.")],
"sympathy": [("She showed great sympathy.","Cô ấy tỏ ra rất cảm thông."),
 ("He has no sympathy for lazy people.","Anh ấy không cảm thông với người lười."),
 ("They sent a card of sympathy.","Họ gửi một tấm thiệp chia buồn.")],
"envy": [("His success filled them with envy.","Thành công của anh ấy khiến họ ghen tị."),
 ("I envy your free time.","Tôi ghen tị với thời gian rảnh của bạn."),
 ("Envy never brings happiness.","Sự ghen tị chẳng bao giờ mang lại hạnh phúc.")],
"temper": [("He has a quick temper.","Anh ấy nóng tính."),
 ("She lost her temper at the meeting.","Cô ấy nổi nóng trong cuộc họp."),
 ("Try to control your temper.","Cố kiềm chế tính nóng của bạn.")],
}
