# -*- coding: utf-8 -*-
"""
Nghia tieng Viet cho tu hay gap trong truyen kinh dien — dot 1.

Day la nhung tu KHONG co trong kho 1900 tu cua app: tu co, tu van chuong,
hoac tu doi thuong nhung chua duoc dua vao giao trinh. Xep theo tan suat
xuat hien that trong 4 cuon sach (do bang tools/books/coverage.mjs).

Nghia viet NGAN va theo dung nghia trong truyen, khong liet ke moi nghia
tu dien — nguoi doc dang re chuot giua chung cau, can hieu ngay.
"""

WORDS = {
    "upon": "trên; vào lúc (lối viết cổ của on)",
    "such": "như vậy, như thế",
    "down": "xuống; đi xuống",
    "nothing": "không có gì",
    "shall": "sẽ (lối nói trang trọng/cổ)",
    "though": "mặc dù",
    "lady": "quý bà, phu nhân",
    "dear": "thân mến; ôi trời (thán từ)",
    "through": "xuyên qua, qua",
    "cried": "kêu lên, thốt lên; đã khóc",
    "myself": "chính tôi",
    "many": "nhiều",
    "few": "ít, một vài",
    "anything": "bất cứ thứ gì",
    "indeed": "quả thật, thật vậy",
    "those": "những cái đó, những người đó",
    "cannot": "không thể",
    "sir": "thưa ngài, thưa ông",
    "whole": "toàn bộ, cả",
    "against": "chống lại; dựa vào",
    "round": "quanh, vòng quanh; tròn",
    "whom": "người mà (tân ngữ của who)",
    "replied": "đáp lại, trả lời",
    "less": "ít hơn",
    "till": "cho đến khi",
    "either": "một trong hai; cũng (câu phủ định)",
    "whether": "liệu có... hay không",
    "everything": "mọi thứ",
    "married": "đã kết hôn; cưới",
    "pleasure": "niềm vui, sự hài lòng",
    "sort": "loại, kiểu",
    "four": "bốn",
    "nor": "cũng không",
    "suppose": "cho rằng, đoán là",
    "towards": "về phía",
    "colonel": "đại tá",
    "whose": "của ai, mà ... của người đó",
    "marriage": "hôn nhân, cuộc hôn nhân",
    "ladies": "các quý bà",
    "else": "khác, nữa",
    "conversation": "cuộc trò chuyện",
    "within": "bên trong; trong vòng",
    "therefore": "vì vậy, do đó",
    "certain": "chắc chắn; một ... nào đó",
    "remarked": "nhận xét, nói",
    "ought": "nên (ought to)",
    "silence": "sự im lặng",
    "gentleman": "quý ông, người đàn ông lịch thiệp",
    "happiness": "hạnh phúc",
    "several": "vài, một số",
    "glad": "vui mừng",
    "ten": "mười",
    "across": "băng qua, bên kia",
    "acquaintance": "người quen; sự quen biết",
    "perfectly": "hoàn toàn, một cách hoàn hảo",
    "object": "vật, đồ vật; mục đích; phản đối",
    "tried": "đã thử, đã cố",
    "impossible": "không thể được",
    "deal": "lượng lớn (a great deal); giao dịch",
    "along": "dọc theo",
    "general": "chung, phổ biến; vị tướng",
    "neither": "không cái nào trong hai",
    "carriage": "cỗ xe ngựa",
    "affection": "tình cảm trìu mến",
    "tone": "giọng điệu",
    "sense": "cảm giác; lý trí; ý nghĩa",
    "pride": "lòng kiêu hãnh, sự tự hào",
    "sight": "cảnh tượng; thị lực",
    "mine": "của tôi",
    "honour": "danh dự; vinh hạnh",
    "none": "không ai, không cái nào",
    "silent": "im lặng",
    "settled": "đã yên vị; đã giải quyết xong",
    "beyond": "vượt quá, bên kia",
    "whatever": "bất cứ điều gì",
    "everybody": "mọi người",
    "anyone": "bất cứ ai",
    "instantly": "ngay lập tức",
    "ill": "ốm, bệnh; xấu",
    "behaviour": "cách cư xử, hành vi",
    "hurried": "vội vã",
    "hall": "sảnh, đại sảnh",
    "convinced": "tin chắc, bị thuyết phục",
    "fear": "nỗi sợ; sợ",
    "sorry": "tiếc, xin lỗi",
    "steps": "các bước; bậc thềm",
    "situation": "tình huống, hoàn cảnh",
    "determined": "quyết tâm; đã xác định",
    "afterwards": "sau đó",
    "except": "ngoại trừ",
    "entirely": "hoàn toàn",
    "absolutely": "tuyệt đối, hoàn toàn",
    "lord": "huân tước, lãnh chúa",
    "usual": "thường lệ",
    "rose": "đứng dậy, dâng lên; hoa hồng",
    "regard": "sự quan tâm, lòng kính trọng; xem như",
    "scarcely": "hầu như không",
    "please": "làm hài lòng; xin vui lòng",
    "merely": "chỉ, đơn thuần",
    "dance": "khiêu vũ, buổi khiêu vũ",
    "observed": "quan sát thấy; nhận xét",
    "blue": "màu xanh lam",
    "manners": "cách cư xử, phép lịch sự",
    "pleased": "hài lòng, vui",
    "address": "địa chỉ; nói với, xưng hô",
    "assure": "cam đoan, bảo đảm",
    "agreeable": "dễ chịu, dễ mến",
    "fellow": "gã, chàng; bạn đồng hành",
    "expression": "vẻ mặt; cách diễn đạt",
    "fortune": "gia sản; vận may",
    "occurred": "xảy ra; chợt nảy ra trong đầu",
    "dare": "dám",
    "companion": "người bạn đồng hành",
    "beside": "bên cạnh",
    "toward": "về phía",
    "spirits": "tinh thần, tâm trạng",
    "ground": "mặt đất; khuôn viên",
    "pool": "vũng nước, ao",
    "particular": "cụ thể, riêng biệt; kỹ tính",
    "laid": "đặt, để (quá khứ của lay)",
    "step": "bước chân; bậc",
    "gentlemen": "các quý ông",
    "civility": "sự lịch thiệp, phép xã giao",
    "six": "sáu",
    "former": "trước kia; cái thứ nhất trong hai",
    "occasion": "dịp, cơ hội",
    "beauty": "vẻ đẹp; người đẹp",
    "natural": "tự nhiên",
    "struck": "đánh trúng; gây ấn tượng mạnh",
    "beg": "khẩn cầu, xin",
    "single": "độc thân; đơn lẻ",
    "neighbourhood": "vùng lân cận, khu xóm",
    "instant": "khoảnh khắc; tức thì",
    "amiable": "hoà nhã, dễ mến",
    "astonishment": "sự kinh ngạc",
    "curiosity": "sự tò mò",
    "fancy": "tưởng tượng; thích; cầu kỳ",
    "bright": "sáng; thông minh",
    "circumstances": "hoàn cảnh, tình cảnh",
    "extraordinary": "phi thường, khác thường",
    "affair": "chuyện, vụ việc",
    "miles": "dặm (đơn vị đo, ~1,6 km)",
    "dead": "đã chết",
    "excellent": "xuất sắc, tuyệt vời",
    "length": "chiều dài; at length: cuối cùng",
    "obliged": "buộc phải; hàm ơn",
    "particularly": "đặc biệt là",
    "scene": "cảnh, khung cảnh",
    "lawn": "bãi cỏ",
    "necessary": "cần thiết",
    "seven": "bảy",
    "easily": "dễ dàng",
    "attempt": "cố gắng, nỗ lực",
    "grey": "màu xám",
    "glanced": "liếc nhìn",
    "red": "màu đỏ",
    "officers": "sĩ quan; viên chức",
    "importance": "tầm quan trọng",
    "view": "quang cảnh; quan điểm",
    "colour": "màu sắc",
    "exceedingly": "vô cùng, hết sức",
    "assured": "cam đoan; chắc chắn",
    "upstairs": "trên gác, lên gác",
    "invitation": "lời mời",
    "carried": "mang, bế; đã chở",
    "instead": "thay vì, thay vào đó",
    "inquired": "hỏi thăm, dò hỏi",
    "visitor": "khách đến thăm",
    "sudden": "đột ngột",
    "master": "ông chủ; bậc thầy",
    "slight": "nhẹ, không đáng kể",
    "delight": "niềm vui thích",
    "pale": "nhợt nhạt, tái",
    "conduct": "cách hành xử; dẫn dắt",
    "absence": "sự vắng mặt",
    "figure": "dáng người; con số; hình",
    "excuse": "lời bào chữa; thứ lỗi",
    "twice": "hai lần",
    "eagerly": "hăm hở, háo hức",
    "spite": "in spite of: mặc dù; ác ý",
    "state": "trạng thái; tuyên bố; bang",
    "thoughts": "những suy nghĩ",
    "singular": "kỳ lạ, khác thường; số ít",
    "latter": "cái thứ hai trong hai",
    "satisfaction": "sự hài lòng, thoả mãn",
    "yellow": "màu vàng",
    "anybody": "bất cứ ai",
    "mad": "điên; tức giận",
    "dropped": "đánh rơi, thả xuống",
    "whenever": "bất cứ khi nào",
    "someone": "ai đó",
    "unless": "trừ khi",
    "frequently": "thường xuyên",
    "resolved": "quyết định dứt khoát; đã giải quyết",
    "kindness": "lòng tốt",
    "sake": "for the sake of: vì, cho",
    "disposition": "tính khí, bản tính",
    "equal": "ngang bằng",
    "thus": "như vậy, do đó",
    "impression": "ấn tượng",
    "confess": "thú nhận",
    "obvious": "hiển nhiên, rõ ràng",
    "favour": "sự ưu ái; việc giúp đỡ",
    "supposed": "được cho là; lẽ ra phải",
    "consequence": "hậu quả; tầm quan trọng",
    "sensible": "biết điều, khôn ngoan",
    "worth": "đáng giá",
    "remarkable": "đáng chú ý, phi thường",
    "frightened": "hoảng sợ",
    "nobody": "không ai",
    "remark": "lời nhận xét",
    "pleasant": "dễ chịu, thú vị",
    "crime": "tội ác",
    "peculiar": "kỳ quặc, riêng biệt",
    "mistaken": "nhầm lẫn",
    "client": "thân chủ, khách hàng",
    "considerable": "đáng kể",
    "madam": "thưa bà",
    "somebody": "ai đó",
    "nice": "tử tế, dễ chịu",
    "generally": "nói chung, thường thì",
    "hastily": "vội vàng",
    "pounds": "bảng Anh (tiền); pao (cân nặng)",
    "pause": "khoảng dừng; ngừng lại",
    "glance": "cái liếc nhìn",
    "countenance": "vẻ mặt, sắc mặt",
    "marked": "rõ rệt; đã đánh dấu",
    "besides": "ngoài ra, hơn nữa",
    "pardon": "thứ lỗi, xin lỗi",
    "sharp": "sắc bén; gay gắt",
    "dreadful": "khủng khiếp",
    "witness": "nhân chứng; chứng kiến",
    "perfect": "hoàn hảo",
    "desire": "khao khát, mong muốn",
    "glancing": "đang liếc nhìn",
    "photograph": "bức ảnh",
    "intention": "ý định",
    "compliment": "lời khen",
    "inquiries": "những câu hỏi thăm dò",
    "admiration": "sự ngưỡng mộ",
    "formed": "hình thành, tạo nên",
    "estate": "điền trang, cơ ngơi",
    "bit": "một chút; đã cắn",
    "creature": "sinh vật, con vật",
    "evidently": "rõ ràng là",
    "dancing": "khiêu vũ",
    "shown": "đã cho thấy",
    "observe": "quan sát; nhận xét",
    "private": "riêng tư",
    "forced": "bị ép buộc; gượng gạo",
    "concerned": "lo lắng; có liên quan",
    "presence": "sự hiện diện",
    "inspector": "thanh tra",
    "charming": "duyên dáng, quyến rũ",
    "caterpillar": "con sâu bướm",
    "somewhere": "đâu đó",
    "passage": "lối đi, hành lang; đoạn văn",
    "lying": "đang nằm; nói dối",
}
