# -*- coding: utf-8 -*-
"""
Nghia tieng Viet cho tu hay gap trong truyen kinh dien — dot 2.

Dot nay nghieng han sang tu LICH SU, vi da them Dickens "A Child's History of
England" va Wells "A Short History of the World": duke, earl, parliament,
reign, barons... Tinh lai tan suat tren ca 6 cuon.

Bo qua rac cua ban so hoa: illustration, seq, sar.
"""

WORDS = {
    # --- Vua chua, tuoc vi, trieu dinh ---
    "duke": "công tước",
    "earl": "bá tước (tước Anh)",
    "prince": "hoàng tử; thân vương",
    "princess": "công chúa",
    "princes": "các hoàng tử",
    "emperor": "hoàng đế",
    "monarch": "quân vương, vua",
    "throne": "ngai vàng",
    "crown": "vương miện; ngôi vua",
    "crowned": "được lên ngôi, đội vương miện",
    "reign": "triều đại; trị vì",
    "royal": "thuộc hoàng gia",
    "noble": "quý tộc; cao thượng",
    "nobles": "giới quý tộc",
    "noblemen": "các nhà quý tộc",
    "baron": "nam tước",
    "barons": "các nam tước",
    "cardinal": "hồng y",
    "archbishop": "tổng giám mục",
    "bishop": "giám mục",
    "bishops": "các giám mục",
    "abbey": "tu viện",
    "monks": "các thầy tu",
    "clergy": "giới tăng lữ",
    "priest": "linh mục, thầy tế",
    "priests": "các linh mục",
    "saint": "vị thánh",
    "palace": "cung điện",
    "parliament": "nghị viện, quốc hội",
    "council": "hội đồng",
    "dynasty": "triều đại, vương triều",
    "kingdom": "vương quốc",
    "empire": "đế quốc, đế chế",
    "empires": "các đế quốc",
    "republic": "nền cộng hoà",
    "dominions": "lãnh thổ cai trị",
    "favourite": "người được sủng ái; ưa thích nhất",

    # --- Chien tranh ---
    "army": "quân đội",
    "armies": "các đạo quân",
    "troops": "quân lính",
    "forces": "lực lượng, quân lực",
    "force": "vũ lực, sức mạnh; ép buộc",
    "battle": "trận đánh",
    "knights": "các hiệp sĩ",
    "sword": "thanh kiếm",
    "fleet": "hạm đội",
    "camp": "trại, doanh trại",
    "guard": "lính gác; canh gác",
    "conquest": "cuộc chinh phục",
    "conquered": "đã chinh phục, bị chinh phục",
    "seized": "chiếm lấy, bắt giữ",
    "marched": "hành quân",
    "march": "cuộc hành quân; tháng Ba",
    "treaty": "hiệp ước",
    "peace": "hoà bình",
    "enemy": "kẻ thù",
    "enemies": "quân địch, kẻ thù",
    "prisoner": "tù nhân, tù binh",
    "prisoners": "các tù binh",
    "prison": "nhà tù",
    "slave": "nô lệ",
    "slaves": "những người nô lệ",
    "tribes": "các bộ lạc",
    "castle": "lâu đài",
    "tower": "tháp; Tháp London",
    "fled": "bỏ chạy, chạy trốn",
    "blow": "cú đánh; thổi",
    "band": "nhóm, toán; ban nhạc",

    # --- Chinh tri, xa hoi ---
    "political": "thuộc chính trị",
    "civil": "dân sự; nội bộ (civil war: nội chiến)",
    "military": "thuộc quân sự",
    "national": "thuộc quốc gia",
    "authority": "quyền lực; nhà chức trách",
    "justice": "công lý; quan toà",
    "judge": "quan toà; xét xử",
    "trial": "phiên toà; cuộc thử nghiệm",
    "treason": "tội phản quốc",
    "execution": "cuộc hành quyết; sự thi hành",
    "executed": "bị hành quyết; đã thi hành",
    "murder": "vụ giết người",
    "murdered": "bị giết hại",
    "plot": "âm mưu; cốt truyện; mảnh đất",
    "revolution": "cuộc cách mạng",
    "declared": "tuyên bố",
    "established": "thiết lập, thành lập",
    "founded": "sáng lập",
    "appointed": "bổ nhiệm",
    "consent": "sự đồng ý",
    "act": "đạo luật; hành động; màn kịch",
    "claim": "yêu sách; đòi hỏi",
    "charge": "lời buộc tội; phí; xông lên",
    "possession": "quyền sở hữu; vật sở hữu",
    "possessions": "tài sản; thuộc địa",
    "property": "tài sản, của cải",
    "population": "dân số",
    "civilization": "nền văn minh",
    "civilizations": "các nền văn minh",
    "mankind": "loài người, nhân loại",
    "human": "thuộc con người",
    "race": "chủng tộc; cuộc đua",
    "education": "giáo dục",
    "development": "sự phát triển",
    "advance": "bước tiến; tiến lên",
    "process": "quá trình",
    "phase": "giai đoạn",
    "stage": "giai đoạn; sân khấu",
    "record": "ghi chép, hồ sơ; ghi lại",
    "series": "chuỗi, loạt",
    "relations": "quan hệ",
    "terms": "điều khoản; quan hệ (on good terms)",

    # --- Ton giao, tinh than ---
    "god": "vị thần; Chúa",
    "gods": "các vị thần",
    "holy": "thiêng liêng, thánh",
    "heaven": "thiên đường",
    "religious": "thuộc tôn giáo",
    "faith": "đức tin; lòng tin",
    "faithful": "trung thành",
    "belief": "niềm tin",
    "cross": "cây thánh giá; băng qua",
    "crossed": "đã băng qua",
    "moral": "thuộc đạo đức",
    "evil": "cái ác; xấu xa",
    "solemn": "trang nghiêm",
    "spirit": "tinh thần; linh hồn",
    "buried": "chôn cất",
    "grave": "nấm mồ; nghiêm trọng",

    # --- Dat dai, dia ly ---
    "land": "vùng đất; đất liền; hạ cánh",
    "lands": "các vùng đất",
    "central": "ở trung tâm",
    "centre": "trung tâm",
    "western": "thuộc phương Tây",
    "northern": "thuộc phương Bắc",
    "plain": "đồng bằng; giản dị; rõ ràng",
    "vast": "rộng lớn, mênh mông",
    "chief": "thủ lĩnh; chính yếu",
    "principal": "chính, chủ yếu; hiệu trưởng",
    "main": "chính, chủ yếu",
    "united": "hợp nhất, thống nhất",
    "independent": "độc lập",
    "sailed": "đi thuyền, ra khơi",
    "railway": "đường sắt",

    # --- Tu pho thong con thieu ---
    "third": "thứ ba",
    "fourth": "thứ tư",
    "fifth": "thứ năm",
    "sixth": "thứ sáu",
    "eight": "tám",
    "nine": "chín",
    "twelve": "mười hai",
    "fifteen": "mười lăm",
    "twenty": "hai mươi",
    "thirty": "ba mươi",
    "fifty": "năm mươi",
    "quarter": "một phần tư; khu phố",
    "rate": "tỉ lệ; mức giá; tốc độ",
    "although": "mặc dù",
    "altogether": "hoàn toàn; tổng cộng",
    "throughout": "suốt, khắp",
    "otherwise": "nếu không thì; cách khác",
    "wherever": "bất cứ nơi nào",
    "hitherto": "cho đến nay, từ trước tới giờ",
    "beneath": "bên dưới",
    "below": "phía dưới",
    "forth": "ra phía trước (and so forth: vân vân)",
    "arose": "nảy sinh, xuất hiện",
    "rising": "đang lên, trỗi dậy",
    "rise": "sự trỗi dậy; đứng lên",
    "gradually": "dần dần",
    "steadily": "đều đặn",
    "steady": "vững vàng, đều đặn",
    "chiefly": "chủ yếu là",
    "actually": "thực ra, thực sự",
    "possibly": "có thể",
    "possibility": "khả năng",
    "probable": "có khả năng xảy ra",
    "according": "according to: theo như",
    "directly": "trực tiếp; ngay lập tức",
    "readily": "sẵn sàng; dễ dàng",
    "extremely": "vô cùng",
    "enormous": "khổng lồ",
    "utmost": "tột bậc, hết mức",
    "mere": "chỉ là, thuần tuý",
    "similar": "tương tự",
    "various": "khác nhau, đa dạng",
    "superior": "cao cấp hơn; cấp trên",
    "minor": "nhỏ, thứ yếu",
    "proper": "đúng đắn, thích hợp",
    "absolute": "tuyệt đối",
    "secure": "an toàn; bảo đảm",
    "firm": "vững chắc; công ty",
    "bold": "táo bạo; in đậm",
    "cruel": "tàn nhẫn",
    "savage": "hung tợn, man rợ",
    "violent": "hung bạo, dữ dội",
    "wretched": "khốn khổ, thảm hại",
    "unhappy": "không vui, bất hạnh",
    "unfortunate": "không may",
    "innocent": "vô tội; ngây thơ",
    "ignorant": "dốt nát, không biết",
    "confusion": "sự hỗn loạn, bối rối",
    "difficulty": "sự khó khăn",
    "struggle": "cuộc đấu tranh; vật lộn",
    "loss": "sự mất mát; thua",
    "gained": "đạt được, giành được",
    "proved": "chứng tỏ, hoá ra là",
    "sought": "tìm kiếm (quá khứ của seek)",
    "persuaded": "thuyết phục",
    "pretended": "giả vờ",
    "proposed": "đề nghị; cầu hôn",
    "committed": "phạm (tội); cam kết",
    "attended": "tham dự; đi kèm",
    "removed": "loại bỏ, dời đi",
    "related": "liên quan; kể lại",
    "represented": "đại diện; thể hiện",
    "successful": "thành công",
    "powerful": "hùng mạnh",
    "strength": "sức mạnh",
    "command": "quyền chỉ huy; ra lệnh",
    "followers": "những người đi theo",
    "servant": "người hầu",
    "servants": "những người hầu",
    "crowd": "đám đông",
    "speech": "bài diễn văn; lời nói",
    "learnt": "đã học, đã biết được",
    "intellectual": "trí tuệ; trí thức",
    "scientific": "thuộc khoa học",
    "material": "vật chất; vật liệu",
    "existence": "sự tồn tại",
    "primitive": "nguyên thuỷ, sơ khai",
    "immediate": "ngay lập tức; gần kề",
    "eighteenth": "thứ mười tám",
    "eldest": "lớn tuổi nhất (trong nhà)",
    "youth": "tuổi trẻ; thanh niên",
    "maid": "người hầu gái; thiếu nữ",
    "supper": "bữa tối",
    "merry": "vui vẻ",
    "joy": "niềm vui sướng",
    "dislike": "sự không ưa",
    "opposed": "phản đối; đối lập",
    "sick": "ốm, buồn nôn",
    "dying": "đang hấp hối",
    "shot": "bắn; cú bắn",
    "burnt": "bị cháy, đã đốt",
    "beat": "đánh; nhịp đập",
    "thrust": "đâm, xô mạnh",
    "bore": "chịu đựng; mang (quá khứ của bear)",
    "bound": "bị trói; chắc chắn sẽ",
    "shut": "đóng lại",
    "edge": "mép, rìa; lưỡi dao",
    "neck": "cổ",
    "piece": "mảnh, miếng",
    "pieces": "các mảnh",
    "golden": "bằng vàng, vàng óng",
    "silver": "bạc",
    "green": "màu xanh lá",
    "darkness": "bóng tối",
    "fond": "be fond of: thích, quý mến",
    "personal": "cá nhân, riêng tư",
    "custom": "phong tục, tập quán",
    "traces": "dấu vết",
    "mark": "dấu; điểm số; đánh dấu",
    "form": "hình thức; mẫu đơn; tạo thành",
    "hunting": "săn bắn",
    "assembled": "tập hợp lại",
    "vain": "in vain: vô ích; kiêu ngạo",
    "fast": "nhanh; chặt; nhịn ăn",
    "rid": "get rid of: thoát khỏi, bỏ đi",
    "chapter": "chương (sách)",
}
